In [1]:
import os
import sys
PROJ_ROOT = "/root/autodl-tmp/jump"
sys.path.append(PROJ_ROOT)

import numpy as np
import polars as pl

from datetime import time, datetime, timedelta

from config import DataConfig, get_session_expr
from src.utils import get_raw_data, minus_time
data_cfg = DataConfig()
SYMBOLS = data_cfg.SYMBOLS
EXPR_DAY_SESSIONS = data_cfg.EXPR_DAY_SESSIONS
EXPR_NIGHT_SESSIONS = data_cfg.EXPR_NIGHT_SESSIONS
EXPR_MARKET_OPEN = data_cfg.EXPR_MARKET_OPEN
in_trading_session = EXPR_DAY_SESSIONS | EXPR_NIGHT_SESSIONS

IS_LAST_30MIN = (
    (pl.col("DATA_is_day_session").filter(in_trading_session) != pl.col("DATA_is_day_session").filter(in_trading_session).shift(-30)) |
    (
        (pl.col("DATA_is_day_session").filter(in_trading_session)) & (pl.col("Time").filter(in_trading_session).dt.date() != pl.col("Time").filter(in_trading_session).dt.date().shift(-30))
    )
)

In [2]:
sector = {}
exchange = {}
for s in SYMBOLS:
    if s in ["RB", "HC", "SS", "I", "J", "JM", "SF", "SM"]:
        sector[s] = "heise"    # 黑色系
    elif s in ["AU", "AG"]:
        sector[s] = "guijinshu"    # 贵金属
    elif s in ["CU", "AL", "ZN", "PB", "NI", "SN"]:
        sector[s] = "yousejinshu"    # 有色金属
    elif s in ["SC", "FU", "BU", "PG", "EG", "EB", "L", "V", "PP", "MA", "TA", "SA", "UR", "RU", "NR", "SP", "ZC"]:
        sector[s] = "nengyuanhuagong"    # 能源化工
    elif s in ["A", "B", "M", "Y", "P", "OI", "RM", "C", "CS", "RR", "CF", "CY", "AP", "CJ", "JD", "SR"]:
        sector[s] = "nongfuchanpin"    # 农副产品
    elif s in ["FB", "FG", "SP", "BP", "LW", "GP"]:
        sector[s] = "qinggongjiancai"    # 轻工建材
    else:
        print(s, " not included in sector classification!")

    if s in ["SC", "NR"]:
        exchange[s] = "INE"    # 上期能源
    elif s in ["CU", "AL", "ZN", "PB", "NI", "SN", "AU", "AG", "RB", "HC", "SS", "FU", "BU", "RU", "SP"]:
        exchange[s] = "SHFE"    # 上期所
    elif s in ["I", "J", "JM", "L", "V", "PP", "EG", "EB", "PG", "C", "CS", "A", "B", "M", "Y", "P", "RR", "FB", "JD"]:
        exchange[s] = "DCE"    # 大商所
    elif s in ["CF", "CY", "SR", "AP", "CJ", "OI", "RM", "TA", "MA", "SA", "FG", "ZC", "UR", "SF", "SM"]:
        exchange[s] = "CZCE"    # 郑商所
    else:
        print(s, " not included in exchange classification!")

In [11]:
valid_condition = (
    (pl.col("High") >= pl.col("Low")) & 
    (pl.col("High") >= pl.col("Open")) &
    (pl.col("High") >= pl.col("Close")) &
    (pl.col("Open") >= pl.col("Low")) &
    (pl.col("Close") >= pl.col("Low")) &
    (pl.col("Volume") >=0) & 
    (pl.col("Amount") >=0) & 
    (pl.col("Open Interest") >=0) &
    (pl.col("Open") >= 0) &
    (pl.col("Close") >= 0) &
    (pl.col("High") >= 0) &
    (pl.col("Low") >= 0)
)
symbol_with_null = []
for s in SYMBOLS:
    df = get_raw_data(s, lazy=False)

#--------------------Find rows with null-----------------------------------------------#
    l = len(df.filter(pl.any_horizontal(pl.all().is_null())))
    if l > 0:
        symbol_with_null.append(s)
    print(f"{s} has {l}/{len(df)} rows containing None.")
    
#--------------------Convert time col from string to datetime--------------------------#
    df = df.with_columns([
        pl.col("Time").str.strptime(
            pl.Datetime("us"),
            "%Y-%m-%d %H:%M:%S%.6f",
            strict=False,
        ).dt.truncate("1m"),
    ]).with_columns([
        pl.when(pl.col("Time").dt.hour() >= 20).then(pl.col("Time").dt.date() + pl.duration(days=1))
            .otherwise(pl.col("Time").dt.date()).alias("TradingDay")
    ]).drop_nulls().sort("Time")    # Because the only nulls are the last 20272 lines of FB

#--------------------Print rows violating validity conditions---------------------------#
    bad_df = df.filter(~valid_condition)
    if len(bad_df) > 0:
        print(f"{s} has bad data:")
        display(bad_df)

#--------------------Print rows out of trading hours------------------------------------#
    out_session_df = df.filter(~in_trading_session)
    if len(out_session_df) > 0:
        print(f"{s} has data out of the trading hours:")
        display(out_session_df)

#--------------------Add rows that are in trading hours but missing---------------------#
    dates = df.select(pl.col("TradingDay").alias("date")).unique().to_series().to_list()
    times = df.select(pl.col("Time")).unique().to_series().to_list()
    start_points = [time(9,0), time(10,30), time(13,30), time(21,0)]
    end_points = [
        time(10,14), time(11,29), time(14,59), time(22,59), 
        time(23,29), time(0,59), time(2,29)
    ]
    times_m1 = [dt - timedelta(minutes=1) for dt in times]
    times_p1 = [dt + timedelta(minutes=1) for dt in times]
    extra_times = (
        set(times_p1).intersection(set(times_m1))
    ).union(
        set([datetime.combine(d,t) for d in dates for t in end_points]).intersection(set(times_p1))
    ).union(
        set([datetime.combine(d,t) for d in dates for t in start_points]).intersection(set(times_m1))
    )
    extra_df = pl.DataFrame({"Time": list(extra_times)})

    full_times = pl.concat([df.select("Time"), extra_df]).unique().sort("Time")
    df = full_times.join(df, on="Time", how="left")

#--------------------Add masks to rows--------------------------------------------------#
    df = df.filter(in_trading_session).with_columns([
        pl.lit(s).alias("Symbol"),
        in_trading_session.alias("DATA_is_trading_hour"),
        ((~valid_condition) | (pl.col("Open").is_null())).alias("DATA_is_bad_data"),
        (pl.col("Open").is_null()).alias("DATA_is_missing_data"),
        EXPR_MARKET_OPEN.alias("DATA_is_market_open"),
    ])
    df = df.with_columns([
        pl.when(EXPR_DAY_SESSIONS).then(True)
            .when(EXPR_NIGHT_SESSIONS).then(False)
            .otherwise(None).alias("DATA_is_day_session"),
    ]).with_columns([
        (IS_LAST_30MIN).alias("DATA_is_last_30min"),
    ])

#--------------------Handle bad data---------------------------------------------------#
    bad = pl.col("DATA_is_bad_data") | pl.col("DATA_is_missing_data")
    df_cleaned = df.with_columns([
        pl.when(bad).then(0).otherwise(pl.col("Volume")).alias("Volume"),
        pl.when(bad).then(0).otherwise(pl.col("Amount")).alias("Amount"),
        pl.when(bad & in_trading_session).then(None).otherwise(pl.col("Open")).alias("Open"),
        pl.when(bad & in_trading_session).then(None).otherwise(pl.col("Close")).alias("Close"),
        pl.when(bad & in_trading_session).then(None).otherwise(pl.col("High")).alias("High"),
        pl.when(bad & in_trading_session).then(None).otherwise(pl.col("Low")).alias("Low"),
        pl.when(bad & in_trading_session).then(None).otherwise(pl.col("Open Interest")).alias("Open Interest"),
    ])
    df_cleaned = df_cleaned.with_columns([
        pl.col("Open").forward_fill(),
        pl.col("Close").forward_fill(),
        pl.col("High").forward_fill(),
        pl.col("Low").forward_fill(),
        pl.col("Open Interest").forward_fill(),
        pl.when(pl.col("Time").dt.hour() >= 20).then(pl.col("Time").dt.date() + pl.duration(days=1))
            .otherwise(pl.col("Time").dt.date()).alias("TradingDay"),
    ]).with_columns([
        pl.when(pl.col("TradingDay").dt.weekday() < 5).then(pl.col("TradingDay"))
            .otherwise(pl.col("TradingDay") + pl.duration(days=2)).alias("TradingDay")
    ]).rename({"Open Interest": "OpenInterest"}).drop_nulls()
    df_cleaned = df_cleaned.with_columns([
        pl.when(pl.col("Volume") == 0).then(0).otherwise(pl.col("Volume").log()).alias("LogVolume"),
        pl.when(pl.col("Amount") == 0).then(0).otherwise(pl.col("Amount").log()).alias("LogAmount"),
        pl.col("TradingDay").dt.month().alias("DATA_month"),
        pl.col("TradingDay").dt.weekday().alias("DATA_weekday"),
        pl.lit(sector[s]).alias("DATA_sector"),
        pl.lit(exchange[s]).alias("DATA_exchange")
    ])
    display(df_cleaned.filter(pl.col("DATA_is_missing_data")))

#--------------------Save cleaned data-------------------------------------------------#
    df_cleaned.write_parquet(f"{PROJ_ROOT}/data/cleaned_data/{s}.parquet", compression="zstd")

PP has 0/426905 rows containing None.
PP has data out of the trading hours:

shape: (2_941, 9)
┌────────────────┬──────────┬──────────┬──────────┬───┬────────┬───────────┬──────────┬────────────┐
│ Time           ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount    ┆ Open     ┆ TradingDay │
│ ---            ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---       ┆ Interest ┆ ---        │
│ datetime[μs]   ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64       ┆ ---      ┆ date       │
│                ┆          ┆          ┆          ┆   ┆        ┆           ┆ f64      ┆            │
╞════════════════╪══════════╪══════════╪══════════╪═══╪════════╪═══════════╪══════════╪════════════╡
│ 2014-03-03     ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 116.0  ┆ 6.20368e6 ┆ 21278.0  ┆ 2014-03-03 │
│ 08:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2014-03-03     ┆ 0.994016 ┆ 0.994016 ┆ 0.994016 ┆ … ┆ 0.0    ┆ 0.0       ┆ 18328.0  ┆ 2014-03-03 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2014-03-04     ┆ 1.000935 ┆ 1.000935 ┆ 1.000935 ┆ … ┆ 4.0    ┆ 214120.0  ┆ 21784.0  ┆ 2014-03-04 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2014-03-05     ┆ 1.006082 ┆ 1.006082 ┆ 1.006082 ┆ … ┆ 102.0  ┆ 5.28309e6 ┆ 24978.0  ┆ 2014-03-05 │
│ 08:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2014-03-05     ┆ 1.000255 ┆ 1.000255 ┆ 1.000255 ┆ … ┆ 0.0    ┆ 0.0       ┆ 23234.0  ┆ 2014-03-05 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ …              ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …         ┆ …        ┆ …          │
│ 2020-04-21     ┆ 1.320344 ┆ 1.320344 ┆ 1.320344 ┆ … ┆ 25.0   ┆ 817180.0  ┆ 433653.0 ┆ 2020-04-21 │
│ 11:30:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-04-21     ┆ 1.334281 ┆ 1.334281 ┆ 1.334281 ┆ … ┆ 4.0    ┆ 132090.0  ┆ 428732.0 ┆ 2020-04-21 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-04-22     ┆ 1.304994 ┆ 1.304994 ┆ 1.304994 ┆ … ┆ 12.0   ┆ 387615.0  ┆ 452826.0 ┆ 2020-04-22 │
│ 10:15:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-04-22     ┆ 1.300348 ┆ 1.300348 ┆ 1.300348 ┆ … ┆ 6.0    ┆ 193125.0  ┆ 446136.0 ┆ 2020-04-22 │
│ 11:30:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-04-22     ┆ 1.311255 ┆ 1.311255 ┆ 1.311053 ┆ … ┆ 55.0   ┆ 1.78506e6 ┆ 453395.0 ┆ 2020-04-22 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
└────────────────┴──────────┴──────────┴──────────┴───┴────────┴───────────┴──────────┴────────────┘

shape: (21, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2014-12-04 ┆ 0.940747 ┆ 0.940747 ┆ 0.940176 ┆ … ┆ 12         ┆ 4         ┆ nengyuanh ┆ DCE       │
│ 13:30:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2015-07-08 ┆ 0.96961  ┆ 0.96961  ┆ 0.96961  ┆ … ┆ 7          ┆ 3         ┆ nengyuanh ┆ DCE       │
│ 14:21:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-06-28 ┆ 1.517671 ┆ 1.517853 ┆ 1.517307 ┆ … ┆ 6          ┆ 7         ┆ nengyuanh ┆ DCE       │
│ 11:02:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-10-10 ┆ 1.555659 ┆ 1.556425 ┆ 1.555659 ┆ … ┆ 10         ┆ 7         ┆ nengyuanh ┆ DCE       │
│ 21:04:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-02-03 ┆ 1.372999 ┆ 1.372999 ┆ 1.372999 ┆ … ┆ 2          ┆ 1         ┆ nengyuanh ┆ DCE       │
│ 13:43:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-03-09 ┆ 1.360667 ┆ 1.360667 ┆ 1.360667 ┆ … ┆ 3          ┆ 1         ┆ nengyuanh ┆ DCE       │
│ 14:09:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-09 ┆ 1.360667 ┆ 1.360667 ┆ 1.360667 ┆ … ┆ 3          ┆ 1         ┆ nengyuanh ┆ DCE       │
│ 14:16:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-09 ┆ 1.360667 ┆ 1.360667 ┆ 1.360667 ┆ … ┆ 3          ┆ 1         ┆ nengyuanh ┆ DCE       │
│ 14:18:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-09 ┆ 1.360667 ┆ 1.360667 ┆ 1.360667 ┆ … ┆ 3          ┆ 1         ┆ nengyuanh ┆ DCE       │
│ 14:33:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-09 ┆ 1.360667 ┆ 1.360667 ┆ 1.360667 ┆ … ┆ 3          ┆ 1         ┆ nengyuanh ┆ DCE       │
│ 14:45:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

Y has 0/613704 rows containing None.
Y has data out of the trading hours:

shape: (3_120, 9)
┌─────────────┬──────────┬──────────┬──────────┬───┬────────┬────────────┬────────────┬────────────┐
│ Time        ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μs ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64        ┆ ---        ┆ date       │
│ ]           ┆          ┆          ┆          ┆   ┆        ┆            ┆ f64        ┆            │
╞═════════════╪══════════╪══════════╪══════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 2013-09-17  ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 1730.0 ┆ 1.227954e8 ┆ 702164.0   ┆ 2013-09-17 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-17  ┆ 1.000564 ┆ 1.000564 ┆ 1.000564 ┆ … ┆ 46.0   ┆ 3.26776e6  ┆ 665940.0   ┆ 2013-09-17 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-18  ┆ 1.001972 ┆ 1.001972 ┆ 1.001972 ┆ … ┆ 3086.0 ┆ 2.1947632e ┆ 666602.0   ┆ 2013-09-18 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆ 8          ┆            ┆            │
│ 2013-09-18  ┆ 0.996055 ┆ 0.996055 ┆ 0.996055 ┆ … ┆ 0.0    ┆ 0.0        ┆ 660060.0   ┆ 2013-09-18 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-23  ┆ 0.986193 ┆ 0.986193 ┆ 0.986193 ┆ … ┆ 5546.0 ┆ 3.8822e8   ┆ 657822.0   ┆ 2013-09-23 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ …           ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 2020-04-23  ┆ 0.538343 ┆ 0.538343 ┆ 0.538343 ┆ … ┆ 6.0    ┆ 329360.0   ┆ 459132.0   ┆ 2020-04-23 │
│ 11:30:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-04-23  ┆ 0.540696 ┆ 0.540696 ┆ 0.540696 ┆ … ┆ 2.0    ┆ 110280.0   ┆ 457173.0   ┆ 2020-04-23 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-04-24  ┆ 0.537166 ┆ 0.537166 ┆ 0.537166 ┆ … ┆ 1.0    ┆ 54780.0    ┆ 453829.0   ┆ 2020-04-24 │
│ 11:30:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-04-24  ┆ 0.533832 ┆ 0.533832 ┆ 0.533832 ┆ … ┆ 22.0   ┆ 1.1977e6   ┆ 448158.0   ┆ 2020-04-24 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-04-27  ┆ 0.526576 ┆ 0.526576 ┆ 0.526576 ┆ … ┆ 1.0    ┆ 53700.0    ┆ 445540.0   ┆ 2020-04-27 │
│ 10:15:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
└─────────────┴──────────┴──────────┴──────────┴───┴────────┴────────────┴────────────┴────────────┘

shape: (18, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2014-12-04 ┆ 0.768276 ┆ 0.768276 ┆ 0.767461 ┆ … ┆ 12         ┆ 4         ┆ nongfucha ┆ DCE       │
│ 13:30:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2014-12-31 ┆ 0.778863 ┆ 0.778863 ┆ 0.778863 ┆ … ┆ 12         ┆ 3         ┆ nongfucha ┆ DCE       │
│ 01:09:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2015-01-20 ┆ 0.757417 ┆ 0.757417 ┆ 0.757145 ┆ … ┆ 1          ┆ 2         ┆ nongfucha ┆ DCE       │
│ 01:51:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2015-01-20 ┆ 0.757417 ┆ 0.757417 ┆ 0.757417 ┆ … ┆ 1          ┆ 2         ┆ nongfucha ┆ DCE       │
│ 02:12:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2015-02-10 ┆ 0.746286 ┆ 0.746286 ┆ 0.746286 ┆ … ┆ 2          ┆ 2         ┆ nongfucha ┆ DCE       │
│ 01:18:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2018-08-24 ┆ 0.634724 ┆ 0.63559  ┆ 0.634724 ┆ … ┆ 8          ┆ 1         ┆ nongfucha ┆ DCE       │
│ 21:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-10-10 ┆ 0.594664 ┆ 0.594863 ┆ 0.594466 ┆ … ┆ 10         ┆ 7         ┆ nongfucha ┆ DCE       │
│ 21:04:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-02-03 ┆ 0.599228 ┆ 0.599228 ┆ 0.599228 ┆ … ┆ 2          ┆ 1         ┆ nongfucha ┆ DCE       │
│ 14:38:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-03-09 ┆ 0.542282 ┆ 0.542282 ┆ 0.542282 ┆ … ┆ 3          ┆ 1         ┆ nongfucha ┆ DCE       │
│ 14:02:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-03-09 ┆ 0.542282 ┆ 0.542282 ┆ 0.542282 ┆ … ┆ 3          ┆ 1         ┆ nongfucha ┆ DCE       │
│ 14:16:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

OI has 0/580930 rows containing None.
OI has bad data:

shape: (5, 9)
┌────────────┬──────────┬──────────┬──────────┬───┬───────────┬────────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume    ┆ Amount     ┆ Open      ┆ TradingDa │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---        ┆ Interest  ┆ y         │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64       ┆ f64        ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆           ┆            ┆ f64       ┆ date      │
╞════════════╪══════════╪══════════╪══════════╪═══╪═══════════╪════════════╪═══════════╪═══════════╡
│ 2018-01-11 ┆ 0.777548 ┆ 0.777548 ┆ 0.777548 ┆ … ┆ -66562.0  ┆ -4.3678e9  ┆ 281056.0  ┆ 2018-01-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 2         │
│ 2018-08-13 ┆ 0.731778 ┆ 0.731778 ┆ 0.731778 ┆ … ┆ -216522.0 ┆ -1.4243e10 ┆ 380266.0  ┆ 2018-08-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 4         │
│ 2018-09-25 ┆ 0.734447 ┆ 0.734447 ┆ 0.734447 ┆ … ┆ -242010.0 ┆ -1.5978e10 ┆ 417158.0  ┆ 2018-09-2 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 5         │
│ 2018-10-16 ┆ 0.750133 ┆ 0.750133 ┆ 0.750133 ┆ … ┆ -245980.0 ┆ -1.6586e10 ┆ 394668.0  ┆ 2018-10-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 7         │
│ 2019-01-02 ┆ 0.69697  ┆ 0.69697  ┆ 0.69697  ┆ … ┆ -101502.0 ┆ -6.5276e9  ┆ 275184.0  ┆ 2019-01-0 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 2         │
└────────────┴──────────┴──────────┴──────────┴───┴───────────┴────────────┴───────────┴───────────┘

OI has data out of the trading hours:

shape: (1_582, 9)
┌─────────────┬──────────┬──────────┬──────────┬───┬────────┬────────────┬────────────┬────────────┐
│ Time        ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μs ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64        ┆ ---        ┆ date       │
│ ]           ┆          ┆          ┆          ┆   ┆        ┆            ┆ f64        ┆            │
╞═════════════╪══════════╪══════════╪══════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 2013-09-30  ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 186.0  ┆ 1.33734e7  ┆ 141358.0   ┆ 2013-09-30 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-10-09  ┆ 1.009179 ┆ 1.009179 ┆ 1.009179 ┆ … ┆ 172.0  ┆ 1.248032e7 ┆ 137960.0   ┆ 2013-10-09 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-10-09  ┆ 1.013908 ┆ 1.013908 ┆ 1.013908 ┆ … ┆ 20.0   ┆ 1.458e6    ┆ 146112.0   ┆ 2013-10-09 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-10-10  ┆ 1.015021 ┆ 1.015021 ┆ 1.015021 ┆ … ┆ 380.0  ┆ 2.77324e7  ┆ 146214.0   ┆ 2013-10-10 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-10-10  ┆ 1.020306 ┆ 1.020306 ┆ 1.020306 ┆ … ┆ 6.0    ┆ 440160.0   ┆ 141882.0   ┆ 2013-10-10 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ …           ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 2021-01-26  ┆ 1.178771 ┆ 1.178771 ┆ 1.178771 ┆ … ┆ 567.0  ┆ 5.519745e6 ┆ 143863.0   ┆ 2021-01-27 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-27  ┆ 1.198629 ┆ 1.198629 ┆ 1.198629 ┆ … ┆ 354.0  ┆ 3.504246e6 ┆ 149837.0   ┆ 2021-01-28 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-28  ┆ 1.201051 ┆ 1.201051 ┆ 1.201051 ┆ … ┆ 392.0  ┆ 3.888248e6 ┆ 150552.0   ┆ 2021-01-29 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-29  ┆ 1.192575 ┆ 1.192575 ┆ 1.192575 ┆ … ┆ 496.0  ┆ 4.885104e6 ┆ 145694.0   ┆ 2021-01-30 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-02-01  ┆ 1.177439 ┆ 1.177439 ┆ 1.177439 ┆ … ┆ 241.0  ┆ 2.343484e6 ┆ 149140.0   ┆ 2021-02-02 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
└─────────────┴──────────┴──────────┴──────────┴───┴────────┴────────────┴────────────┴────────────┘

shape: (72, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2014-08-06 ┆ 0.920403 ┆ 0.920403 ┆ 0.920403 ┆ … ┆ 8          ┆ 3         ┆ nongfucha ┆ CZCE      │
│ 09:51:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2014-10-16 ┆ 0.846908 ┆ 0.846908 ┆ 0.846908 ┆ … ┆ 10         ┆ 4         ┆ nongfucha ┆ CZCE      │
│ 10:04:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2015-02-17 ┆ 0.827922 ┆ 0.827922 ┆ 0.827637 ┆ … ┆ 2          ┆ 2         ┆ nongfucha ┆ CZCE      │
│ 10:57:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2015-02-25 ┆ 0.822237 ┆ 0.822237 ┆ 0.822237 ┆ … ┆ 2          ┆ 3         ┆ nongfucha ┆ CZCE      │
│ 11:25:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2015-03-16 ┆ 0.822254 ┆ 0.822254 ┆ 0.822254 ┆ … ┆ 3          ┆ 1         ┆ nongfucha ┆ CZCE      │
│ 11:26:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-03-09 ┆ 0.769592 ┆ 0.769592 ┆ 0.769592 ┆ … ┆ 3          ┆ 1         ┆ nongfucha ┆ CZCE      │
│ 14:33:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-03-09 ┆ 0.769592 ┆ 0.769592 ┆ 0.769592 ┆ … ┆ 3          ┆ 1         ┆ nongfucha ┆ CZCE      │
│ 14:36:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-03-09 ┆ 0.769592 ┆ 0.769592 ┆ 0.769592 ┆ … ┆ 3          ┆ 1         ┆ nongfucha ┆ CZCE      │
│ 14:39:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-03-09 ┆ 0.769592 ┆ 0.769592 ┆ 0.769592 ┆ … ┆ 3          ┆ 1         ┆ nongfucha ┆ CZCE      │
│ 14:45:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-03-09 ┆ 0.769592 ┆ 0.769592 ┆ 0.769592 ┆ … ┆ 3          ┆ 1         ┆ nongfucha ┆ CZCE      │
│ 14:47:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

EB has 0/104080 rows containing None.
EB has data out of the trading hours:

shape: (138, 9)
┌─────────────────┬──────────┬──────────┬──────────┬───┬────────┬──────────┬──────────┬────────────┐
│ Time            ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount   ┆ Open     ┆ TradingDay │
│ ---             ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---      ┆ Interest ┆ ---        │
│ datetime[μs]    ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64      ┆ ---      ┆ date       │
│                 ┆          ┆          ┆          ┆   ┆        ┆          ┆ f64      ┆            │
╞═════════════════╪══════════╪══════════╪══════════╪═══╪════════╪══════════╪══════════╪════════════╡
│ 2019-09-27      ┆ 0.990025 ┆ 0.990025 ┆ 0.990025 ┆ … ┆ 0.0    ┆ 0.0      ┆ 15074.0  ┆ 2019-09-27 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2019-09-30      ┆ 0.994514 ┆ 0.994514 ┆ 0.994514 ┆ … ┆ 0.0    ┆ 0.0      ┆ 13464.0  ┆ 2019-09-30 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2019-10-08      ┆ 0.993516 ┆ 0.993516 ┆ 0.993516 ┆ … ┆ 0.0    ┆ 0.0      ┆ 14208.0  ┆ 2019-10-08 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2019-10-09      ┆ 0.991521 ┆ 0.991521 ┆ 0.991521 ┆ … ┆ 0.0    ┆ 0.0      ┆ 15982.0  ┆ 2019-10-09 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2019-10-10      ┆ 0.97793  ┆ 0.97793  ┆ 0.97793  ┆ … ┆ 0.0    ┆ 0.0      ┆ 21110.0  ┆ 2019-10-10 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ …               ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …        ┆ …        ┆ …          │
│ 2020-04-01      ┆ 0.551621 ┆ 0.551621 ┆ 0.551621 ┆ … ┆ 0.0    ┆ 0.0      ┆ 78269.0  ┆ 2020-04-01 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-04-02      ┆ 0.581796 ┆ 0.581796 ┆ 0.581796 ┆ … ┆ 1.0    ┆ 23330.0  ┆ 74460.0  ┆ 2020-04-02 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-04-03      ┆ 0.608978 ┆ 0.608978 ┆ 0.608978 ┆ … ┆ 6.0    ┆ 146495.0 ┆ 66333.0  ┆ 2020-04-03 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-04-07      ┆ 0.61596  ┆ 0.61596  ┆ 0.61596  ┆ … ┆ 10.0   ┆ 247000.0 ┆ 58340.0  ┆ 2020-04-07 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-04-08      ┆ 0.623317 ┆ 0.623317 ┆ 0.623317 ┆ … ┆ 3.0    ┆ 74985.0  ┆ 49438.0  ┆ 2020-04-08 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
└─────────────────┴──────────┴──────────┴──────────┴───┴────────┴──────────┴──────────┴────────────┘

shape: (128, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2019-09-27 ┆ 0.990274 ┆ 0.990524 ┆ 0.990274 ┆ … ┆ 9          ┆ 7         ┆ nengyuanh ┆ DCE       │
│ 11:10:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-09-27 ┆ 0.990773 ┆ 0.991521 ┆ 0.990773 ┆ … ┆ 9          ┆ 7         ┆ nengyuanh ┆ DCE       │
│ 13:57:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-09-27 ┆ 0.993516 ┆ 0.993516 ┆ 0.993267 ┆ … ┆ 9          ┆ 1         ┆ nengyuanh ┆ DCE       │
│ 22:38:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-09-30 ┆ 0.99202  ┆ 0.992145 ┆ 0.99202  ┆ … ┆ 9          ┆ 1         ┆ nengyuanh ┆ DCE       │
│ 09:53:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-09-30 ┆ 0.992145 ┆ 0.992145 ┆ 0.992145 ┆ … ┆ 9          ┆ 1         ┆ nengyuanh ┆ DCE       │
│ 09:55:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-03-19 ┆ 0.631047 ┆ 0.631047 ┆ 0.631047 ┆ … ┆ 3          ┆ 4         ┆ nengyuanh ┆ DCE       │
│ 13:38:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-19 ┆ 0.631047 ┆ 0.631047 ┆ 0.631047 ┆ … ┆ 3          ┆ 4         ┆ nengyuanh ┆ DCE       │
│ 13:43:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-19 ┆ 0.631047 ┆ 0.631047 ┆ 0.631047 ┆ … ┆ 3          ┆ 4         ┆ nengyuanh ┆ DCE       │
│ 14:42:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-19 ┆ 0.631047 ┆ 0.631047 ┆ 0.631047 ┆ … ┆ 3          ┆ 4         ┆ nengyuanh ┆ DCE       │
│ 14:44:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-19 ┆ 0.631047 ┆ 0.631047 ┆ 0.631047 ┆ … ┆ 3          ┆ 4         ┆ nengyuanh ┆ DCE       │
│ 14:46:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

NR has 0/100922 rows containing None.
NR has bad data:

shape: (3, 9)
┌─────────────────┬──────────┬──────────┬──────────┬───┬────────┬──────────┬──────────┬────────────┐
│ Time            ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount   ┆ Open     ┆ TradingDay │
│ ---             ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---      ┆ Interest ┆ ---        │
│ datetime[μs]    ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64      ┆ ---      ┆ date       │
│                 ┆          ┆          ┆          ┆   ┆        ┆          ┆ f64      ┆            │
╞═════════════════╪══════════╪══════════╪══════════╪═══╪════════╪══════════╪══════════╪════════════╡
│ 2019-09-11      ┆ 1.04499  ┆ 1.043456 ┆ 1.038855 ┆ … ┆ 80.0   ┆ 8.154e6  ┆ 27074.0  ┆ 2019-09-12 │
│ 21:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2019-10-09      ┆ 0.998978 ┆ 1.0      ┆ 0.999489 ┆ … ┆ 34.0   ┆ 3.324e6  ┆ 22308.0  ┆ 2019-10-10 │
│ 21:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2019-10-11      ┆ 1.00818  ┆ 1.007157 ┆ 1.006646 ┆ … ┆ 12.0   ┆ 1.1815e6 ┆ 22838.0  ┆ 2019-10-12 │
│ 21:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
└─────────────────┴──────────┴──────────┴──────────┴───┴────────┴──────────┴──────────┴────────────┘

NR has data out of the trading hours:

shape: (176, 9)
┌───────────────┬──────────┬──────────┬──────────┬───┬────────┬────────┬──────────┬────────────┐
│ Time          ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount ┆ Open     ┆ TradingDay │
│ ---           ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---    ┆ Interest ┆ ---        │
│ datetime[μs]  ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64    ┆ ---      ┆ date       │
│               ┆          ┆          ┆          ┆   ┆        ┆        ┆ f64      ┆            │
╞═══════════════╪══════════╪══════════╪══════════╪═══╪════════╪════════╪══════════╪════════════╡
│ 2019-08-13    ┆ 1.007669 ┆ 1.007669 ┆ 1.007669 ┆ … ┆ 0.0    ┆ 0.0    ┆ 17864.0  ┆ 2019-08-13 │
│ 15:00:00      ┆          ┆          ┆          ┆   ┆        ┆        ┆          ┆            │
│ 2019-08-14    ┆ 1.021984 ┆ 1.021984 ┆ 1.021984 ┆ … ┆ 0.0    ┆ 0.0    ┆ 23014.0  ┆ 2019-08-14 │
│ 15:00:00      ┆          ┆          ┆          ┆   ┆        ┆        ┆          ┆            │
│ 2019-08-15    ┆ 1.008691 ┆ 1.008691 ┆ 1.008691 ┆ … ┆ 0.0    ┆ 0.0    ┆ 23046.0  ┆ 2019-08-15 │
│ 15:00:00      ┆          ┆          ┆          ┆   ┆        ┆        ┆          ┆            │
│ 2019-08-16    ┆ 1.009714 ┆ 1.009714 ┆ 1.009714 ┆ … ┆ 0.0    ┆ 0.0    ┆ 22704.0  ┆ 2019-08-16 │
│ 15:00:00      ┆          ┆          ┆          ┆   ┆        ┆        ┆          ┆            │
│ 2019-08-19    ┆ 1.025562 ┆ 1.025562 ┆ 1.025562 ┆ … ┆ 0.0    ┆ 0.0    ┆ 25496.0  ┆ 2019-08-19 │
│ 15:00:00      ┆          ┆          ┆          ┆   ┆        ┆        ┆          ┆            │
│ …             ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …      ┆ …        ┆ …          │
│ 2020-04-14    ┆ 0.812041 ┆ 0.812041 ┆ 0.812041 ┆ … ┆ 0.0    ┆ 0.0    ┆ 8961.0   ┆ 2020-04-14 │
│ 15:00:00      ┆          ┆          ┆          ┆   ┆        ┆        ┆          ┆            │
│ 2020-04-15    ┆ 0.805049 ┆ 0.805049 ┆ 0.805049 ┆ … ┆ 0.0    ┆ 0.0    ┆ 8771.0   ┆ 2020-04-15 │
│ 15:00:00      ┆          ┆          ┆          ┆   ┆        ┆        ┆          ┆            │
│ 2020-04-16    ┆ 0.793064 ┆ 0.793064 ┆ 0.793064 ┆ … ┆ 0.0    ┆ 0.0    ┆ 8841.0   ┆ 2020-04-16 │
│ 15:00:00      ┆          ┆          ┆          ┆   ┆        ┆        ┆          ┆            │
│ 2020-04-17    ┆ 0.811267 ┆ 0.811267 ┆ 0.811267 ┆ … ┆ 0.0    ┆ 0.0    ┆ 11717.0  ┆ 2020-04-17 │
│ 15:00:00      ┆          ┆          ┆          ┆   ┆        ┆        ┆          ┆            │
│ 2020-04-20    ┆ 0.82455  ┆ 0.82455  ┆ 0.82455  ┆ … ┆ 0.0    ┆ 0.0    ┆ 11895.0  ┆ 2020-04-20 │
│ 15:00:00      ┆          ┆          ┆          ┆   ┆        ┆        ┆          ┆            │
└───────────────┴──────────┴──────────┴──────────┴───┴────────┴────────┴──────────┴────────────┘

shape: (3_868, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2019-08-13 ┆ 1.010225 ┆ 1.010736 ┆ 1.009714 ┆ … ┆ 8          ┆ 2         ┆ nengyuanh ┆ INE       │
│ 09:26:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-08-13 ┆ 1.006646 ┆ 1.006646 ┆ 1.006135 ┆ … ┆ 8          ┆ 2         ┆ nengyuanh ┆ INE       │
│ 10:32:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-08-13 ┆ 1.007157 ┆ 1.007669 ┆ 1.006646 ┆ … ┆ 8          ┆ 2         ┆ nengyuanh ┆ INE       │
│ 10:36:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-08-13 ┆ 1.007157 ┆ 1.007157 ┆ 1.006646 ┆ … ┆ 8          ┆ 2         ┆ nengyuanh ┆ INE       │
│ 11:10:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-08-13 ┆ 1.007157 ┆ 1.007157 ┆ 1.007157 ┆ … ┆ 8          ┆ 2         ┆ nengyuanh ┆ INE       │
│ 11:26:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-04-20 ┆ 0.801919 ┆ 0.802411 ┆ 0.801919 ┆ … ┆ 4          ┆ 1         ┆ nengyuanh ┆ INE       │
│ 09:45:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-04-20 ┆ 0.820614 ┆ 0.820614 ┆ 0.820122 ┆ … ┆ 4          ┆ 1         ┆ nengyuanh ┆ INE       │
│ 13:55:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-04-20 ┆ 0.824058 ┆ 0.824058 ┆ 0.823074 ┆ … ┆ 4          ┆ 1         ┆ nengyuanh ┆ INE       │
│ 14:13:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-04-20 ┆ 0.823074 ┆ 0.823074 ┆ 0.823074 ┆ … ┆ 4          ┆ 1         ┆ nengyuanh ┆ INE       │
│ 14:41:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-04-20 ┆ 0.820614 ┆ 0.82209  ┆ 0.820614 ┆ … ┆ 4          ┆ 1         ┆ nengyuanh ┆ INE       │
│ 14:46:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

I has 0/605867 rows containing None.
I has data out of the trading hours:

shape: (3_079, 9)
┌────────────────┬──────────┬──────────┬──────────┬───┬────────┬───────────┬──────────┬────────────┐
│ Time           ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount    ┆ Open     ┆ TradingDay │
│ ---            ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---       ┆ Interest ┆ ---        │
│ datetime[μs]   ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64       ┆ ---      ┆ date       │
│                ┆          ┆          ┆          ┆   ┆        ┆           ┆ f64      ┆            │
╞════════════════╪══════════╪══════════╪══════════╪═══╪════════╪═══════════╪══════════╪════════════╡
│ 2013-10-21     ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 450.0  ┆ 4.392e7   ┆ 65384.0  ┆ 2013-10-21 │
│ 08:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2013-10-21     ┆ 0.992828 ┆ 0.992828 ┆ 0.992828 ┆ … ┆ 20.0   ┆ 1.938e6   ┆ 68130.0  ┆ 2013-10-21 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2013-10-22     ┆ 0.98668  ┆ 0.98668  ┆ 0.98668  ┆ … ┆ 216.0  ┆ 2.08008e7 ┆ 68224.0  ┆ 2013-10-22 │
│ 08:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2013-10-22     ┆ 0.971311 ┆ 0.971311 ┆ 0.971311 ┆ … ┆ 30.0   ┆ 2.844e6   ┆ 76004.0  ┆ 2013-10-22 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2013-10-23     ┆ 0.972336 ┆ 0.972336 ┆ 0.972336 ┆ … ┆ 182.0  ┆ 1.72718e7 ┆ 75992.0  ┆ 2013-10-23 │
│ 08:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ …              ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …         ┆ …        ┆ …          │
│ 2020-03-25     ┆ 1.916623 ┆ 1.916623 ┆ 1.916623 ┆ … ┆ 110.0  ┆ 7.3137e6  ┆ 468545.0 ┆ 2020-03-25 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-03-26     ┆ 1.889242 ┆ 1.889242 ┆ 1.889242 ┆ … ┆ 3.0    ┆ 196650.0  ┆ 449098.0 ┆ 2020-03-26 │
│ 10:15:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-03-26     ┆ 1.907976 ┆ 1.907976 ┆ 1.907976 ┆ … ┆ 10.0   ┆ 660200.0  ┆ 445985.0 ┆ 2020-03-26 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-03-27     ┆ 1.913741 ┆ 1.913741 ┆ 1.913741 ┆ … ┆ 12.0   ┆ 796800.0  ┆ 448700.0 ┆ 2020-03-27 │
│ 11:30:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-03-27     ┆ 1.89933  ┆ 1.89933  ┆ 1.89933  ┆ … ┆ 54.0   ┆ 3.5599e6  ┆ 422344.0 ┆ 2020-03-27 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
└────────────────┴──────────┴──────────┴──────────┴───┴────────┴───────────┴──────────┴────────────┘

shape: (344, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2014-03-10 ┆ 0.758922 ┆ 0.758922 ┆ 0.758922 ┆ … ┆ 3          ┆ 1         ┆ heise     ┆ DCE       │
│ 14:03:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2014-12-27 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ … ┆ 12         ┆ 1         ┆ heise     ┆ DCE       │
│ 00:15:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2014-12-27 ┆ 0.547531 ┆ 0.547531 ┆ 0.546384 ┆ … ┆ 12         ┆ 1         ┆ heise     ┆ DCE       │
│ 00:53:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2014-12-27 ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ … ┆ 12         ┆ 1         ┆ heise     ┆ DCE       │
│ 01:20:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2014-12-27 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ … ┆ 12         ┆ 1         ┆ heise     ┆ DCE       │
│ 01:45:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2019-10-10 ┆ 1.797953 ┆ 1.797953 ┆ 1.795214 ┆ … ┆ 10         ┆ 7         ┆ heise     ┆ DCE       │
│ 21:04:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-02-03 ┆ 1.748018 ┆ 1.748018 ┆ 1.748018 ┆ … ┆ 2          ┆ 1         ┆ heise     ┆ DCE       │
│ 13:58:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-02-03 ┆ 1.748018 ┆ 1.748018 ┆ 1.748018 ┆ … ┆ 2          ┆ 1         ┆ heise     ┆ DCE       │
│ 14:24:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-02-03 ┆ 1.748018 ┆ 1.748018 ┆ 1.748018 ┆ … ┆ 2          ┆ 1         ┆ heise     ┆ DCE       │
│ 14:32:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-02-03 ┆ 1.748018 ┆ 1.748018 ┆ 1.748018 ┆ … ┆ 2          ┆ 1         ┆ heise     ┆ DCE       │
│ 14:37:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

RM has 0/591761 rows containing None.
RM has bad data:

shape: (7, 9)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume     ┆ Amount    ┆ Open      ┆ TradingDa │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ ---       ┆ Interest  ┆ y         │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64        ┆ f64       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆           ┆ f64       ┆ date      │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2018-01-11 ┆ 1.209794 ┆ 1.209794 ┆ 1.209794 ┆ … ┆ -454002.0  ┆ -1.0315e1 ┆ 653716.0  ┆ 2018-01-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆            ┆ 0         ┆           ┆ 2         │
│ 2018-08-13 ┆ 1.317036 ┆ 1.317036 ┆ 1.317036 ┆ … ┆ -819498.0  ┆ -2.0422e1 ┆ 509814.0  ┆ 2018-08-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆            ┆ 0         ┆           ┆ 4         │
│ 2018-09-25 ┆ 1.26947  ┆ 1.26947  ┆ 1.26947  ┆ … ┆ -574060.0  ┆ -1.3789e1 ┆ 612940.0  ┆ 2018-09-2 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆            ┆ 0         ┆           ┆ 5         │
│ 2018-10-16 ┆ 1.368301 ┆ 1.368301 ┆ 1.368301 ┆ … ┆ -1.360984e ┆ -3.5236e1 ┆ 726090.0  ┆ 2018-10-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆ 6          ┆ 0         ┆           ┆ 7         │
│ 2018-11-05 ┆ 1.257843 ┆ 1.257843 ┆ 1.257843 ┆ … ┆ -1.114312e ┆ -2.6521e1 ┆ 460522.0  ┆ 2018-11-0 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆ 6          ┆ 0         ┆           ┆ 6         │
│ 2019-01-02 ┆ 1.101692 ┆ 1.101692 ┆ 1.101692 ┆ … ┆ -565226.0  ┆ -1.1830e1 ┆ 509548.0  ┆ 2019-01-0 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆            ┆ 0         ┆           ┆ 2         │
│ 2019-05-14 ┆ 1.176559 ┆ 1.176559 ┆ 1.176559 ┆ … ┆ -1.19838e6 ┆ -2.7179e1 ┆ 519950.0  ┆ 2019-05-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆            ┆ 0         ┆           ┆ 5         │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

RM has data out of the trading hours:

shape: (1_561, 9)
┌─────────────┬──────────┬──────────┬──────────┬───┬────────┬────────────┬────────────┬────────────┐
│ Time        ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μs ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64        ┆ ---        ┆ date       │
│ ]           ┆          ┆          ┆          ┆   ┆        ┆            ┆ f64        ┆            │
╞═════════════╪══════════╪══════════╪══════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 2013-09-30  ┆ 1.0      ┆ 1.0      ┆ 0.999597 ┆ … ┆ 5884.0 ┆ 1.459232e8 ┆ 932368.0   ┆ 2013-09-30 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-10-09  ┆ 1.01975  ┆ 1.01975  ┆ 1.01975  ┆ … ┆ 4288.0 ┆ 1.084864e8 ┆ 863926.0   ┆ 2013-10-09 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-10-09  ┆ 1.02499  ┆ 1.02499  ┆ 1.02499  ┆ … ┆ 352.0  ┆ 8.95136e6  ┆ 968274.0   ┆ 2013-10-09 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-10-10  ┆ 1.024184 ┆ 1.024184 ┆ 1.024184 ┆ … ┆ 1442.0 ┆ 3.664122e7 ┆ 968282.0   ┆ 2013-10-10 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-10-10  ┆ 1.008867 ┆ 1.008867 ┆ 1.008867 ┆ … ┆ 596.0  ┆ 1.491788e7 ┆ 957836.0   ┆ 2013-10-10 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ …           ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 2021-01-26  ┆ 1.492032 ┆ 1.492032 ┆ 1.492032 ┆ … ┆ 2341.0 ┆ 6.608643e6 ┆ 360837.0   ┆ 2021-01-27 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-27  ┆ 1.518458 ┆ 1.518458 ┆ 1.518458 ┆ … ┆ 1583.0 ┆ 4.547959e6 ┆ 363769.0   ┆ 2021-01-28 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-28  ┆ 1.511059 ┆ 1.511059 ┆ 1.511059 ┆ … ┆ 1484.0 ┆ 4.242756e6 ┆ 361261.0   ┆ 2021-01-29 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-29  ┆ 1.511059 ┆ 1.511059 ┆ 1.511059 ┆ … ┆ 1407.0 ┆ 4.022613e6 ┆ 369050.0   ┆ 2021-01-30 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-02-01  ┆ 1.512116 ┆ 1.512116 ┆ 1.512116 ┆ … ┆ 829.0  ┆ 2.371769e6 ┆ 369493.0   ┆ 2021-02-02 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
└─────────────┴──────────┴──────────┴──────────┴───┴────────┴────────────┴────────────┴────────────┘

shape: (4, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2014-10-16 ┆ 1.008302 ┆ 1.008767 ┆ 1.007837 ┆ … ┆ 10         ┆ 4         ┆ nongfucha ┆ CZCE      │
│ 10:04:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2015-07-15 ┆ 1.135929 ┆ 1.136424 ┆ 1.13494  ┆ … ┆ 7          ┆ 4         ┆ nongfucha ┆ CZCE      │
│ 21:35:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2016-01-12 ┆ 0.984185 ┆ 0.984701 ┆ 0.983669 ┆ … ┆ 1          ┆ 3         ┆ nongfucha ┆ CZCE      │
│ 22:59:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-05-23 ┆ 1.270975 ┆ 1.271493 ┆ 1.269937 ┆ … ┆ 5          ┆ 4         ┆ nongfucha ┆ CZCE      │
│ 10:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

CF has 0/595241 rows containing None.
CF has bad data:

shape: (10, 9)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume     ┆ Amount    ┆ Open      ┆ TradingDa │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ ---       ┆ Interest  ┆ y         │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64        ┆ f64       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆           ┆ f64       ┆ date      │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2018-01-11 ┆ 0.880839 ┆ 0.880839 ┆ 0.880839 ┆ … ┆ -91486.0   ┆ -6.9964e9 ┆ 317094.0  ┆ 2018-01-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆ 2         │
│ 2018-06-19 ┆ 0.932181 ┆ 0.932181 ┆ 0.932181 ┆ … ┆ -865772.0  ┆ -7.5777e1 ┆ 741332.0  ┆ 2018-06-1 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆            ┆ 0         ┆           ┆ 9         │
│ 2018-08-13 ┆ 0.905022 ┆ 0.905022 ┆ 0.905022 ┆ … ┆ -477192.0  ┆ -4.0549e1 ┆ 565592.0  ┆ 2018-08-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆            ┆ 0         ┆           ┆ 4         │
│ 2018-09-25 ┆ 0.856563 ┆ 0.856563 ┆ 0.856563 ┆ … ┆ -141778.0  ┆ -1.1402e1 ┆ 436198.0  ┆ 2018-09-2 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆            ┆ 0         ┆           ┆ 5         │
│ 2018-10-16 ┆ 0.822748 ┆ 0.822748 ┆ 0.822748 ┆ … ┆ -161618.0  ┆ -1.2485e1 ┆ 401748.0  ┆ 2018-10-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆            ┆ 0         ┆           ┆ 7         │
│ 2019-01-02 ┆ 0.762028 ┆ 0.762028 ┆ 0.762028 ┆ … ┆ -105924.0  ┆ -7.8569e9 ┆ 358668.0  ┆ 2019-01-0 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆ 2         │
│ 2019-01-07 ┆ 0.775127 ┆ 0.775127 ┆ 0.775127 ┆ … ┆ -144376.0  ┆ -1.0893e1 ┆ 366006.0  ┆ 2019-01-0 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆            ┆ 0         ┆           ┆ 8         │
│ 2019-05-14 ┆ 0.688794 ┆ 0.688794 ┆ 0.688794 ┆ … ┆ -1.011782e ┆ -7.0015e1 ┆ 537500.0  ┆ 2019-05-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆ 6          ┆ 0         ┆           ┆ 5         │
│ 2020-11-30 ┆ 0.615204 ┆ 0.615416 ┆ 0.615204 ┆ … ┆ 67.0       ┆ -52380.0  ┆ 278642.0  ┆ 2020-11-3 │
│ 14:08:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆ 0         │
│ 2020-12-08 ┆ 0.615204 ┆ 0.615204 ┆ 0.614992 ┆ … ┆ 47.0       ┆ -236965.0 ┆ 206503.0  ┆ 2020-12-0 │
│ 14:20:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆ 8         │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

CF has data out of the trading hours:

shape: (1_573, 9)
┌────────────┬──────────┬──────────┬──────────┬───┬─────────┬────────────┬────────────┬────────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume  ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---     ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64     ┆ f64        ┆ ---        ┆ date       │
│ s]         ┆          ┆          ┆          ┆   ┆         ┆            ┆ f64        ┆            │
╞════════════╪══════════╪══════════╪══════════╪═══╪═════════╪════════════╪════════════╪════════════╡
│ 2013-10-14 ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 120.0   ┆ 1.1355e7   ┆ 45506.0    ┆ 2013-10-14 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆         ┆            ┆            ┆            │
│ 2013-10-14 ┆ 1.001057 ┆ 1.001057 ┆ 1.001057 ┆ … ┆ 0.0     ┆ 0.0        ┆ 46306.0    ┆ 2013-10-14 │
│ 15:00:00   ┆          ┆          ┆          ┆   ┆         ┆            ┆            ┆            │
│ 2013-10-15 ┆ 1.002114 ┆ 1.002114 ┆ 1.002114 ┆ … ┆ 90.0    ┆ 8.53425e6  ┆ 46318.0    ┆ 2013-10-15 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆         ┆            ┆            ┆            │
│ 2013-10-16 ┆ 1.002642 ┆ 1.002642 ┆ 1.002642 ┆ … ┆ 18.0    ┆ 1.70775e6  ┆ 47838.0    ┆ 2013-10-16 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆         ┆            ┆            ┆            │
│ 2013-10-17 ┆ 1.0      ┆ 1.000528 ┆ 1.0      ┆ … ┆ 78.0    ┆ 7.38465e6  ┆ 48160.0    ┆ 2013-10-17 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆         ┆            ┆            ┆            │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …       ┆ …          ┆ …          ┆ …          │
│ 2021-01-26 ┆ 0.62889  ┆ 0.62889  ┆ 0.62889  ┆ … ┆ 1637.0  ┆ 2.442404e7 ┆ 511721.0   ┆ 2021-01-27 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆         ┆            ┆            ┆            │
│ 2021-01-27 ┆ 0.634791 ┆ 0.634791 ┆ 0.634791 ┆ … ┆ 1446.0  ┆ 2.177676e7 ┆ 496104.0   ┆ 2021-01-28 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆         ┆            ┆            ┆            │
│ 2021-01-28 ┆ 0.626361 ┆ 0.626361 ┆ 0.626361 ┆ … ┆ 3255.0  ┆ 4.83693e7  ┆ 497442.0   ┆ 2021-01-29 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆         ┆            ┆            ┆            │
│ 2021-01-29 ┆ 0.625939 ┆ 0.625939 ┆ 0.625939 ┆ … ┆ 3512.0  ┆ 5.21532e7  ┆ 497398.0   ┆ 2021-01-30 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆         ┆            ┆            ┆            │
│ 2021-02-01 ┆ 0.634791 ┆ 0.634791 ┆ 0.634791 ┆ … ┆ 11343.0 ┆ 1.7082558e ┆ 483291.0   ┆ 2021-02-02 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆         ┆ 8          ┆            ┆            │
└────────────┴──────────┴──────────┴──────────┴───┴─────────┴────────────┴────────────┴────────────┘

shape: (339, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2013-10-14 ┆ 0.998943 ┆ 0.998943 ┆ 0.998943 ┆ … ┆ 10         ┆ 1         ┆ nongfucha ┆ CZCE      │
│ 10:42:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2013-10-15 ┆ 1.001849 ┆ 1.002114 ┆ 1.001849 ┆ … ┆ 10         ┆ 2         ┆ nongfucha ┆ CZCE      │
│ 11:10:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2013-10-16 ┆ 1.002114 ┆ 1.002114 ┆ 1.002114 ┆ … ┆ 10         ┆ 3         ┆ nongfucha ┆ CZCE      │
│ 13:55:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2013-10-16 ┆ 1.002114 ┆ 1.002114 ┆ 1.001849 ┆ … ┆ 10         ┆ 3         ┆ nongfucha ┆ CZCE      │
│ 14:38:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2013-10-17 ┆ 0.998679 ┆ 0.998679 ┆ 0.998415 ┆ … ┆ 10         ┆ 4         ┆ nongfucha ┆ CZCE      │
│ 09:29:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-03-23 ┆ 0.487589 ┆ 0.487589 ┆ 0.487589 ┆ … ┆ 3          ┆ 1         ┆ nongfucha ┆ CZCE      │
│ 14:06:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-03-23 ┆ 0.487589 ┆ 0.487589 ┆ 0.487589 ┆ … ┆ 3          ┆ 1         ┆ nongfucha ┆ CZCE      │
│ 14:27:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-03-23 ┆ 0.487589 ┆ 0.487589 ┆ 0.487589 ┆ … ┆ 3          ┆ 1         ┆ nongfucha ┆ CZCE      │
│ 14:29:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-03-23 ┆ 0.487589 ┆ 0.487589 ┆ 0.487589 ┆ … ┆ 3          ┆ 1         ┆ nongfucha ┆ CZCE      │
│ 14:35:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-03-23 ┆ 0.487589 ┆ 0.487589 ┆ 0.487589 ┆ … ┆ 3          ┆ 1         ┆ nongfucha ┆ CZCE      │
│ 14:38:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

SN has 0/614972 rows containing None.
SN has bad data:

shape: (9, 9)
┌────────────┬──────────┬──────────┬──────────┬───┬──────────┬───────────┬────────────┬────────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume   ┆ Amount    ┆ Open       ┆ TradingDay │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---       ┆ Interest   ┆ ---        │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64       ┆ ---        ┆ date       │
│ s]         ┆          ┆          ┆          ┆   ┆          ┆           ┆ f64        ┆            │
╞════════════╪══════════╪══════════╪══════════╪═══╪══════════╪═══════════╪════════════╪════════════╡
│ 2017-07-03 ┆ 1.131383 ┆ 1.131383 ┆ 1.131383 ┆ … ┆ -10616.0 ┆ -1.5445e9 ┆ 22158.0    ┆ 2017-07-04 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆          ┆           ┆            ┆            │
│ 2017-07-12 ┆ 1.129832 ┆ 1.129832 ┆ 1.129832 ┆ … ┆ -15384.0 ┆ -2.2320e9 ┆ 20890.0    ┆ 2017-07-13 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆          ┆           ┆            ┆            │
│ 2017-07-21 ┆ 1.13115  ┆ 1.13115  ┆ 1.13115  ┆ … ┆ -16574.0 ┆ -2.4155e9 ┆ 22406.0    ┆ 2017-07-22 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆          ┆           ┆            ┆            │
│ 2017-07-25 ┆ 1.14379  ┆ 1.14379  ┆ 1.14379  ┆ … ┆ -13616.0 ┆ -1.9985e9 ┆ 23524.0    ┆ 2017-07-26 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆          ┆           ┆            ┆            │
│ 2017-07-27 ┆ 1.165502 ┆ 1.165502 ┆ 1.165502 ┆ … ┆ -44916.0 ┆ -6.6904e9 ┆ 27866.0    ┆ 2017-07-28 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆          ┆           ┆            ┆            │
│ 2017-08-08 ┆ 1.1365   ┆ 1.1365   ┆ 1.1365   ┆ … ┆ -15850.0 ┆ -2.3390e9 ┆ 20866.0    ┆ 2017-08-09 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆          ┆           ┆            ┆            │
│ 2017-08-11 ┆ 1.130142 ┆ 1.130142 ┆ 1.130142 ┆ … ┆ -17476.0 ┆ -2.5561e9 ┆ 20220.0    ┆ 2017-08-12 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆          ┆           ┆            ┆            │
│ 2017-09-04 ┆ 1.120338 ┆ 1.120338 ┆ 1.120338 ┆ … ┆ -20606.0 ┆ -3.0487e9 ┆ 16112.0    ┆ 2017-09-05 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆          ┆           ┆            ┆            │
│ 2017-09-07 ┆ 1.100542 ┆ 1.100542 ┆ 1.100542 ┆ … ┆ -13778.0 ┆ -2.0013e9 ┆ 18656.0    ┆ 2017-09-08 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆          ┆           ┆            ┆            │
└────────────┴──────────┴──────────┴──────────┴───┴──────────┴───────────┴────────────┴────────────┘

SN has data out of the trading hours:

shape: (2_277, 9)
┌─────────────────┬──────────┬──────────┬──────────┬───┬────────┬──────────┬──────────┬────────────┐
│ Time            ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount   ┆ Open     ┆ TradingDay │
│ ---             ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---      ┆ Interest ┆ ---        │
│ datetime[μs]    ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64      ┆ ---      ┆ date       │
│                 ┆          ┆          ┆          ┆   ┆        ┆          ┆ f64      ┆            │
╞═════════════════╪══════════╪══════════╪══════════╪═══╪════════╪══════════╪══════════╪════════════╡
│ 2015-03-27      ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 2.0    ┆ 238540.0 ┆ 610.0    ┆ 2015-03-28 │
│ 20:59:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2015-03-30      ┆ 0.990023 ┆ 0.990023 ┆ 0.990023 ┆ … ┆ 0.0    ┆ 0.0      ┆ 830.0    ┆ 2015-03-30 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2015-03-30      ┆ 0.990023 ┆ 0.990023 ┆ 0.990023 ┆ … ┆ 0.0    ┆ 0.0      ┆ 830.0    ┆ 2015-03-31 │
│ 20:59:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2015-03-31      ┆ 0.990693 ┆ 0.990693 ┆ 0.990693 ┆ … ┆ 0.0    ┆ 0.0      ┆ 1176.0   ┆ 2015-03-31 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2015-03-31      ┆ 0.98952  ┆ 0.98952  ┆ 0.98952  ┆ … ┆ 4.0    ┆ 472080.0 ┆ 1180.0   ┆ 2015-04-01 │
│ 20:59:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ …               ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …        ┆ …        ┆ …          │
│ 2020-03-23      ┆ 0.776292 ┆ 0.776292 ┆ 0.776292 ┆ … ┆ 0.0    ┆ 0.0      ┆ 42254.0  ┆ 2020-03-23 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-03-24      ┆ 0.824232 ┆ 0.824232 ┆ 0.824232 ┆ … ┆ 10.0   ┆ 1.1399e6 ┆ 41676.0  ┆ 2020-03-24 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-03-25      ┆ 0.825751 ┆ 0.825751 ┆ 0.825751 ┆ … ┆ 2.0    ┆ 228290.0 ┆ 41174.0  ┆ 2020-03-25 │
│ 10:15:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-03-25      ┆ 0.844261 ┆ 0.844261 ┆ 0.844261 ┆ … ┆ 1.0    ┆ 116760.0 ┆ 41375.0  ┆ 2020-03-25 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-03-26      ┆ 0.839344 ┆ 0.839344 ┆ 0.839344 ┆ … ┆ 1.0    ┆ 116080.0 ┆ 42356.0  ┆ 2020-03-26 │
│ 10:15:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
└─────────────────┴──────────┴──────────┴──────────┴───┴────────┴──────────┴──────────┴────────────┘

shape: (8_358, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2015-03-27 ┆ 0.995976 ┆ 0.995976 ┆ 0.995976 ┆ … ┆ 3          ┆ 1         ┆ yousejins ┆ SHFE      │
│ 22:08:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2015-03-27 ┆ 0.997652 ┆ 0.997652 ┆ 0.997652 ┆ … ┆ 3          ┆ 1         ┆ yousejins ┆ SHFE      │
│ 23:10:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2015-03-27 ┆ 0.997652 ┆ 0.997652 ┆ 0.997652 ┆ … ┆ 3          ┆ 1         ┆ yousejins ┆ SHFE      │
│ 23:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2015-03-27 ┆ 0.998239 ┆ 0.998239 ┆ 0.998239 ┆ … ┆ 3          ┆ 1         ┆ yousejins ┆ SHFE      │
│ 23:43:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2015-03-27 ┆ 0.997485 ┆ 0.997485 ┆ 0.997485 ┆ … ┆ 3          ┆ 1         ┆ yousejins ┆ SHFE      │
│ 23:45:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-03-19 ┆ 0.782294 ┆ 0.782294 ┆ 0.782294 ┆ … ┆ 3          ┆ 4         ┆ yousejins ┆ SHFE      │
│ 13:43:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2020-03-19 ┆ 0.782294 ┆ 0.782294 ┆ 0.782294 ┆ … ┆ 3          ┆ 4         ┆ yousejins ┆ SHFE      │
│ 13:46:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2020-03-19 ┆ 0.782294 ┆ 0.782294 ┆ 0.782294 ┆ … ┆ 3          ┆ 4         ┆ yousejins ┆ SHFE      │
│ 14:09:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2020-03-19 ┆ 0.782294 ┆ 0.782294 ┆ 0.782294 ┆ … ┆ 3          ┆ 4         ┆ yousejins ┆ SHFE      │
│ 14:43:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2020-03-19 ┆ 0.782294 ┆ 0.782294 ┆ 0.782294 ┆ … ┆ 3          ┆ 4         ┆ yousejins ┆ SHFE      │
│ 14:52:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

TA has 0/596747 rows containing None.
TA has bad data:

shape: (15, 9)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume     ┆ Amount    ┆ Open      ┆ TradingDa │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ ---       ┆ Interest  ┆ y         │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64        ┆ f64       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆           ┆ f64       ┆ date      │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2018-01-11 ┆ 0.746012 ┆ 0.746012 ┆ 0.746012 ┆ … ┆ -538304.0  ┆ -1.5282e1 ┆ 1.350282e ┆ 2018-01-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆            ┆ 0         ┆ 6         ┆ 2         │
│ 2018-08-13 ┆ 0.966406 ┆ 0.966406 ┆ 0.966406 ┆ … ┆ -2.478524e ┆ -8.6401e1 ┆ 1.112508e ┆ 2018-08-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆ 6          ┆ 0         ┆ 6         ┆ 4         │
│ 2018-09-25 ┆ 1.003277 ┆ 1.003277 ┆ 1.003277 ┆ … ┆ -1.26952e6 ┆ -4.5944e1 ┆ 1.074304e ┆ 2018-09-2 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆            ┆ 0         ┆ 6         ┆ 5         │
│ 2018-10-16 ┆ 1.009098 ┆ 1.009098 ┆ 1.009098 ┆ … ┆ -1.063298e ┆ -3.8704e1 ┆ 931460.0  ┆ 2018-10-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆ 6          ┆ 0         ┆           ┆ 7         │
│ 2018-11-05 ┆ 0.942564 ┆ 0.942564 ┆ 0.942564 ┆ … ┆ -638134.0  ┆ -2.1697e1 ┆ 968860.0  ┆ 2018-11-0 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆            ┆ 0         ┆           ┆ 6         │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-07-10 ┆ 0.505258 ┆ 0.505543 ┆ 0.504973 ┆ … ┆ 453.0      ┆ -290550.0 ┆ 1.330587e ┆ 2020-07-1 │
│ 13:55:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ 6         ┆ 0         │
│ 2020-08-21 ┆ 0.507956 ┆ 0.508229 ┆ 0.507956 ┆ … ┆ 172.0      ┆ -103474.0 ┆ 1.247821e ┆ 2020-08-2 │
│ 09:57:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ 6         ┆ 1         │
│ 2020-09-17 ┆ 0.495148 ┆ 0.495421 ┆ 0.495148 ┆ … ┆ 112.0      ┆ -326736.0 ┆ 1.436042e ┆ 2020-09-1 │
│ 10:55:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ 6         ┆ 7         │
│ 2020-09-21 ┆ 0.490788 ┆ 0.491061 ┆ 0.490788 ┆ … ┆ 202.0      ┆ -280938.0 ┆ 1.516408e ┆ 2020-09-2 │
│ 11:04:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ 6         ┆ 1         │
│ 2020-11-10 ┆ 0.449639 ┆ 0.449639 ┆ 0.449367 ┆ … ┆ 675.0      ┆ -469452.0 ┆ 2.102884e ┆ 2020-11-1 │
│ 09:55:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ 6         ┆ 0         │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

TA has data out of the trading hours:

shape: (1_579, 9)
┌────────────┬──────────┬──────────┬──────────┬───┬─────────┬────────────┬────────────┬────────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume  ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---     ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64     ┆ f64        ┆ ---        ┆ date       │
│ s]         ┆          ┆          ┆          ┆   ┆         ┆            ┆ f64        ┆            │
╞════════════╪══════════╪══════════╪══════════╪═══╪═════════╪════════════╪════════════╪════════════╡
│ 2013-09-30 ┆ 1.0      ┆ 1.000519 ┆ 1.0      ┆ … ┆ 1908.0  ┆ 7.362972e7 ┆ 458452.0   ┆ 2013-09-30 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆         ┆            ┆            ┆            │
│ 2013-10-08 ┆ 1.007778 ┆ 1.007778 ┆ 1.007778 ┆ … ┆ 2.0     ┆ 77740.0    ┆ 475132.0   ┆ 2013-10-08 │
│ 15:00:00   ┆          ┆          ┆          ┆   ┆         ┆            ┆            ┆            │
│ 2013-10-09 ┆ 1.008297 ┆ 1.008297 ┆ 1.008297 ┆ … ┆ 640.0   ┆ 2.48896e7  ┆ 475642.0   ┆ 2013-10-09 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆         ┆            ┆            ┆            │
│ 2013-10-09 ┆ 1.00726  ┆ 1.00726  ┆ 1.00726  ┆ … ┆ 2.0     ┆ 77700.0    ┆ 503884.0   ┆ 2013-10-09 │
│ 15:00:00   ┆          ┆          ┆          ┆   ┆         ┆            ┆            ┆            │
│ 2013-10-10 ┆ 1.00337  ┆ 1.00337  ┆ 1.00337  ┆ … ┆ 1514.0  ┆ 5.85918e7  ┆ 503204.0   ┆ 2013-10-10 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆         ┆            ┆            ┆            │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …       ┆ …          ┆ …          ┆ …          │
│ 2021-01-26 ┆ 0.515399 ┆ 0.515399 ┆ 0.515399 ┆ … ┆ 7609.0  ┆ 2.9796844e ┆ 2.160347e6 ┆ 2021-01-27 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆         ┆ 7          ┆            ┆            │
│ 2021-01-27 ┆ 0.515925 ┆ 0.515925 ┆ 0.515925 ┆ … ┆ 11732.0 ┆ 4.598944e7 ┆ 2.163147e6 ┆ 2021-01-28 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆         ┆            ┆            ┆            │
│ 2021-01-28 ┆ 0.517241 ┆ 0.517241 ┆ 0.517241 ┆ … ┆ 7985.0  ┆ 3.138105e7 ┆ 2.125896e6 ┆ 2021-01-29 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆         ┆            ┆            ┆            │
│ 2021-01-29 ┆ 0.533825 ┆ 0.533825 ┆ 0.533825 ┆ … ┆ 9806.0  ┆ 3.9773136e ┆ 2.165515e6 ┆ 2021-01-30 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆         ┆ 7          ┆            ┆            │
│ 2021-02-01 ┆ 0.543564 ┆ 0.543564 ┆ 0.543564 ┆ … ┆ 6748.0  ┆ 2.786924e7 ┆ 2.285016e6 ┆ 2021-02-02 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆         ┆            ┆            ┆            │
└────────────┴──────────┴──────────┴──────────┴───┴─────────┴────────────┴────────────┴────────────┘

shape: (43, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2014-10-16 ┆ 0.777057 ┆ 0.777057 ┆ 0.775651 ┆ … ┆ 10         ┆ 4         ┆ nengyuanh ┆ CZCE      │
│ 10:04:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2015-07-15 ┆ 0.643076 ┆ 0.643076 ┆ 0.642503 ┆ … ┆ 7          ┆ 4         ┆ nengyuanh ┆ CZCE      │
│ 21:35:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2016-01-12 ┆ 0.60425  ┆ 0.604532 ┆ 0.603968 ┆ … ┆ 1          ┆ 3         ┆ nengyuanh ┆ CZCE      │
│ 22:59:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2018-07-19 ┆ 0.784285 ┆ 0.784285 ┆ 0.783495 ┆ … ┆ 7          ┆ 7         ┆ nengyuanh ┆ CZCE      │
│ 21:03:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-05-23 ┆ 0.806733 ┆ 0.80703  ┆ 0.806436 ┆ … ┆ 5          ┆ 4         ┆ nengyuanh ┆ CZCE      │
│ 10:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-03-19 ┆ 0.511828 ┆ 0.511828 ┆ 0.511828 ┆ … ┆ 3          ┆ 4         ┆ nengyuanh ┆ CZCE      │
│ 10:48:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-19 ┆ 0.511828 ┆ 0.511828 ┆ 0.511828 ┆ … ┆ 3          ┆ 4         ┆ nengyuanh ┆ CZCE      │
│ 10:58:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-19 ┆ 0.511828 ┆ 0.511828 ┆ 0.511828 ┆ … ┆ 3          ┆ 4         ┆ nengyuanh ┆ CZCE      │
│ 11:03:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-19 ┆ 0.511828 ┆ 0.511828 ┆ 0.511828 ┆ … ┆ 3          ┆ 4         ┆ nengyuanh ┆ CZCE      │
│ 11:06:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-19 ┆ 0.511828 ┆ 0.511828 ┆ 0.511828 ┆ … ┆ 3          ┆ 4         ┆ nengyuanh ┆ CZCE      │
│ 11:11:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

M has 0/610004 rows containing None.
M has data out of the trading hours:

shape: (3_168, 9)
┌────────────┬──────────┬──────────┬──────────┬───┬─────────┬────────────┬────────────┬────────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume  ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---     ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64     ┆ f64        ┆ ---        ┆ date       │
│ s]         ┆          ┆          ┆          ┆   ┆         ┆            ┆ f64        ┆            │
╞════════════╪══════════╪══════════╪══════════╪═══╪═════════╪════════════╪════════════╪════════════╡
│ 2013-09-17 ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 7614.0  ┆ 2.7494154e ┆ 1.94709e6  ┆ 2013-09-17 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆         ┆ 8          ┆            ┆            │
│ 2013-09-17 ┆ 1.006092 ┆ 1.006092 ┆ 1.006092 ┆ … ┆ 48.0    ┆ 1.74384e6  ┆ 1.966138e6 ┆ 2013-09-17 │
│ 15:00:00   ┆          ┆          ┆          ┆   ┆         ┆            ┆            ┆            │
│ 2013-09-18 ┆ 0.998338 ┆ 0.998338 ┆ 0.998338 ┆ … ┆ 6104.0  ┆ 2.200492e8 ┆ 1.966644e6 ┆ 2013-09-18 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆         ┆            ┆            ┆            │
│ 2013-09-18 ┆ 1.004985 ┆ 1.004985 ┆ 1.004985 ┆ … ┆ 54.0    ┆ 1.96006e6  ┆ 1.965692e6 ┆ 2013-09-18 │
│ 15:00:00   ┆          ┆          ┆          ┆   ┆         ┆            ┆            ┆            │
│ 2013-09-23 ┆ 0.985876 ┆ 0.985876 ┆ 0.985876 ┆ … ┆ 10620.0 ┆ 3.78072e8  ┆ 1.967832e6 ┆ 2013-09-23 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆         ┆            ┆            ┆            │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …       ┆ …          ┆ …          ┆ …          │
│ 2020-05-15 ┆ 1.19394  ┆ 1.19394  ┆ 1.19394  ┆ … ┆ 1.0     ┆ 27070.0    ┆ 1.777031e6 ┆ 2020-05-15 │
│ 11:30:00   ┆          ┆          ┆          ┆   ┆         ┆            ┆            ┆            │
│ 2020-05-15 ┆ 1.191735 ┆ 1.191735 ┆ 1.191735 ┆ … ┆ 5.0     ┆ 135100.0   ┆ 1.768817e6 ┆ 2020-05-15 │
│ 15:00:00   ┆          ┆          ┆          ┆   ┆         ┆            ┆            ┆            │
│ 2020-05-18 ┆ 1.204085 ┆ 1.204526 ┆ 1.204085 ┆ … ┆ 45.0    ┆ 1.22856e6  ┆ 1.729418e6 ┆ 2020-05-18 │
│ 10:15:00   ┆          ┆          ┆          ┆   ┆         ┆            ┆            ┆            │
│ 2020-05-18 ┆ 1.210259 ┆ 1.210259 ┆ 1.210259 ┆ … ┆ 3.0     ┆ 82320.0    ┆ 1.713579e6 ┆ 2020-05-18 │
│ 11:30:00   ┆          ┆          ┆          ┆   ┆         ┆            ┆            ┆            │
│ 2020-05-18 ┆ 1.212024 ┆ 1.212024 ┆ 1.212024 ┆ … ┆ 9.0     ┆ 247330.0   ┆ 1.690754e6 ┆ 2020-05-18 │
│ 15:00:00   ┆          ┆          ┆          ┆   ┆         ┆            ┆            ┆            │
└────────────┴──────────┴──────────┴──────────┴───┴─────────┴────────────┴────────────┴────────────┘

shape: (7, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2016-01-12 ┆ 0.885434 ┆ 0.885805 ┆ 0.885063 ┆ … ┆ 1          ┆ 3         ┆ nongfucha ┆ DCE       │
│ 22:59:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2018-08-20 ┆ 1.292237 ┆ 1.293456 ┆ 1.292237 ┆ … ┆ 8          ┆ 2         ┆ nongfucha ┆ DCE       │
│ 21:15:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2018-08-24 ┆ 1.273538 ┆ 1.274758 ┆ 1.273538 ┆ … ┆ 8          ┆ 1         ┆ nongfucha ┆ DCE       │
│ 21:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-04-23 ┆ 1.109628 ┆ 1.110053 ┆ 1.109628 ┆ … ┆ 4          ┆ 2         ┆ nongfucha ┆ DCE       │
│ 10:11:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-05-23 ┆ 1.186945 ┆ 1.18737  ┆ 1.18652  ┆ … ┆ 5          ┆ 4         ┆ nongfucha ┆ DCE       │
│ 10:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-06-28 ┆ 1.222205 ┆ 1.222205 ┆ 1.22178  ┆ … ┆ 6          ┆ 7         ┆ nongfucha ┆ DCE       │
│ 11:02:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-10-10 ┆ 1.26353  ┆ 1.26353  ┆ 1.262677 ┆ … ┆ 10         ┆ 7         ┆ nongfucha ┆ DCE       │
│ 21:04:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

J has 0/643019 rows containing None.
J has data out of the trading hours:

shape: (3_058, 9)
┌─────────────┬──────────┬──────────┬──────────┬───┬────────┬────────────┬────────────┬────────────┐
│ Time        ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μs ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64        ┆ ---        ┆ date       │
│ ]           ┆          ┆          ┆          ┆   ┆        ┆            ┆ f64        ┆            │
╞═════════════╪══════════╪══════════╪══════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 2013-09-17  ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 872.0  ┆ 1.36468e8  ┆ 302036.0   ┆ 2013-09-17 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-17  ┆ 1.004473 ┆ 1.004473 ┆ 1.004473 ┆ … ┆ 32.0   ┆ 5.0314e6   ┆ 268450.0   ┆ 2013-09-17 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-18  ┆ 1.003195 ┆ 1.003195 ┆ 1.003195 ┆ … ┆ 1416.0 ┆ 2.22312e8  ┆ 268818.0   ┆ 2013-09-18 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-18  ┆ 1.01278  ┆ 1.01278  ┆ 1.01278  ┆ … ┆ 2.0    ┆ 317000.0   ┆ 293470.0   ┆ 2013-09-18 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-23  ┆ 1.011502 ┆ 1.011502 ┆ 1.011502 ┆ … ┆ 1454.0 ┆ 2.301682e8 ┆ 294004.0   ┆ 2013-09-23 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ …           ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 2020-03-23  ┆ 1.780694 ┆ 1.780694 ┆ 1.780694 ┆ … ┆ 3.0    ┆ 529500.0   ┆ 86907.0    ┆ 2020-03-23 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-03-24  ┆ 1.811465 ┆ 1.811465 ┆ 1.811465 ┆ … ┆ 0.0    ┆ 0.0        ┆ 76430.0    ┆ 2020-03-24 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-03-25  ┆ 1.817014 ┆ 1.817014 ┆ 1.817014 ┆ … ┆ 3.0    ┆ 540350.0   ┆ 71964.0    ┆ 2020-03-25 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-03-26  ┆ 1.808943 ┆ 1.808943 ┆ 1.808943 ┆ … ┆ 0.0    ┆ 0.0        ┆ 69460.0    ┆ 2020-03-26 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-03-27  ┆ 1.816005 ┆ 1.816005 ┆ 1.816005 ┆ … ┆ 7.0    ┆ 1.26e6     ┆ 69475.0    ┆ 2020-03-27 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
└─────────────┴──────────┴──────────┴──────────┴───┴────────┴────────────┴────────────┴────────────┘

shape: (1_731, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2014-07-10 ┆ 0.629873 ┆ 0.629873 ┆ 0.629873 ┆ … ┆ 7          ┆ 4         ┆ heise     ┆ DCE       │
│ 01:45:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2014-07-10 ┆ 0.630443 ┆ 0.630443 ┆ 0.630443 ┆ … ┆ 7          ┆ 4         ┆ heise     ┆ DCE       │
│ 02:04:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2014-07-11 ┆ 0.631583 ┆ 0.631583 ┆ 0.631013 ┆ … ┆ 7          ┆ 7         ┆ heise     ┆ DCE       │
│ 01:26:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2014-07-11 ┆ 0.631583 ┆ 0.631583 ┆ 0.631013 ┆ … ┆ 7          ┆ 7         ┆ heise     ┆ DCE       │
│ 01:32:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2014-07-11 ┆ 0.631583 ┆ 0.631583 ┆ 0.631013 ┆ … ┆ 7          ┆ 7         ┆ heise     ┆ DCE       │
│ 02:10:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2018-08-20 ┆ 2.122245 ┆ 2.122245 ┆ 2.120245 ┆ … ┆ 8          ┆ 2         ┆ heise     ┆ DCE       │
│ 21:15:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2018-08-24 ┆ 2.030234 ┆ 2.031435 ┆ 2.029834 ┆ … ┆ 8          ┆ 1         ┆ heise     ┆ DCE       │
│ 21:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2019-05-23 ┆ 2.133879 ┆ 2.138154 ┆ 2.133404 ┆ … ┆ 5          ┆ 4         ┆ heise     ┆ DCE       │
│ 10:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2019-06-28 ┆ 1.962903 ┆ 1.964328 ┆ 1.961953 ┆ … ┆ 6          ┆ 7         ┆ heise     ┆ DCE       │
│ 11:02:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2019-10-10 ┆ 1.804056 ┆ 1.806    ┆ 1.804056 ┆ … ┆ 10         ┆ 7         ┆ heise     ┆ DCE       │
│ 21:04:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

AP has 0/169196 rows containing None.
AP has bad data:

shape: (7, 9)
┌────────────┬──────────┬──────────┬──────────┬───┬───────────┬────────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume    ┆ Amount     ┆ Open      ┆ TradingDa │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---        ┆ Interest  ┆ y         │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64       ┆ f64        ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆           ┆            ┆ f64       ┆ date      │
╞════════════╪══════════╪══════════╪══════════╪═══╪═══════════╪════════════╪═══════════╪═══════════╡
│ 2018-01-12 ┆ 0.963415 ┆ 0.963415 ┆ 0.963415 ┆ … ┆ -42994.0  ┆ -3.3626e9  ┆ 20408.0   ┆ 2018-01-1 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 2         │
│ 2018-06-19 ┆ 1.264403 ┆ 1.264403 ┆ 1.264403 ┆ … ┆ -891744.0 ┆ -8.9228e10 ┆ 374108.0  ┆ 2018-06-1 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 9         │
│ 2018-08-14 ┆ 1.328681 ┆ 1.328681 ┆ 1.328681 ┆ … ┆ -271560.0 ┆ -3.0686e10 ┆ 219006.0  ┆ 2018-08-1 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 4         │
│ 2018-09-25 ┆ 1.446381 ┆ 1.446381 ┆ 1.446381 ┆ … ┆ -302798.0 ┆ -3.7247e10 ┆ 273168.0  ┆ 2018-09-2 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 5         │
│ 2019-01-02 ┆ 1.25916  ┆ 1.25916  ┆ 1.25916  ┆ … ┆ -234480.0 ┆ -2.6520e10 ┆ 212794.0  ┆ 2019-01-0 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 2         │
│ 2019-01-08 ┆ 1.182787 ┆ 1.182787 ┆ 1.182787 ┆ … ┆ -308190.0 ┆ -3.2742e10 ┆ 229814.0  ┆ 2019-01-0 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 8         │
│ 2019-05-15 ┆ 1.507532 ┆ 1.507532 ┆ 1.507532 ┆ … ┆ -275844.0 ┆ -2.4183e10 ┆ 132942.0  ┆ 2019-05-1 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 5         │
└────────────┴──────────┴──────────┴──────────┴───┴───────────┴────────────┴───────────┴───────────┘

AP has data out of the trading hours:

shape: (520, 9)
┌─────────────┬──────────┬──────────┬──────────┬───┬────────┬────────────┬────────────┬────────────┐
│ Time        ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μs ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64        ┆ ---        ┆ date       │
│ ]           ┆          ┆          ┆          ┆   ┆        ┆            ┆ f64        ┆            │
╞═════════════╪══════════╪══════════╪══════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 2017-12-25  ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 262.0  ┆ 2.126916e7 ┆ 21736.0    ┆ 2017-12-25 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2017-12-26  ┆ 0.998399 ┆ 0.998399 ┆ 0.998399 ┆ … ┆ 104.0  ┆ 8.4292e6   ┆ 25360.0    ┆ 2017-12-26 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2017-12-27  ┆ 0.997044 ┆ 0.997044 ┆ 0.997044 ┆ … ┆ 46.0   ┆ 3.72324e6  ┆ 21050.0    ┆ 2017-12-27 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2017-12-28  ┆ 0.996797 ┆ 0.996797 ┆ 0.996797 ┆ … ┆ 36.0   ┆ 2.91312e6  ┆ 17546.0    ┆ 2017-12-28 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2017-12-29  ┆ 0.998522 ┆ 0.998522 ┆ 0.998522 ┆ … ┆ 10.0   ┆ 810600.0   ┆ 15564.0    ┆ 2017-12-29 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ …           ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 2021-01-26  ┆ 0.767233 ┆ 0.767233 ┆ 0.767233 ┆ … ┆ 1782.0 ┆ 1.0692e7   ┆ 339983.0   ┆ 2021-01-26 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-27  ┆ 0.777463 ┆ 0.777463 ┆ 0.777463 ┆ … ┆ 522.0  ┆ 3.17376e6  ┆ 344894.0   ┆ 2021-01-27 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-28  ┆ 0.773499 ┆ 0.773499 ┆ 0.773499 ┆ … ┆ 685.0  ┆ 4.143565e6 ┆ 343999.0   ┆ 2021-01-28 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-29  ┆ 0.777079 ┆ 0.777079 ┆ 0.777079 ┆ … ┆ 473.0  ┆ 2.874421e6 ┆ 362032.0   ┆ 2021-01-29 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-02-01  ┆ 0.77823  ┆ 0.77823  ┆ 0.77823  ┆ … ┆ 608.0  ┆ 3.700288e6 ┆ 336582.0   ┆ 2021-02-01 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
└─────────────┴──────────┴──────────┴──────────┴───┴────────┴────────────┴────────────┴────────────┘

shape: (8, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2018-01-08 ┆ 0.996428 ┆ 0.996428 ┆ 0.996305 ┆ … ┆ 1          ┆ 1         ┆ nongfucha ┆ CZCE      │
│ 09:48:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2018-01-08 ┆ 0.996181 ┆ 0.996181 ┆ 0.996058 ┆ … ┆ 1          ┆ 1         ┆ nongfucha ┆ CZCE      │
│ 13:54:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-04-04 ┆ 1.294452 ┆ 1.294786 ┆ 1.293673 ┆ … ┆ 4          ┆ 4         ┆ nongfucha ┆ CZCE      │
│ 14:27:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-05-23 ┆ 1.69118  ┆ 1.69118  ┆ 1.689976 ┆ … ┆ 5          ┆ 4         ┆ nongfucha ┆ CZCE      │
│ 10:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-06-28 ┆ 1.601076 ┆ 1.601935 ┆ 1.600904 ┆ … ┆ 6          ┆ 7         ┆ nongfucha ┆ CZCE      │
│ 11:02:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-04-27 ┆ 1.403935 ┆ 1.403935 ┆ 1.403935 ┆ … ┆ 4          ┆ 1         ┆ nongfucha ┆ CZCE      │
│ 10:03:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-04-27 ┆ 1.403935 ┆ 1.403935 ┆ 1.403935 ┆ … ┆ 4          ┆ 1         ┆ nongfucha ┆ CZCE      │
│ 10:39:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-04-27 ┆ 1.403935 ┆ 1.403935 ┆ 1.403935 ┆ … ┆ 4          ┆ 1         ┆ nongfucha ┆ CZCE      │
│ 10:52:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

UR has 0/80750 rows containing None.
UR has bad data:

shape: (7, 9)
┌─────────────────┬──────────┬──────────┬──────────┬───┬────────┬──────────┬──────────┬────────────┐
│ Time            ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount   ┆ Open     ┆ TradingDay │
│ ---             ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---      ┆ Interest ┆ ---        │
│ datetime[μs]    ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64      ┆ ---      ┆ date       │
│                 ┆          ┆          ┆          ┆   ┆        ┆          ┆ f64      ┆            │
╞═════════════════╪══════════╪══════════╪══════════╪═══╪════════╪══════════╪══════════╪════════════╡
│ 2020-07-23      ┆ 1.02397  ┆ 1.024599 ┆ 1.02397  ┆ … ┆ 57.0   ┆ -37322.0 ┆ 50246.0  ┆ 2020-07-23 │
│ 13:47:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-07-24      ┆ 1.032146 ┆ 1.032775 ┆ 1.031517 ┆ … ┆ 42.0   ┆ -1939.0  ┆ 53753.0  ┆ 2020-07-24 │
│ 11:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-09-09      ┆ 1.034635 ┆ 1.035267 ┆ 1.034635 ┆ … ┆ 96.0   ┆ -9926.0  ┆ 57497.0  ┆ 2020-09-09 │
│ 14:48:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-11-13      ┆ 1.135821 ┆ 1.135821 ┆ 1.135189 ┆ … ┆ 26.0   ┆ -41943.0 ┆ 64249.0  ┆ 2020-11-13 │
│ 14:40:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-12-14      ┆ 1.126968 ┆ 1.126968 ┆ 1.126335 ┆ … ┆ 12.0   ┆ -47684.0 ┆ 22472.0  ┆ 2020-12-14 │
│ 14:43:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-12-22      ┆ 1.142427 ┆ 1.143033 ┆ 1.142427 ┆ … ┆ 12.0   ┆ -40006.0 ┆ 66140.0  ┆ 2020-12-22 │
│ 11:01:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-12-29      ┆ 1.09581  ┆ 1.096415 ┆ 1.09581  ┆ … ┆ 28.0   ┆ -14971.0 ┆ 45171.0  ┆ 2020-12-29 │
│ 13:49:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
└─────────────────┴──────────┴──────────┴──────────┴───┴────────┴──────────┴──────────┴────────────┘

UR has data out of the trading hours:

shape: (131, 9)
┌─────────────┬──────────┬──────────┬──────────┬───┬────────┬────────────┬────────────┬────────────┐
│ Time        ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μs ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64        ┆ ---        ┆ date       │
│ ]           ┆          ┆          ┆          ┆   ┆        ┆            ┆ f64        ┆            │
╞═════════════╪══════════╪══════════╪══════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 2019-08-12  ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 2066.0 ┆ 6.98308e7  ┆ 79638.0    ┆ 2019-08-12 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2019-08-13  ┆ 1.008876 ┆ 1.008876 ┆ 1.008876 ┆ … ┆ 1812.0 ┆ 6.17892e7  ┆ 94364.0    ┆ 2019-08-13 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2019-08-14  ┆ 1.047337 ┆ 1.047337 ┆ 1.047337 ┆ … ┆ 3230.0 ┆ 1.14342e8  ┆ 130056.0   ┆ 2019-08-14 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2019-08-15  ┆ 1.028402 ┆ 1.028402 ┆ 1.028402 ┆ … ┆ 864.0  ┆ 3.003264e7 ┆ 91688.0    ┆ 2019-08-15 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2019-08-16  ┆ 1.027811 ┆ 1.027811 ┆ 1.027811 ┆ … ┆ 96.0   ┆ 3.33504e6  ┆ 91520.0    ┆ 2019-08-16 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ …           ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 2021-01-26  ┆ 1.207207 ┆ 1.207207 ┆ 1.207207 ┆ … ┆ 604.0  ┆ 1.204376e6 ┆ 91807.0    ┆ 2021-01-26 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-27  ┆ 1.196915 ┆ 1.196915 ┆ 1.196915 ┆ … ┆ 320.0  ┆ 632640.0   ┆ 90047.0    ┆ 2021-01-27 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-28  ┆ 1.207812 ┆ 1.207812 ┆ 1.207812 ┆ … ┆ 1163.0 ┆ 2.320185e6 ┆ 104863.0   ┆ 2021-01-28 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-29  ┆ 1.219921 ┆ 1.219921 ┆ 1.219921 ┆ … ┆ 781.0  ┆ 1.573715e6 ┆ 102112.0   ┆ 2021-01-29 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-02-01  ┆ 1.245954 ┆ 1.245954 ┆ 1.245954 ┆ … ┆ 704.0  ┆ 1.448832e6 ┆ 131889.0   ┆ 2021-02-01 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
└─────────────┴──────────┴──────────┴──────────┴───┴────────┴────────────┴────────────┴────────────┘

shape: (143, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2019-09-25 ┆ 1.042012 ┆ 1.042604 ┆ 1.042012 ┆ … ┆ 9          ┆ 3         ┆ nengyuanh ┆ CZCE      │
│ 10:06:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-09-26 ┆ 1.037278 ┆ 1.037278 ┆ 1.037278 ┆ … ┆ 9          ┆ 4         ┆ nengyuanh ┆ CZCE      │
│ 10:42:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-09-26 ┆ 1.03787  ┆ 1.03787  ┆ 1.036686 ┆ … ┆ 9          ┆ 4         ┆ nengyuanh ┆ CZCE      │
│ 11:22:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-09-27 ┆ 1.036095 ┆ 1.036095 ┆ 1.035503 ┆ … ┆ 9          ┆ 7         ┆ nengyuanh ┆ CZCE      │
│ 11:19:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-09-30 ┆ 1.042012 ┆ 1.042012 ┆ 1.042012 ┆ … ┆ 9          ┆ 1         ┆ nengyuanh ┆ CZCE      │
│ 10:46:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-04-13 ┆ 0.982048 ┆ 0.982048 ┆ 0.982048 ┆ … ┆ 4          ┆ 1         ┆ nengyuanh ┆ CZCE      │
│ 10:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-04-13 ┆ 0.981465 ┆ 0.981465 ┆ 0.981465 ┆ … ┆ 4          ┆ 1         ┆ nengyuanh ┆ CZCE      │
│ 10:38:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-04-13 ┆ 0.982048 ┆ 0.982048 ┆ 0.982048 ┆ … ┆ 4          ┆ 1         ┆ nengyuanh ┆ CZCE      │
│ 11:02:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-04-13 ┆ 0.983214 ┆ 0.983214 ┆ 0.982631 ┆ … ┆ 4          ┆ 1         ┆ nengyuanh ┆ CZCE      │
│ 13:36:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-12-21 ┆ 1.114952 ┆ 1.114952 ┆ 1.114952 ┆ … ┆ 12         ┆ 1         ┆ nengyuanh ┆ CZCE      │
│ 11:12:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

ZC has 0/456387 rows containing None.
ZC has bad data:

shape: (9, 9)
┌────────────┬──────────┬──────────┬──────────┬───┬───────────┬────────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume    ┆ Amount     ┆ Open      ┆ TradingDa │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---        ┆ Interest  ┆ y         │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64       ┆ f64        ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆           ┆            ┆ f64       ┆ date      │
╞════════════╪══════════╪══════════╪══════════╪═══╪═══════════╪════════════╪═══════════╪═══════════╡
│ 2015-11-09 ┆ 0.932039 ┆ 0.932039 ┆ 0.932039 ┆ … ┆ -812.0    ┆ -2.494464e ┆ 29854.0   ┆ 2015-11-0 │
│ 09:00:00   ┆          ┆          ┆          ┆   ┆           ┆ 7          ┆           ┆ 9         │
│ 2018-01-11 ┆ 2.493464 ┆ 2.493464 ┆ 2.493464 ┆ … ┆ -155760.0 ┆ -9.8908e9  ┆ 250778.0  ┆ 2018-01-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 2         │
│ 2018-08-13 ┆ 2.498496 ┆ 2.498496 ┆ 2.498496 ┆ … ┆ -229006.0 ┆ -1.4519e10 ┆ 122854.0  ┆ 2018-08-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 4         │
│ 2018-09-25 ┆ 2.556141 ┆ 2.556141 ┆ 2.556141 ┆ … ┆ -210068.0 ┆ -1.3318e10 ┆ 279852.0  ┆ 2018-09-2 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 5         │
│ 2018-10-16 ┆ 2.672256 ┆ 2.672256 ┆ 2.672256 ┆ … ┆ -210116.0 ┆ -1.3926e10 ┆ 266846.0  ┆ 2018-10-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 7         │
│ 2018-11-05 ┆ 2.53195  ┆ 2.53195  ┆ 2.53195  ┆ … ┆ -214740.0 ┆ -1.3486e10 ┆ 237610.0  ┆ 2018-11-0 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 6         │
│ 2019-01-02 ┆ 2.470547 ┆ 2.470547 ┆ 2.470547 ┆ … ┆ -178934.0 ┆ -1.0074e10 ┆ 308146.0  ┆ 2019-01-0 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 2         │
│ 2020-12-22 ┆ 3.465022 ┆ 3.465022 ┆ 3.465022 ┆ … ┆ 61.0      ┆ -98150.4   ┆ 200875.0  ┆ 2020-12-2 │
│ 14:14:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 2         │
│ 2020-12-22 ┆ 3.465022 ┆ 3.465022 ┆ 3.465022 ┆ … ┆ 110.0     ┆ -65467.8   ┆ 197012.0  ┆ 2020-12-2 │
│ 14:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 2         │
└────────────┴──────────┴──────────┴──────────┴───┴───────────┴────────────┴───────────┴───────────┘

ZC has data out of the trading hours:

shape: (1_030, 9)
┌────────────────┬──────────┬──────────┬──────────┬───┬────────┬───────────┬──────────┬────────────┐
│ Time           ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount    ┆ Open     ┆ TradingDay │
│ ---            ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---       ┆ Interest ┆ ---        │
│ datetime[μs]   ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64       ┆ ---      ┆ date       │
│                ┆          ┆          ┆          ┆   ┆        ┆           ┆ f64      ┆            │
╞════════════════╪══════════╪══════════╪══════════╪═══╪════════╪═══════════╪══════════╪════════════╡
│ 2015-11-06     ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 22.0   ┆ 725120.0  ┆ 27932.0  ┆ 2015-11-07 │
│ 20:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2015-11-09     ┆ 0.935073 ┆ 0.935073 ┆ 0.935073 ┆ … ┆ 4.0    ┆ 123280.0  ┆ 29524.0  ┆ 2015-11-10 │
│ 20:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2015-11-11     ┆ 0.918689 ┆ 0.918689 ┆ 0.918689 ┆ … ┆ 2.0    ┆ 60560.0   ┆ 29152.0  ┆ 2015-11-12 │
│ 20:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2015-11-12     ┆ 0.906553 ┆ 0.906553 ┆ 0.906553 ┆ … ┆ 32.0   ┆ 956160.0  ┆ 32412.0  ┆ 2015-11-13 │
│ 20:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2015-11-13     ┆ 0.915049 ┆ 0.915049 ┆ 0.915049 ┆ … ┆ 42.0   ┆ 1.26672e6 ┆ 33798.0  ┆ 2015-11-14 │
│ 20:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ …              ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …         ┆ …        ┆ …          │
│ 2021-01-26     ┆ 3.361957 ┆ 3.361957 ┆ 3.361957 ┆ … ┆ 425.0  ┆ 277270.0  ┆ 239036.0 ┆ 2021-01-27 │
│ 20:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2021-01-27     ┆ 3.383601 ┆ 3.383601 ┆ 3.383601 ┆ … ┆ 823.0  ┆ 540381.8  ┆ 241539.0 ┆ 2021-01-28 │
│ 20:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2021-01-28     ┆ 3.34959  ┆ 3.34959  ┆ 3.34959  ┆ … ┆ 493.0  ┆ 320450.0  ┆ 234368.0 ┆ 2021-01-29 │
│ 20:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2021-01-29     ┆ 3.257862 ┆ 3.257862 ┆ 3.257862 ┆ … ┆ 705.0  ┆ 445701.0  ┆ 257892.0 ┆ 2021-01-30 │
│ 20:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2021-02-01     ┆ 3.257862 ┆ 3.257862 ┆ 3.257862 ┆ … ┆ 315.0  ┆ 199143.0  ┆ 250445.0 ┆ 2021-02-02 │
│ 20:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
└────────────────┴──────────┴──────────┴──────────┴───┴────────┴───────────┴──────────┴────────────┘

shape: (172, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2015-11-06 ┆ 1.00182  ┆ 1.002427 ┆ 1.00182  ┆ … ┆ 11         ┆ 1         ┆ nengyuanh ┆ CZCE      │
│ 23:00:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2015-11-09 ┆ 0.934466 ┆ 0.934466 ┆ 0.934466 ┆ … ┆ 11         ┆ 1         ┆ nengyuanh ┆ CZCE      │
│ 09:32:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2015-11-09 ┆ 0.933859 ┆ 0.933859 ┆ 0.933859 ┆ … ┆ 11         ┆ 1         ┆ nengyuanh ┆ CZCE      │
│ 09:43:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2015-11-09 ┆ 0.934466 ┆ 0.934466 ┆ 0.934466 ┆ … ┆ 11         ┆ 1         ┆ nengyuanh ┆ CZCE      │
│ 09:53:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2015-11-09 ┆ 0.933252 ┆ 0.933859 ┆ 0.933252 ┆ … ┆ 11         ┆ 1         ┆ nengyuanh ┆ CZCE      │
│ 10:02:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-01-13 ┆ 2.557401 ┆ 2.557401 ┆ 2.55648  ┆ … ┆ 1          ┆ 2         ┆ nengyuanh ┆ CZCE      │
│ 22:54:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-01-20 ┆ 2.53897  ┆ 2.539891 ┆ 2.53897  ┆ … ┆ 1          ┆ 2         ┆ nengyuanh ┆ CZCE      │
│ 22:31:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-01-20 ┆ 2.540813 ┆ 2.540813 ┆ 2.539891 ┆ … ┆ 1          ┆ 2         ┆ nengyuanh ┆ CZCE      │
│ 22:37:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-01-21 ┆ 2.518695 ┆ 2.518695 ┆ 2.518695 ┆ … ┆ 1          ┆ 3         ┆ nengyuanh ┆ CZCE      │
│ 22:09:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-01-22 ┆ 2.523303 ┆ 2.523303 ┆ 2.522381 ┆ … ┆ 1          ┆ 4         ┆ nengyuanh ┆ CZCE      │
│ 22:18:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

JD has 0/399305 rows containing None.
JD has data out of the trading hours:

shape: (3_074, 9)
┌────────────────┬──────────┬──────────┬──────────┬───┬────────┬───────────┬──────────┬────────────┐
│ Time           ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount    ┆ Open     ┆ TradingDay │
│ ---            ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---       ┆ Interest ┆ ---        │
│ datetime[μs]   ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64       ┆ ---      ┆ date       │
│                ┆          ┆          ┆          ┆   ┆        ┆           ┆ f64      ┆            │
╞════════════════╪══════════╪══════════╪══════════╪═══╪════════╪═══════════╪══════════╪════════════╡
│ 2013-11-11     ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 330.0  ┆ 1.31406e7 ┆ 38994.0  ┆ 2013-11-11 │
│ 08:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2013-11-11     ┆ 0.989704 ┆ 0.989704 ┆ 0.989704 ┆ … ┆ 0.0    ┆ 0.0       ┆ 44132.0  ┆ 2013-11-11 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2013-11-12     ┆ 0.989453 ┆ 0.989453 ┆ 0.989453 ┆ … ┆ 122.0  ┆ 4.8068e6  ┆ 44140.0  ┆ 2013-11-12 │
│ 08:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2013-11-12     ┆ 0.991964 ┆ 0.992215 ┆ 0.991964 ┆ … ┆ 54.0   ┆ 2.13302e6 ┆ 38812.0  ┆ 2013-11-12 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2013-11-13     ┆ 0.990959 ┆ 0.990959 ┆ 0.990959 ┆ … ┆ 54.0   ┆ 2.13084e6 ┆ 38826.0  ┆ 2013-11-13 │
│ 08:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ …              ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …         ┆ …        ┆ …          │
│ 2020-03-09     ┆ 0.651456 ┆ 0.651456 ┆ 0.651456 ┆ … ┆ 57.0   ┆ 1.93572e6 ┆ 237049.0 ┆ 2020-03-09 │
│ 10:15:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-03-09     ┆ 0.648387 ┆ 0.648387 ┆ 0.648387 ┆ … ┆ 132.0  ┆ 4.46218e6 ┆ 235041.0 ┆ 2020-03-09 │
│ 11:30:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-03-09     ┆ 0.654909 ┆ 0.654909 ┆ 0.654909 ┆ … ┆ 59.0   ┆ 2.0142e6  ┆ 218073.0 ┆ 2020-03-09 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-03-10     ┆ 0.64877  ┆ 0.64877  ┆ 0.64877  ┆ … ┆ 144.0  ┆ 4.86746e6 ┆ 217596.0 ┆ 2020-03-10 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-03-11     ┆ 0.629396 ┆ 0.629396 ┆ 0.629396 ┆ … ┆ 215.0  ┆ 7.05663e6 ┆ 244626.0 ┆ 2020-03-11 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
└────────────────┴──────────┴──────────┴──────────┴───┴────────┴───────────┴──────────┴────────────┘

shape: (4, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2015-07-08 ┆ 0.893146 ┆ 0.893146 ┆ 0.893146 ┆ … ┆ 7          ┆ 3         ┆ nongfucha ┆ DCE       │
│ 14:44:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-05-23 ┆ 0.759313 ┆ 0.759489 ┆ 0.759313 ┆ … ┆ 5          ┆ 4         ┆ nongfucha ┆ DCE       │
│ 10:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-06-28 ┆ 0.763886 ┆ 0.763886 ┆ 0.763183 ┆ … ┆ 6          ┆ 7         ┆ nongfucha ┆ DCE       │
│ 11:02:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-02-03 ┆ 0.614433 ┆ 0.614433 ┆ 0.614433 ┆ … ┆ 2          ┆ 1         ┆ nongfucha ┆ DCE       │
│ 14:09:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

CJ has 0/95938 rows containing None.
CJ has bad data:

shape: (3, 9)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume     ┆ Amount    ┆ Open      ┆ TradingDa │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ ---       ┆ Interest  ┆ y         │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64        ┆ f64       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆           ┆ f64       ┆ date      │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2019-05-15 ┆ 1.077664 ┆ 1.077664 ┆ 1.077664 ┆ … ┆ -1.24142e6 ┆ -5.8998e1 ┆ 89416.0   ┆ 2019-05-1 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆            ┆ 0         ┆           ┆ 5         │
│ 2020-06-08 ┆ 1.110695 ┆ 1.11125  ┆ 1.110695 ┆ … ┆ 4.0        ┆ -8755.0   ┆ 15514.0   ┆ 2020-06-0 │
│ 14:27:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆ 8         │
│ 2020-07-15 ┆ 1.082387 ┆ 1.082387 ┆ 1.081832 ┆ … ┆ 7.0        ┆ -27350.0  ┆ 15843.0   ┆ 2020-07-1 │
│ 13:49:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆ 5         │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

CJ has data out of the trading hours:

shape: (198, 9)
┌─────────────┬──────────┬──────────┬──────────┬───┬────────┬────────────┬────────────┬────────────┐
│ Time        ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μs ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64        ┆ ---        ┆ date       │
│ ]           ┆          ┆          ┆          ┆   ┆        ┆            ┆ f64        ┆            │
╞═════════════╪══════════╪══════════╪══════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 2019-05-06  ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 722.0  ┆ 3.18402e7  ┆ 41330.0    ┆ 2019-05-06 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2019-05-07  ┆ 0.987528 ┆ 0.987528 ┆ 0.987528 ┆ … ┆ 784.0  ┆ 3.41432e7  ┆ 57596.0    ┆ 2019-05-07 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2019-05-08  ┆ 0.977324 ┆ 0.977324 ┆ 0.977324 ┆ … ┆ 162.0  ┆ 6.9822e6   ┆ 71046.0    ┆ 2019-05-08 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2019-05-09  ┆ 0.979025 ┆ 0.979025 ┆ 0.979025 ┆ … ┆ 334.0  ┆ 1.442045e7 ┆ 72136.0    ┆ 2019-05-09 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2019-05-10  ┆ 0.981293 ┆ 0.981293 ┆ 0.981293 ┆ … ┆ 472.0  ┆ 2.04258e7  ┆ 70944.0    ┆ 2019-05-10 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ …           ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 2021-01-26  ┆ 1.060131 ┆ 1.060131 ┆ 1.060131 ┆ … ┆ 109.0  ┆ 1.11725e6  ┆ 23886.0    ┆ 2021-01-26 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-27  ┆ 1.063234 ┆ 1.063234 ┆ 1.063234 ┆ … ┆ 391.0  ┆ 4.01948e6  ┆ 23865.0    ┆ 2021-01-27 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-28  ┆ 1.064785 ┆ 1.064785 ┆ 1.064785 ┆ … ┆ 387.0  ┆ 3.984165e6 ┆ 25117.0    ┆ 2021-01-28 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-29  ┆ 1.066337 ┆ 1.066337 ┆ 1.066337 ┆ … ┆ 38.0   ┆ 391780.0   ┆ 24926.0    ┆ 2021-01-29 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-02-01  ┆ 1.061165 ┆ 1.061165 ┆ 1.061165 ┆ … ┆ 162.0  ┆ 1.66212e6  ┆ 23534.0    ┆ 2021-02-01 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
└─────────────┴──────────┴──────────┴──────────┴───┴────────┴────────────┴────────────┴────────────┘

shape: (80, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2019-05-23 ┆ 1.169501 ┆ 1.170068 ┆ 1.168934 ┆ … ┆ 5          ┆ 4         ┆ nongfucha ┆ CZCE      │
│ 10:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-10-23 ┆ 1.188776 ┆ 1.188776 ┆ 1.188776 ┆ … ┆ 10         ┆ 3         ┆ nongfucha ┆ CZCE      │
│ 11:07:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-10-23 ┆ 1.188776 ┆ 1.188776 ┆ 1.188776 ┆ … ┆ 10         ┆ 3         ┆ nongfucha ┆ CZCE      │
│ 13:45:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-10-23 ┆ 1.188776 ┆ 1.188776 ┆ 1.188776 ┆ … ┆ 10         ┆ 3         ┆ nongfucha ┆ CZCE      │
│ 13:59:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-10-23 ┆ 1.188776 ┆ 1.188776 ┆ 1.188776 ┆ … ┆ 10         ┆ 3         ┆ nongfucha ┆ CZCE      │
│ 14:24:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-12-22 ┆ 1.016168 ┆ 1.019797 ┆ 1.016168 ┆ … ┆ 12         ┆ 2         ┆ nongfucha ┆ CZCE      │
│ 13:55:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-12-22 ┆ 1.019279 ┆ 1.020315 ┆ 1.019279 ┆ … ┆ 12         ┆ 2         ┆ nongfucha ┆ CZCE      │
│ 14:28:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-12-22 ┆ 1.01876  ┆ 1.01876  ┆ 1.017723 ┆ … ┆ 12         ┆ 2         ┆ nongfucha ┆ CZCE      │
│ 14:38:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-12-22 ┆ 1.017723 ┆ 1.017723 ┆ 1.016686 ┆ … ┆ 12         ┆ 2         ┆ nongfucha ┆ CZCE      │
│ 14:51:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-12-22 ┆ 1.017723 ┆ 1.017723 ┆ 1.017205 ┆ … ┆ 12         ┆ 2         ┆ nongfucha ┆ CZCE      │
│ 14:56:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

P has 0/648196 rows containing None.
P has data out of the trading hours:

shape: (3_212, 9)
┌─────────────┬──────────┬──────────┬──────────┬───┬────────┬────────────┬────────────┬────────────┐
│ Time        ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μs ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64        ┆ ---        ┆ date       │
│ ]           ┆          ┆          ┆          ┆   ┆        ┆            ┆ f64        ┆            │
╞═════════════╪══════════╪══════════╪══════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 2013-09-17  ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 318.0  ┆ 1.717836e7 ┆ 667454.0   ┆ 2013-09-17 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-17  ┆ 1.001851 ┆ 1.001851 ┆ 1.001851 ┆ … ┆ 2.0    ┆ 108240.0   ┆ 665016.0   ┆ 2013-09-17 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-18  ┆ 0.99963  ┆ 0.99963  ┆ 0.99963  ┆ … ┆ 1588.0 ┆ 8.5752e7   ┆ 665060.0   ┆ 2013-09-18 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-18  ┆ 0.998149 ┆ 0.998149 ┆ 0.998149 ┆ … ┆ 0.0    ┆ 0.0        ┆ 670530.0   ┆ 2013-09-18 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-23  ┆ 0.990004 ┆ 0.990004 ┆ 0.990004 ┆ … ┆ 1344.0 ┆ 7.187712e7 ┆ 670278.0   ┆ 2013-09-23 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ …           ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 2020-05-13  ┆ 0.623368 ┆ 0.623368 ┆ 0.623083 ┆ … ┆ 14.0   ┆ 612240.0   ┆ 461127.0   ┆ 2020-05-13 │
│ 11:30:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-05-13  ┆ 0.626789 ┆ 0.626789 ┆ 0.626789 ┆ … ┆ 50.0   ┆ 2.19906e6  ┆ 452848.0   ┆ 2020-05-13 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-05-14  ┆ 0.621088 ┆ 0.621088 ┆ 0.621088 ┆ … ┆ 206.0  ┆ 8.97748e6  ┆ 452709.0   ┆ 2020-05-14 │
│ 10:15:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-05-14  ┆ 0.621658 ┆ 0.621658 ┆ 0.621658 ┆ … ┆ 11.0   ┆ 479820.0   ┆ 447808.0   ┆ 2020-05-14 │
│ 11:30:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-05-14  ┆ 0.623083 ┆ 0.623083 ┆ 0.623083 ┆ … ┆ 7.0    ┆ 306020.0   ┆ 442959.0   ┆ 2020-05-14 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
└─────────────┴──────────┴──────────┴──────────┴───┴────────┴────────────┴────────────┴────────────┘

shape: (19, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2014-07-17 ┆ 0.981622 ┆ 0.981622 ┆ 0.981279 ┆ … ┆ 7          ┆ 4         ┆ nongfucha ┆ DCE       │
│ 01:02:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2014-08-13 ┆ 0.955537 ┆ 0.955537 ┆ 0.955537 ┆ … ┆ 8          ┆ 3         ┆ nongfucha ┆ DCE       │
│ 01:42:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2014-12-04 ┆ 0.85093  ┆ 0.851268 ┆ 0.850253 ┆ … ┆ 12         ┆ 4         ┆ nongfucha ┆ DCE       │
│ 13:30:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2015-01-20 ┆ 0.825902 ┆ 0.825902 ┆ 0.825902 ┆ … ┆ 1          ┆ 2         ┆ nongfucha ┆ DCE       │
│ 01:50:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2015-01-27 ┆ 0.8188   ┆ 0.8188   ┆ 0.8188   ┆ … ┆ 1          ┆ 2         ┆ nongfucha ┆ DCE       │
│ 02:09:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2015-04-10 ┆ 0.82041  ┆ 0.82041  ┆ 0.82041  ┆ … ┆ 4          ┆ 7         ┆ nongfucha ┆ DCE       │
│ 01:12:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2016-01-12 ┆ 0.733551 ┆ 0.733866 ┆ 0.733551 ┆ … ┆ 1          ┆ 3         ┆ nongfucha ┆ DCE       │
│ 22:59:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-04-23 ┆ 0.669934 ┆ 0.670224 ┆ 0.669644 ┆ … ┆ 4          ┆ 2         ┆ nongfucha ┆ DCE       │
│ 10:11:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-05-23 ┆ 0.635727 ┆ 0.635727 ┆ 0.635437 ┆ … ┆ 5          ┆ 4         ┆ nongfucha ┆ DCE       │
│ 10:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-10-10 ┆ 0.669882 ┆ 0.669882 ┆ 0.669323 ┆ … ┆ 10         ┆ 7         ┆ nongfucha ┆ DCE       │
│ 21:04:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

FU has 0/266819 rows containing None.
FU has data out of the trading hours:

shape: (2_536, 9)
┌────────────────┬──────────┬──────────┬──────────┬───┬────────┬───────────┬──────────┬────────────┐
│ Time           ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount    ┆ Open     ┆ TradingDay │
│ ---            ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---       ┆ Interest ┆ ---        │
│ datetime[μs]   ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64       ┆ ---      ┆ date       │
│                ┆          ┆          ┆          ┆   ┆        ┆           ┆ f64      ┆            │
╞════════════════╪══════════╪══════════╪══════════╪═══╪════════╪═══════════╪══════════╪════════════╡
│ 2013-09-17     ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 0.0    ┆ 0.0       ┆ 16.0     ┆ 2013-09-17 │
│ 08:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2013-09-17     ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 0.0    ┆ 0.0       ┆ 16.0     ┆ 2013-09-17 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2013-09-18     ┆ 1.004911 ┆ 1.004911 ┆ 1.004911 ┆ … ┆ 0.0    ┆ 0.0       ┆ 16.0     ┆ 2013-09-18 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2013-09-23     ┆ 1.004911 ┆ 1.004911 ┆ 1.004911 ┆ … ┆ 0.0    ┆ 0.0       ┆ 16.0     ┆ 2013-09-23 │
│ 08:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2013-09-23     ┆ 0.916511 ┆ 0.916511 ┆ 0.916511 ┆ … ┆ 0.0    ┆ 0.0       ┆ 16.0     ┆ 2013-09-23 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ …              ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …         ┆ …        ┆ …          │
│ 2020-04-07     ┆ 0.303621 ┆ 0.303621 ┆ 0.303621 ┆ … ┆ 73.0   ┆ 1.15229e6 ┆ 210781.0 ┆ 2020-04-07 │
│ 11:30:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-04-07     ┆ 0.303814 ┆ 0.303814 ┆ 0.303814 ┆ … ┆ 15.0   ┆ 236780.0  ┆ 198090.0 ┆ 2020-04-07 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-04-08     ┆ 0.300158 ┆ 0.300158 ┆ 0.300158 ┆ … ┆ 1.0    ┆ 15600.0   ┆ 189174.0 ┆ 2020-04-08 │
│ 10:15:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-04-08     ┆ 0.300158 ┆ 0.300158 ┆ 0.300158 ┆ … ┆ 86.0   ┆ 1.34185e6 ┆ 183229.0 ┆ 2020-04-08 │
│ 11:30:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-04-08     ┆ 0.299581 ┆ 0.299581 ┆ 0.299581 ┆ … ┆ 36.0   ┆ 560510.0  ┆ 171068.0 ┆ 2020-04-08 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
└────────────────┴──────────┴──────────┴──────────┴───┴────────┴───────────┴──────────┴────────────┘

shape: (13_173, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2013-09-17 ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 9          ┆ 2         ┆ nengyuanh ┆ SHFE      │
│ 09:09:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2013-09-17 ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 9          ┆ 2         ┆ nengyuanh ┆ SHFE      │
│ 09:47:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2013-09-18 ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 9          ┆ 3         ┆ nengyuanh ┆ SHFE      │
│ 09:01:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2013-09-18 ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 9          ┆ 3         ┆ nengyuanh ┆ SHFE      │
│ 09:03:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2013-09-18 ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 9          ┆ 3         ┆ nengyuanh ┆ SHFE      │
│ 09:06:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-02-20 ┆ 0.445811 ┆ 0.446004 ┆ 0.445811 ┆ … ┆ 2          ┆ 4         ┆ nengyuanh ┆ SHFE      │
│ 10:47:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-09 ┆ 0.356149 ┆ 0.356149 ┆ 0.356149 ┆ … ┆ 3          ┆ 1         ┆ nengyuanh ┆ SHFE      │
│ 09:59:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-09 ┆ 0.356149 ┆ 0.356149 ┆ 0.356149 ┆ … ┆ 3          ┆ 1         ┆ nengyuanh ┆ SHFE      │
│ 11:02:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-09 ┆ 0.356149 ┆ 0.356149 ┆ 0.356149 ┆ … ┆ 3          ┆ 1         ┆ nengyuanh ┆ SHFE      │
│ 11:19:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-09 ┆ 0.356149 ┆ 0.356149 ┆ 0.356149 ┆ … ┆ 3          ┆ 1         ┆ nengyuanh ┆ SHFE      │
│ 14:01:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

PG has 0/68033 rows containing None.

shape: (0, 22)
┌──────────────┬──────┬──────┬─────┬───┬────────────┬──────────────┬─────────────┬───────────────┐
│ Time         ┆ Open ┆ High ┆ Low ┆ … ┆ DATA_month ┆ DATA_weekday ┆ DATA_sector ┆ DATA_exchange │
│ ---          ┆ ---  ┆ ---  ┆ --- ┆   ┆ ---        ┆ ---          ┆ ---         ┆ ---           │
│ datetime[μs] ┆ f64  ┆ f64  ┆ f64 ┆   ┆ i8         ┆ i8           ┆ str         ┆ str           │
╞══════════════╪══════╪══════╪═════╪═══╪════════════╪══════════════╪═════════════╪═══════════════╡
└──────────────┴──────┴──────┴─────┴───┴────────────┴──────────────┴─────────────┴───────────────┘

CS has 0/381415 rows containing None.
CS has data out of the trading hours:

shape: (2_418, 9)
┌────────────────┬──────────┬──────────┬──────────┬───┬────────┬───────────┬──────────┬────────────┐
│ Time           ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount    ┆ Open     ┆ TradingDay │
│ ---            ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---       ┆ Interest ┆ ---        │
│ datetime[μs]   ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64       ┆ ---      ┆ date       │
│                ┆          ┆          ┆          ┆   ┆        ┆           ┆ f64      ┆            │
╞════════════════╪══════════╪══════════╪══════════╪═══╪════════╪═══════════╪══════════╪════════════╡
│ 2014-12-22     ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 10.0   ┆ 279500.0  ┆ 4936.0   ┆ 2014-12-22 │
│ 08:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2014-12-22     ┆ 0.979606 ┆ 0.979606 ┆ 0.979606 ┆ … ┆ 0.0    ┆ 0.0       ┆ 8132.0   ┆ 2014-12-22 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2014-12-23     ┆ 0.978891 ┆ 0.978891 ┆ 0.978891 ┆ … ┆ 42.0   ┆ 1.14912e6 ┆ 8152.0   ┆ 2014-12-23 │
│ 08:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2014-12-23     ┆ 0.980322 ┆ 0.980322 ┆ 0.980322 ┆ … ┆ 0.0    ┆ 0.0       ┆ 8664.0   ┆ 2014-12-23 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2014-12-24     ┆ 0.982826 ┆ 0.982826 ┆ 0.982826 ┆ … ┆ 10.0   ┆ 274700.0  ┆ 8662.0   ┆ 2014-12-24 │
│ 08:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ …              ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …         ┆ …        ┆ …          │
│ 2020-03-18     ┆ 0.906426 ┆ 0.906426 ┆ 0.906426 ┆ … ┆ 0.0    ┆ 0.0       ┆ 81836.0  ┆ 2020-03-18 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-03-19     ┆ 0.9048   ┆ 0.9048   ┆ 0.9048   ┆ … ┆ 0.0    ┆ 0.0       ┆ 83421.0  ┆ 2020-03-19 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-03-20     ┆ 0.908052 ┆ 0.908052 ┆ 0.908052 ┆ … ┆ 1.0    ┆ 22340.0   ┆ 81304.0  ┆ 2020-03-20 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-03-23     ┆ 0.916994 ┆ 0.916994 ┆ 0.916994 ┆ … ┆ 0.0    ┆ 0.0       ┆ 76218.0  ┆ 2020-03-23 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-03-24     ┆ 0.914962 ┆ 0.914962 ┆ 0.914962 ┆ … ┆ 0.0    ┆ 0.0       ┆ 74678.0  ┆ 2020-03-24 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
└────────────────┴──────────┴──────────┴──────────┴───┴────────┴───────────┴──────────┴────────────┘

shape: (415, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2014-12-26 ┆ 0.974955 ┆ 0.974955 ┆ 0.974597 ┆ … ┆ 12         ┆ 7         ┆ nongfucha ┆ DCE       │
│ 09:59:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2014-12-26 ┆ 0.975313 ┆ 0.975313 ┆ 0.975313 ┆ … ┆ 12         ┆ 7         ┆ nongfucha ┆ DCE       │
│ 10:47:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2014-12-26 ┆ 0.975313 ┆ 0.975313 ┆ 0.975313 ┆ … ┆ 12         ┆ 7         ┆ nongfucha ┆ DCE       │
│ 11:02:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2014-12-26 ┆ 0.974955 ┆ 0.974955 ┆ 0.974955 ┆ … ┆ 12         ┆ 7         ┆ nongfucha ┆ DCE       │
│ 11:14:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2014-12-26 ┆ 0.97424  ┆ 0.974597 ┆ 0.97424  ┆ … ┆ 12         ┆ 7         ┆ nongfucha ┆ DCE       │
│ 11:23:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-02-25 ┆ 0.910897 ┆ 0.911304 ┆ 0.910897 ┆ … ┆ 2          ┆ 2         ┆ nongfucha ┆ DCE       │
│ 09:58:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-03-04 ┆ 0.916181 ┆ 0.916181 ┆ 0.916181 ┆ … ┆ 3          ┆ 3         ┆ nongfucha ┆ DCE       │
│ 11:07:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-03-19 ┆ 0.907239 ┆ 0.907239 ┆ 0.906833 ┆ … ┆ 3          ┆ 4         ┆ nongfucha ┆ DCE       │
│ 13:57:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-03-19 ┆ 0.906833 ┆ 0.907239 ┆ 0.906833 ┆ … ┆ 3          ┆ 4         ┆ nongfucha ┆ DCE       │
│ 13:59:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-03-23 ┆ 0.912523 ┆ 0.91293  ┆ 0.912117 ┆ … ┆ 3          ┆ 1         ┆ nongfucha ┆ DCE       │
│ 14:24:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

MA has 0/534400 rows containing None.
MA has bad data:

shape: (11, 9)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume     ┆ Amount    ┆ Open      ┆ TradingDa │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ ---       ┆ Interest  ┆ y         │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64        ┆ f64       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆           ┆ f64       ┆ date      │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2017-03-20 ┆ 1.129415 ┆ 1.129415 ┆ 1.129415 ┆ … ┆ -869130.0  ┆ -2.2849e1 ┆ 581780.0  ┆ 2017-03-2 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆            ┆ 0         ┆           ┆ 1         │
│ 2017-03-21 ┆ 1.105357 ┆ 1.105357 ┆ 1.105357 ┆ … ┆ -883838.0  ┆ -2.2741e1 ┆ 585574.0  ┆ 2017-03-2 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆            ┆ 0         ┆           ┆ 2         │
│ 2018-01-11 ┆ 1.362075 ┆ 1.362075 ┆ 1.362075 ┆ … ┆ -720382.0  ┆ -2.1446e1 ┆ 718704.0  ┆ 2018-01-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆            ┆ 0         ┆           ┆ 2         │
│ 2018-08-13 ┆ 1.485056 ┆ 1.485056 ┆ 1.485056 ┆ … ┆ -765624.0  ┆ -2.4944e1 ┆ 604178.0  ┆ 2018-08-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆            ┆ 0         ┆           ┆ 4         │
│ 2018-09-25 ┆ 1.526535 ┆ 1.526535 ┆ 1.526535 ┆ … ┆ -995242.0  ┆ -3.3331e1 ┆ 768924.0  ┆ 2018-09-2 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆            ┆ 0         ┆           ┆ 5         │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2019-01-02 ┆ 1.072127 ┆ 1.072127 ┆ 1.072127 ┆ … ┆ -1.892978e ┆ -4.5242e1 ┆ 1.046174e ┆ 2019-01-0 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆ 6          ┆ 0         ┆ 6         ┆ 2         │
│ 2019-05-14 ┆ 1.038994 ┆ 1.038994 ┆ 1.038994 ┆ … ┆ -2.04868e6 ┆ -4.8759e1 ┆ 1.478696e ┆ 2019-05-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆            ┆ 0         ┆ 6         ┆ 5         │
│ 2020-06-04 ┆ 0.652773 ┆ 0.653148 ┆ 0.652773 ┆ … ┆ 644.0      ┆ -408574.0 ┆ 1.488783e ┆ 2020-06-0 │
│ 14:33:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ 6         ┆ 4         │
│ 2020-07-28 ┆ 0.649398 ┆ 0.649398 ┆ 0.649023 ┆ … ┆ 599.0      ┆ -21819.0  ┆ 1.311553e ┆ 2020-07-2 │
│ 14:09:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ 6         ┆ 8         │
│ 2020-09-22 ┆ 0.686136 ┆ 0.686136 ┆ 0.685459 ┆ … ┆ 525.0      ┆ -298710.0 ┆ 984437.0  ┆ 2020-09-2 │
│ 11:26:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆ 2         │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

MA has data out of the trading hours:

shape: (1_244, 9)
┌─────────────┬──────────┬──────────┬──────────┬───┬────────┬────────────┬────────────┬────────────┐
│ Time        ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μs ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64        ┆ ---        ┆ date       │
│ ]           ┆          ┆          ┆          ┆   ┆        ┆            ┆ f64        ┆            │
╞═════════════╪══════════╪══════════╪══════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 2014-12-09  ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 1110.0 ┆ 2.57631e7  ┆ 96940.0    ┆ 2014-12-09 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2014-12-10  ┆ 1.006032 ┆ 1.006032 ┆ 1.006032 ┆ … ┆ 310.0  ┆ 7.2385e6   ┆ 94614.0    ┆ 2014-12-10 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2014-12-11  ┆ 0.990952 ┆ 0.990952 ┆ 0.990952 ┆ … ┆ 764.0  ┆ 1.7572e7   ┆ 96452.0    ┆ 2014-12-11 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2014-12-12  ┆ 0.997846 ┆ 0.997846 ┆ 0.997846 ┆ … ┆ 824.0  ┆ 1.908384e7 ┆ 102602.0   ┆ 2014-12-12 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2014-12-12  ┆ 1.000862 ┆ 1.000862 ┆ 1.000862 ┆ … ┆ 158.0  ┆ 3.67034e6  ┆ 123840.0   ┆ 2014-12-13 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ …           ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 2021-01-26  ┆ 0.73095  ┆ 0.73095  ┆ 0.73095  ┆ … ┆ 3937.0 ┆ 8.814943e6 ┆ 1.051487e6 ┆ 2021-01-27 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-27  ┆ 0.735194 ┆ 0.735194 ┆ 0.735194 ┆ … ┆ 1029.0 ┆ 2.317308e6 ┆ 982627.0   ┆ 2021-01-28 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-28  ┆ 0.737806 ┆ 0.737806 ┆ 0.737806 ┆ … ┆ 8470.0 ┆ 1.91422e7  ┆ 1.037332e6 ┆ 2021-01-29 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-29  ┆ 0.752823 ┆ 0.752823 ┆ 0.752823 ┆ … ┆ 1307.0 ┆ 3.013942e6 ┆ 989048.0   ┆ 2021-01-30 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-02-01  ┆ 0.748906 ┆ 0.748906 ┆ 0.748906 ┆ … ┆ 1150.0 ┆ 2.6381e6   ┆ 880413.0   ┆ 2021-02-02 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
└─────────────┴──────────┴──────────┴──────────┴───┴────────┴────────────┴────────────┴────────────┘

shape: (17, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2015-07-15 ┆ 0.940115 ┆ 0.940945 ┆ 0.939285 ┆ … ┆ 7          ┆ 4         ┆ nengyuanh ┆ CZCE      │
│ 21:35:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2016-01-12 ┆ 0.785531 ┆ 0.785986 ┆ 0.785531 ┆ … ┆ 1          ┆ 3         ┆ nengyuanh ┆ CZCE      │
│ 22:59:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2018-12-28 ┆ 1.067193 ┆ 1.067193 ┆ 1.066744 ┆ … ┆ 12         ┆ 7         ┆ nengyuanh ┆ CZCE      │
│ 14:21:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-05-23 ┆ 1.086142 ┆ 1.087452 ┆ 1.086142 ┆ … ┆ 5          ┆ 4         ┆ nengyuanh ┆ CZCE      │
│ 10:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-02-03 ┆ 0.820493 ┆ 0.820493 ┆ 0.820493 ┆ … ┆ 2          ┆ 1         ┆ nengyuanh ┆ CZCE      │
│ 11:14:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-03-09 ┆ 0.74974  ┆ 0.74974  ┆ 0.74974  ┆ … ┆ 3          ┆ 1         ┆ nengyuanh ┆ CZCE      │
│ 10:48:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-09 ┆ 0.74974  ┆ 0.74974  ┆ 0.74974  ┆ … ┆ 3          ┆ 1         ┆ nengyuanh ┆ CZCE      │
│ 10:57:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-09 ┆ 0.74974  ┆ 0.74974  ┆ 0.74974  ┆ … ┆ 3          ┆ 1         ┆ nengyuanh ┆ CZCE      │
│ 11:17:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-09 ┆ 0.74974  ┆ 0.74974  ┆ 0.74974  ┆ … ┆ 3          ┆ 1         ┆ nengyuanh ┆ CZCE      │
│ 11:20:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-09 ┆ 0.74974  ┆ 0.74974  ┆ 0.74974  ┆ … ┆ 3          ┆ 1         ┆ nengyuanh ┆ CZCE      │
│ 13:53:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

SS has 0/128053 rows containing None.
SS has data out of the trading hours:

shape: (179, 9)
┌─────────────┬──────────┬──────────┬──────────┬───┬────────┬────────────┬────────────┬────────────┐
│ Time        ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μs ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64        ┆ ---        ┆ date       │
│ ]           ┆          ┆          ┆          ┆   ┆        ┆            ┆ f64        ┆            │
╞═════════════╪══════════╪══════════╪══════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 2019-09-26  ┆ 1.008995 ┆ 1.008995 ┆ 1.008995 ┆ … ┆ 0.0    ┆ 0.0        ┆ 19368.0    ┆ 2019-09-26 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2019-09-27  ┆ 1.007388 ┆ 1.007388 ┆ 1.007388 ┆ … ┆ 2.0    ┆ 156800.0   ┆ 16542.0    ┆ 2019-09-27 │
│ 11:30:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2019-09-27  ┆ 1.010279 ┆ 1.010279 ┆ 1.010279 ┆ … ┆ 4.0    ┆ 314450.0   ┆ 15904.0    ┆ 2019-09-27 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2019-09-30  ┆ 1.008673 ┆ 1.008673 ┆ 1.008673 ┆ … ┆ 0.0    ┆ 0.0        ┆ 14590.0    ┆ 2019-09-30 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2019-10-08  ┆ 1.003212 ┆ 1.003212 ┆ 1.003212 ┆ … ┆ 2.0    ┆ 156150.0   ┆ 14574.0    ┆ 2019-10-08 │
│ 10:15:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ …           ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 2020-05-19  ┆ 0.877059 ┆ 0.877059 ┆ 0.877059 ┆ … ┆ 0.0    ┆ 0.0        ┆ 53618.0    ┆ 2020-05-19 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-05-20  ┆ 0.87217  ┆ 0.87217  ┆ 0.87217  ┆ … ┆ 0.0    ┆ 0.0        ┆ 54569.0    ┆ 2020-05-20 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-05-21  ┆ 0.888792 ┆ 0.888792 ┆ 0.888792 ┆ … ┆ 22.0   ┆ 1.499075e6 ┆ 53570.0    ┆ 2020-05-21 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-05-22  ┆ 0.857829 ┆ 0.857829 ┆ 0.857829 ┆ … ┆ 8.0    ┆ 526550.0   ┆ 49489.0    ┆ 2020-05-22 │
│ 11:30:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-05-22  ┆ 0.855222 ┆ 0.855222 ┆ 0.855222 ┆ … ┆ 0.0    ┆ 0.0        ┆ 47115.0    ┆ 2020-05-22 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
└─────────────┴──────────┴──────────┴──────────┴───┴────────┴────────────┴────────────┴────────────┘

shape: (2_831, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2019-09-26 ┆ 1.00771  ┆ 1.008673 ┆ 1.00771  ┆ … ┆ 9          ┆ 7         ┆ heise     ┆ SHFE      │
│ 21:46:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2019-09-27 ┆ 1.006746 ┆ 1.006746 ┆ 1.006425 ┆ … ┆ 9          ┆ 7         ┆ heise     ┆ SHFE      │
│ 00:33:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2019-09-27 ┆ 1.006425 ┆ 1.006746 ┆ 1.006425 ┆ … ┆ 9          ┆ 7         ┆ heise     ┆ SHFE      │
│ 00:36:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2019-09-27 ┆ 1.006425 ┆ 1.006425 ┆ 1.006425 ┆ … ┆ 9          ┆ 7         ┆ heise     ┆ SHFE      │
│ 00:42:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2019-09-27 ┆ 1.006746 ┆ 1.006746 ┆ 1.006746 ┆ … ┆ 9          ┆ 7         ┆ heise     ┆ SHFE      │
│ 00:48:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-05-23 ┆ 0.859459 ┆ 0.859459 ┆ 0.859459 ┆ … ┆ 5          ┆ 1         ┆ heise     ┆ SHFE      │
│ 00:27:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-05-23 ┆ 0.859459 ┆ 0.859459 ┆ 0.859459 ┆ … ┆ 5          ┆ 1         ┆ heise     ┆ SHFE      │
│ 00:36:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-05-23 ┆ 0.859459 ┆ 0.859459 ┆ 0.859459 ┆ … ┆ 5          ┆ 1         ┆ heise     ┆ SHFE      │
│ 00:39:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-05-23 ┆ 0.859785 ┆ 0.859785 ┆ 0.859785 ┆ … ┆ 5          ┆ 1         ┆ heise     ┆ SHFE      │
│ 00:48:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-05-25 ┆ 0.865977 ┆ 0.865977 ┆ 0.865651 ┆ … ┆ 5          ┆ 1         ┆ heise     ┆ SHFE      │
│ 10:45:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

AL has 0/778000 rows containing None.
AL has bad data:

shape: (9, 9)
┌────────────┬──────────┬──────────┬──────────┬───┬───────────┬────────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume    ┆ Amount     ┆ Open      ┆ TradingDa │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---        ┆ Interest  ┆ y         │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64       ┆ f64        ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆           ┆            ┆ f64       ┆ date      │
╞════════════╪══════════╪══════════╪══════════╪═══╪═══════════╪════════════╪═══════════╪═══════════╡
│ 2017-09-04 ┆ 1.1729   ┆ 1.1729   ┆ 1.1729   ┆ … ┆ -569788.0 ┆ -4.7726e10 ┆ 442410.0  ┆ 2017-09-0 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 5         │
│ 2017-09-07 ┆ 1.150563 ┆ 1.150563 ┆ 1.150563 ┆ … ┆ -458992.0 ┆ -3.7471e10 ┆ 412054.0  ┆ 2017-09-0 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 8         │
│ 2017-09-11 ┆ 1.172191 ┆ 1.172191 ┆ 1.172191 ┆ … ┆ -613782.0 ┆ -4.9411e10 ┆ 396798.0  ┆ 2017-09-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 2         │
│ 2017-09-13 ┆ 1.167582 ┆ 1.167582 ┆ 1.167582 ┆ … ┆ -467918.0 ┆ -3.8976e10 ┆ 415868.0  ┆ 2017-09-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 4         │
│ 2017-09-26 ┆ 1.162973 ┆ 1.162973 ┆ 1.162973 ┆ … ┆ -458014.0 ┆ -3.7823e10 ┆ 336238.0  ┆ 2017-09-2 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 7         │
│ 2017-10-09 ┆ 1.164391 ┆ 1.164391 ┆ 1.164391 ┆ … ┆ -386440.0 ┆ -3.1512e10 ┆ 231348.0  ┆ 2017-10-0 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 9         │
│ 2017-10-10 ┆ 1.155172 ┆ 1.155172 ┆ 1.155172 ┆ … ┆ -210360.0 ┆ -1.7425e10 ┆ 198894.0  ┆ 2017-10-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 1         │
│ 2017-10-12 ┆ 1.160437 ┆ 1.160437 ┆ 1.160437 ┆ … ┆ -385244.0 ┆ -3.1525e10 ┆ 448502.0  ┆ 2017-10-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 3         │
│ 2017-10-18 ┆ 1.135057 ┆ 1.135057 ┆ 1.135057 ┆ … ┆ -444500.0 ┆ -3.6049e10 ┆ 458944.0  ┆ 2017-10-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 9         │
└────────────┴──────────┴──────────┴──────────┴───┴───────────┴────────────┴───────────┴───────────┘

AL has data out of the trading hours:

shape: (3_082, 9)
┌─────────────────┬──────────┬──────────┬──────────┬───┬────────┬──────────┬──────────┬────────────┐
│ Time            ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount   ┆ Open     ┆ TradingDay │
│ ---             ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---      ┆ Interest ┆ ---        │
│ datetime[μs]    ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64      ┆ ---      ┆ date       │
│                 ┆          ┆          ┆          ┆   ┆        ┆          ┆ f64      ┆            │
╞═════════════════╪══════════╪══════════╪══════════╪═══╪════════╪══════════╪══════════╪════════════╡
│ 2013-09-17      ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 60.0   ┆ 4.2525e6 ┆ 74948.0  ┆ 2013-09-17 │
│ 08:59:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2013-09-17      ┆ 0.996825 ┆ 0.996825 ┆ 0.996825 ┆ … ┆ 0.0    ┆ 0.0      ┆ 79688.0  ┆ 2013-09-17 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2013-09-18      ┆ 0.996825 ┆ 0.996825 ┆ 0.996825 ┆ … ┆ 0.0    ┆ 0.0      ┆ 79688.0  ┆ 2013-09-18 │
│ 08:59:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2013-09-18      ┆ 0.998236 ┆ 0.998236 ┆ 0.998236 ┆ … ┆ 0.0    ┆ 0.0      ┆ 80222.0  ┆ 2013-09-18 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2013-09-23      ┆ 0.998942 ┆ 0.998942 ┆ 0.998942 ┆ … ┆ 8.0    ┆ 566400.0 ┆ 80214.0  ┆ 2013-09-23 │
│ 08:59:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ …               ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …        ┆ …        ┆ …          │
│ 2020-05-22      ┆ 0.858206 ┆ 0.858206 ┆ 0.858206 ┆ … ┆ 0.0    ┆ 0.0      ┆ 157674.0 ┆ 2020-05-22 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-05-25      ┆ 0.863574 ┆ 0.863574 ┆ 0.863574 ┆ … ┆ 66.0   ┆ 4.2471e6 ┆ 158751.0 ┆ 2020-05-25 │
│ 10:15:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-05-25      ┆ 0.86089  ┆ 0.86089  ┆ 0.86089  ┆ … ┆ 1.0    ┆ 64150.0  ┆ 158182.0 ┆ 2020-05-25 │
│ 11:30:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-05-25      ┆ 0.861561 ┆ 0.861561 ┆ 0.861561 ┆ … ┆ 0.0    ┆ 0.0      ┆ 157683.0 ┆ 2020-05-25 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-05-26      ┆ 0.868942 ┆ 0.868942 ┆ 0.868942 ┆ … ┆ 3.0    ┆ 194250.0 ┆ 159459.0 ┆ 2020-05-26 │
│ 11:30:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
└─────────────────┴──────────┴──────────┴──────────┴───┴────────┴──────────┴──────────┴────────────┘

shape: (4_924, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2013-09-17 ┆ 0.997178 ┆ 0.997178 ┆ 0.997178 ┆ … ┆ 9          ┆ 2         ┆ yousejins ┆ SHFE      │
│ 10:00:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2013-09-17 ┆ 0.997531 ┆ 0.997531 ┆ 0.997531 ┆ … ┆ 9          ┆ 2         ┆ yousejins ┆ SHFE      │
│ 11:16:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2013-09-17 ┆ 0.997178 ┆ 0.997178 ┆ 0.997178 ┆ … ┆ 9          ┆ 2         ┆ yousejins ┆ SHFE      │
│ 11:26:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2013-09-17 ┆ 0.99612  ┆ 0.99612  ┆ 0.99612  ┆ … ┆ 9          ┆ 2         ┆ yousejins ┆ SHFE      │
│ 13:46:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2013-09-17 ┆ 0.996825 ┆ 0.996825 ┆ 0.996825 ┆ … ┆ 9          ┆ 2         ┆ yousejins ┆ SHFE      │
│ 14:17:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-05-25 ┆ 0.861561 ┆ 0.861561 ┆ 0.861226 ┆ … ┆ 5          ┆ 2         ┆ yousejins ┆ SHFE      │
│ 23:59:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2020-05-26 ┆ 0.861226 ┆ 0.861561 ┆ 0.861226 ┆ … ┆ 5          ┆ 2         ┆ yousejins ┆ SHFE      │
│ 00:01:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2020-05-26 ┆ 0.861226 ┆ 0.861226 ┆ 0.861226 ┆ … ┆ 5          ┆ 2         ┆ yousejins ┆ SHFE      │
│ 00:05:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2020-05-26 ┆ 0.861561 ┆ 0.861561 ┆ 0.861561 ┆ … ┆ 5          ┆ 2         ┆ yousejins ┆ SHFE      │
│ 00:20:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2020-05-26 ┆ 0.861226 ┆ 0.861226 ┆ 0.861226 ┆ … ┆ 5          ┆ 2         ┆ yousejins ┆ SHFE      │
│ 00:40:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

SC has 0/346057 rows containing None.
SC has bad data:

shape: (1, 9)
┌─────────────────┬──────────┬──────────┬──────────┬───┬────────┬──────────┬──────────┬────────────┐
│ Time            ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount   ┆ Open     ┆ TradingDay │
│ ---             ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---      ┆ Interest ┆ ---        │
│ datetime[μs]    ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64      ┆ ---      ┆ date       │
│                 ┆          ┆          ┆          ┆   ┆        ┆          ┆ f64      ┆            │
╞═════════════════╪══════════╪══════════╪══════════╪═══╪════════╪══════════╪══════════╪════════════╡
│ 2018-12-19      ┆ 0.903759 ┆ 0.905153 ┆ 0.905153 ┆ … ┆ 2.0    ┆ 779200.0 ┆ 11276.0  ┆ 2018-12-20 │
│ 21:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
└─────────────────┴──────────┴──────────┴──────────┴───┴────────┴──────────┴──────────┴────────────┘

SC has data out of the trading hours:

shape: (1_098, 9)
┌─────────────────┬──────────┬──────────┬──────────┬───┬────────┬──────────┬──────────┬────────────┐
│ Time            ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount   ┆ Open     ┆ TradingDay │
│ ---             ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---      ┆ Interest ┆ ---        │
│ datetime[μs]    ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64      ┆ ---      ┆ date       │
│                 ┆          ┆          ┆          ┆   ┆        ┆          ┆ f64      ┆            │
╞═════════════════╪══════════╪══════════╪══════════╪═══╪════════╪══════════╪══════════╪════════════╡
│ 2018-03-27      ┆ 0.986276 ┆ 0.986276 ┆ 0.986276 ┆ … ┆ 0.0    ┆ 0.0      ┆ 3936.0   ┆ 2018-03-27 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2018-03-28      ┆ 0.954641 ┆ 0.954641 ┆ 0.954641 ┆ … ┆ 0.0    ┆ 0.0      ┆ 6074.0   ┆ 2018-03-28 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2018-03-29      ┆ 0.953012 ┆ 0.953012 ┆ 0.953012 ┆ … ┆ 0.0    ┆ 0.0      ┆ 7732.0   ┆ 2018-03-29 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2018-03-30      ┆ 0.974413 ┆ 0.974413 ┆ 0.974413 ┆ … ┆ 2.0    ┆ 837800.0 ┆ 7720.0   ┆ 2018-03-30 │
│ 11:30:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2018-03-30      ┆ 0.977669 ┆ 0.977669 ┆ 0.977669 ┆ … ┆ 0.0    ┆ 0.0      ┆ 7058.0   ┆ 2018-03-30 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ …               ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …        ┆ …        ┆ …          │
│ 2020-05-14      ┆ 0.55509  ┆ 0.55509  ┆ 0.55509  ┆ … ┆ 2.0    ┆ 459000.0 ┆ 27802.0  ┆ 2020-05-14 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-05-15      ┆ 0.583151 ┆ 0.583151 ┆ 0.583151 ┆ … ┆ 2.0    ┆ 515300.0 ┆ 64005.0  ┆ 2020-05-15 │
│ 02:30:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-05-15      ┆ 0.587224 ┆ 0.587224 ┆ 0.587224 ┆ … ┆ 6.0    ┆ 1.5575e6 ┆ 65371.0  ┆ 2020-05-15 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-05-16      ┆ 0.587224 ┆ 0.587224 ┆ 0.587224 ┆ … ┆ 1.0    ┆ 259500.0 ┆ 67006.0  ┆ 2020-05-16 │
│ 02:30:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-05-18      ┆ 0.603064 ┆ 0.603064 ┆ 0.603064 ┆ … ┆ 7.0    ┆ 1.8655e6 ┆ 67870.0  ┆ 2020-05-18 │
│ 10:15:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
└─────────────────┴──────────┴──────────┴──────────┴───┴────────┴──────────┴──────────┴────────────┘

shape: (843, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2018-03-27 ┆ 0.985811 ┆ 0.986043 ┆ 0.985811 ┆ … ┆ 3          ┆ 2         ┆ nengyuanh ┆ INE       │
│ 00:30:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2018-03-27 ┆ 0.986043 ┆ 0.986043 ┆ 0.985578 ┆ … ┆ 3          ┆ 2         ┆ nengyuanh ┆ INE       │
│ 00:37:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2018-03-27 ┆ 0.986974 ┆ 0.986974 ┆ 0.986974 ┆ … ┆ 3          ┆ 2         ┆ nengyuanh ┆ INE       │
│ 01:09:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2018-03-27 ┆ 0.986974 ┆ 0.986974 ┆ 0.986974 ┆ … ┆ 3          ┆ 2         ┆ nengyuanh ┆ INE       │
│ 01:19:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2018-03-27 ┆ 0.986508 ┆ 0.986508 ┆ 0.986508 ┆ … ┆ 3          ┆ 2         ┆ nengyuanh ┆ INE       │
│ 01:26:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-04-22 ┆ 0.509377 ┆ 0.509377 ┆ 0.509377 ┆ … ┆ 4          ┆ 3         ┆ nengyuanh ┆ INE       │
│ 13:45:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-04-22 ┆ 0.509377 ┆ 0.509377 ┆ 0.509377 ┆ … ┆ 4          ┆ 3         ┆ nengyuanh ┆ INE       │
│ 13:54:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-04-22 ┆ 0.509377 ┆ 0.509377 ┆ 0.509377 ┆ … ┆ 4          ┆ 3         ┆ nengyuanh ┆ INE       │
│ 14:15:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-04-22 ┆ 0.509377 ┆ 0.509377 ┆ 0.509377 ┆ … ┆ 4          ┆ 3         ┆ nengyuanh ┆ INE       │
│ 14:33:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-04-22 ┆ 0.509377 ┆ 0.509377 ┆ 0.509377 ┆ … ┆ 4          ┆ 3         ┆ nengyuanh ┆ INE       │
│ 14:52:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

NI has 0/639074 rows containing None.
NI has bad data:

shape: (16, 9)
┌────────────┬──────────┬──────────┬──────────┬───┬───────────┬────────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume    ┆ Amount     ┆ Open      ┆ TradingDa │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---        ┆ Interest  ┆ y         │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64       ┆ f64        ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆           ┆            ┆ f64       ┆ date      │
╞════════════╪══════════╪══════════╪══════════╪═══╪═══════════╪════════════╪═══════════╪═══════════╡
│ 2017-07-03 ┆ 0.706416 ┆ 0.706416 ┆ 0.706416 ┆ … ┆ -332740.0 ┆ -2.5625e10 ┆ 498934.0  ┆ 2017-07-0 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 4         │
│ 2017-07-12 ┆ 0.692439 ┆ 0.692439 ┆ 0.692439 ┆ … ┆ -421032.0 ┆ -3.1731e10 ┆ 469348.0  ┆ 2017-07-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 3         │
│ 2017-07-21 ┆ 0.721215 ┆ 0.721215 ┆ 0.721215 ┆ … ┆ -404188.0 ┆ -3.1626e10 ┆ 439740.0  ┆ 2017-07-2 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 2         │
│ 2017-07-25 ┆ 0.742682 ┆ 0.742682 ┆ 0.742682 ┆ … ┆ -553630.0 ┆ -4.4321e10 ┆ 459466.0  ┆ 2017-07-2 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 6         │
│ 2017-07-27 ┆ 0.749534 ┆ 0.749534 ┆ 0.749534 ┆ … ┆ -411068.0 ┆ -3.3498e10 ┆ 388812.0  ┆ 2017-07-2 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 8         │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …         ┆ …          ┆ …         ┆ …         │
│ 2017-09-26 ┆ 0.753953 ┆ 0.753953 ┆ 0.753953 ┆ … ┆ -455808.0 ┆ -3.8594e10 ┆ 472986.0  ┆ 2017-09-2 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 7         │
│ 2017-10-09 ┆ 0.766504 ┆ 0.766504 ┆ 0.766504 ┆ … ┆ -423204.0 ┆ -3.5751e10 ┆ 430190.0  ┆ 2017-10-0 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 9         │
│ 2017-10-10 ┆ 0.785778 ┆ 0.785778 ┆ 0.785778 ┆ … ┆ -474606.0 ┆ -4.1641e10 ┆ 468958.0  ┆ 2017-10-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 1         │
│ 2017-10-12 ┆ 0.808908 ┆ 0.808908 ┆ 0.808908 ┆ … ┆ -548256.0 ┆ -4.9002e10 ┆ 479866.0  ┆ 2017-10-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 3         │
│ 2017-10-18 ┆ 0.848174 ┆ 0.848174 ┆ 0.848174 ┆ … ┆ -491536.0 ┆ -4.6155e10 ┆ 467808.0  ┆ 2017-10-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 9         │
└────────────┴──────────┴──────────┴──────────┴───┴───────────┴────────────┴───────────┴───────────┘

NI has data out of the trading hours:

shape: (2_552, 9)
┌────────────────┬──────────┬──────────┬──────────┬───┬────────┬───────────┬──────────┬────────────┐
│ Time           ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount    ┆ Open     ┆ TradingDay │
│ ---            ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---       ┆ Interest ┆ ---        │
│ datetime[μs]   ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64       ┆ ---      ┆ date       │
│                ┆          ┆          ┆          ┆   ┆        ┆           ┆ f64      ┆            │
╞════════════════╪══════════╪══════════╪══════════╪═══╪════════╪═══════════╪══════════╪════════════╡
│ 2015-03-27     ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 96.0   ┆ 9.50496e6 ┆ 14454.0  ┆ 2015-03-28 │
│ 20:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2015-03-30     ┆ 0.994142 ┆ 0.994142 ┆ 0.994142 ┆ … ┆ 2.0    ┆ 196860.0  ┆ 34186.0  ┆ 2015-03-30 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2015-03-30     ┆ 0.989799 ┆ 0.989799 ┆ 0.989799 ┆ … ┆ 128.0  ┆ 1.2544e7  ┆ 34286.0  ┆ 2015-03-31 │
│ 20:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2015-03-31     ┆ 0.959903 ┆ 0.959903 ┆ 0.959903 ┆ … ┆ 2.0    ┆ 190080.0  ┆ 54888.0  ┆ 2015-03-31 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2015-03-31     ┆ 0.948793 ┆ 0.948793 ┆ 0.948793 ┆ … ┆ 160.0  ┆ 1.50304e7 ┆ 54958.0  ┆ 2015-04-01 │
│ 20:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ …              ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …         ┆ …        ┆ …          │
│ 2020-03-31     ┆ 0.867126 ┆ 0.867126 ┆ 0.867126 ┆ … ┆ 24.0   ┆ 2.23155e6 ┆ 86782.0  ┆ 2020-03-31 │
│ 11:30:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-03-31     ┆ 0.856309 ┆ 0.856309 ┆ 0.856309 ┆ … ┆ 13.0   ┆ 1.1939e6  ┆ 92556.0  ┆ 2020-03-31 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-04-01     ┆ 0.863583 ┆ 0.863583 ┆ 0.863583 ┆ … ┆ 59.0   ┆ 5.46442e6 ┆ 87201.0  ┆ 2020-04-01 │
│ 10:15:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-04-01     ┆ 0.865727 ┆ 0.865727 ┆ 0.865727 ┆ … ┆ 3.0    ┆ 278520.0  ┆ 86768.0  ┆ 2020-04-01 │
│ 11:30:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-04-01     ┆ 0.864235 ┆ 0.864235 ┆ 0.864235 ┆ … ┆ 9.0    ┆ 834190.0  ┆ 83435.0  ┆ 2020-04-01 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
└────────────────┴──────────┴──────────┴──────────┴───┴────────┴───────────┴──────────┴────────────┘

shape: (67, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2015-03-27 ┆ 0.998586 ┆ 0.998687 ┆ 0.998081 ┆ … ┆ 3          ┆ 1         ┆ yousejins ┆ SHFE      │
│ 23:54:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2015-04-27 ┆ 1.025048 ┆ 1.025048 ┆ 1.025048 ┆ … ┆ 4          ┆ 1         ┆ yousejins ┆ SHFE      │
│ 11:06:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2015-05-20 ┆ 1.033633 ┆ 1.033633 ┆ 1.033633 ┆ … ┆ 5          ┆ 3         ┆ yousejins ┆ SHFE      │
│ 11:07:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2015-05-20 ┆ 1.033633 ┆ 1.033633 ┆ 1.033633 ┆ … ┆ 5          ┆ 3         ┆ yousejins ┆ SHFE      │
│ 14:37:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2015-07-08 ┆ 0.826293 ┆ 0.826293 ┆ 0.826293 ┆ … ┆ 7          ┆ 3         ┆ yousejins ┆ SHFE      │
│ 00:30:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2019-10-10 ┆ 1.223634 ┆ 1.224704 ┆ 1.223634 ┆ … ┆ 10         ┆ 7         ┆ yousejins ┆ SHFE      │
│ 21:04:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2020-01-06 ┆ 1.005352 ┆ 1.0061   ┆ 1.005352 ┆ … ┆ 1          ┆ 1         ┆ yousejins ┆ SHFE      │
│ 09:16:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2020-01-08 ┆ 1.019568 ┆ 1.020597 ┆ 1.018633 ┆ … ┆ 1          ┆ 3         ┆ yousejins ┆ SHFE      │
│ 09:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2020-01-21 ┆ 1.010309 ┆ 1.010309 ┆ 1.008812 ┆ … ┆ 1          ┆ 2         ┆ yousejins ┆ SHFE      │
│ 10:43:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2020-02-20 ┆ 0.968016 ┆ 0.968016 ┆ 0.967923 ┆ … ┆ 2          ┆ 4         ┆ yousejins ┆ SHFE      │
│ 10:47:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

RB has 0/601967 rows containing None.
RB has bad data:

shape: (11, 9)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume     ┆ Amount    ┆ Open      ┆ TradingDa │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ ---       ┆ Interest  ┆ y         │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64        ┆ f64       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆           ┆ f64       ┆ date      │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2017-08-08 ┆ 1.100852 ┆ 1.100852 ┆ 1.100852 ┆ … ┆ -6.064258e ┆ -2.3758e1 ┆ 2.375234e ┆ 2017-08-0 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆ 6          ┆ 1         ┆ 6         ┆ 9         │
│ 2017-08-11 ┆ 1.092364 ┆ 1.092364 ┆ 1.092364 ┆ … ┆ -9.147584e ┆ -3.5748e1 ┆ 2.903294e ┆ 2017-08-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆ 6          ┆ 1         ┆ 6         ┆ 2         │
│ 2017-09-04 ┆ 1.148665 ┆ 1.148665 ┆ 1.148665 ┆ … ┆ -4.655426e ┆ -1.9079e1 ┆ 3.72062e6 ┆ 2017-09-0 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆ 6          ┆ 1         ┆           ┆ 5         │
│ 2017-09-07 ┆ 1.117827 ┆ 1.117827 ┆ 1.117827 ┆ … ┆ -4.49675e6 ┆ -1.7908e1 ┆ 3.657112e ┆ 2017-09-0 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆            ┆ 1         ┆ 6         ┆ 8         │
│ 2017-09-11 ┆ 1.107642 ┆ 1.107642 ┆ 1.107642 ┆ … ┆ -3.905958e ┆ -1.5238e1 ┆ 3.499996e ┆ 2017-09-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆ 6          ┆ 1         ┆ 6         ┆ 2         │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2017-09-26 ┆ 1.022199 ┆ 1.022199 ┆ 1.022199 ┆ … ┆ -3.093314e ┆ -1.1188e1 ┆ 3.52e6    ┆ 2017-09-2 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆ 6          ┆ 1         ┆           ┆ 7         │
│ 2017-10-09 ┆ 1.064355 ┆ 1.064355 ┆ 1.064355 ┆ … ┆ -3.368988e ┆ -1.2137e1 ┆ 3.100256e ┆ 2017-10-0 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆ 6          ┆ 1         ┆ 6         ┆ 9         │
│ 2017-10-10 ┆ 1.004375 ┆ 1.004375 ┆ 1.004375 ┆ … ┆ -3.728738e ┆ -1.3430e1 ┆ 3.46464e6 ┆ 2017-10-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆ 6          ┆ 1         ┆           ┆ 1         │
│ 2017-10-12 ┆ 1.036911 ┆ 1.036911 ┆ 1.036911 ┆ … ┆ -4.771324e ┆ -1.7077e1 ┆ 3.63737e6 ┆ 2017-10-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆ 6          ┆ 1         ┆           ┆ 3         │
│ 2017-10-18 ┆ 1.044267 ┆ 1.044267 ┆ 1.044267 ┆ … ┆ -2.913504e ┆ -1.0877e1 ┆ 3.20251e6 ┆ 2017-10-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆ 6          ┆ 1         ┆           ┆ 9         │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

RB has data out of the trading hours:

shape: (3_268, 9)
┌─────────────┬──────────┬──────────┬──────────┬───┬────────┬────────────┬────────────┬────────────┐
│ Time        ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μs ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64        ┆ ---        ┆ date       │
│ ]           ┆          ┆          ┆          ┆   ┆        ┆            ┆ f64        ┆            │
╞═════════════╪══════════╪══════════╪══════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 2013-09-17  ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 1772.0 ┆ 6.45894e7  ┆ 1.502096e6 ┆ 2013-09-17 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-17  ┆ 1.000549 ┆ 1.000549 ┆ 1.000549 ┆ … ┆ 22.0   ┆ 802280.0   ┆ 1.520864e6 ┆ 2013-09-17 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-18  ┆ 0.998628 ┆ 0.998628 ┆ 0.998628 ┆ … ┆ 1224.0 ┆ 4.45536e7  ┆ 1.521228e6 ┆ 2013-09-18 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-18  ┆ 0.996708 ┆ 0.996708 ┆ 0.996708 ┆ … ┆ 320.0  ┆ 1.16254e7  ┆ 1.46174e6  ┆ 2013-09-18 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-23  ┆ 0.99561  ┆ 0.99561  ┆ 0.99561  ┆ … ┆ 2518.0 ┆ 9.137822e7 ┆ 1.462846e6 ┆ 2013-09-23 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ …           ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 2020-04-21  ┆ 1.439948 ┆ 1.439948 ┆ 1.439948 ┆ … ┆ 2.0    ┆ 66490.0    ┆ 1.548868e6 ┆ 2020-04-21 │
│ 10:15:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-04-21  ┆ 1.435616 ┆ 1.435616 ┆ 1.435616 ┆ … ┆ 133.0  ┆ 4.40762e6  ┆ 1.552209e6 ┆ 2020-04-21 │
│ 11:30:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-04-21  ┆ 1.445579 ┆ 1.445579 ┆ 1.445579 ┆ … ┆ 66.0   ┆ 2.20235e6  ┆ 1.527245e6 ┆ 2020-04-21 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-04-22  ┆ 1.442547 ┆ 1.442547 ┆ 1.442547 ┆ … ┆ 7.0    ┆ 233150.0   ┆ 1.536703e6 ┆ 2020-04-22 │
│ 10:15:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-04-22  ┆ 1.446879 ┆ 1.446879 ┆ 1.446879 ┆ … ┆ 66.0   ┆ 2.20456e6  ┆ 1.537894e6 ┆ 2020-04-22 │
│ 11:30:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
└─────────────┴──────────┴──────────┴──────────┴───┴────────┴────────────┴────────────┴────────────┘

shape: (26, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2013-11-04 ┆ 0.981318 ┆ 0.981318 ┆ 0.981051 ┆ … ┆ 11         ┆ 1         ┆ heise     ┆ SHFE      │
│ 14:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2014-09-23 ┆ 0.677152 ┆ 0.677152 ┆ 0.676894 ┆ … ┆ 9          ┆ 2         ┆ heise     ┆ SHFE      │
│ 09:43:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2014-12-04 ┆ 0.674819 ┆ 0.674819 ┆ 0.674292 ┆ … ┆ 12         ┆ 4         ┆ heise     ┆ SHFE      │
│ 13:30:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2015-05-18 ┆ 0.599355 ┆ 0.599355 ┆ 0.599355 ┆ … ┆ 5          ┆ 2         ┆ heise     ┆ SHFE      │
│ 21:25:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2015-06-19 ┆ 0.575615 ┆ 0.576126 ┆ 0.575615 ┆ … ┆ 6          ┆ 7         ┆ heise     ┆ SHFE      │
│ 09:01:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2019-06-28 ┆ 1.493824 ┆ 1.493824 ┆ 1.491979 ┆ … ┆ 6          ┆ 7         ┆ heise     ┆ SHFE      │
│ 11:02:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-01-06 ┆ 1.485014 ┆ 1.485851 ┆ 1.484595 ┆ … ┆ 1          ┆ 1         ┆ heise     ┆ SHFE      │
│ 09:16:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-01-08 ┆ 1.515594 ┆ 1.51685  ┆ 1.515175 ┆ … ┆ 1          ┆ 3         ┆ heise     ┆ SHFE      │
│ 09:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-01-21 ┆ 1.491297 ┆ 1.491297 ┆ 1.490459 ┆ … ┆ 1          ┆ 2         ┆ heise     ┆ SHFE      │
│ 10:43:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-02-20 ┆ 1.431394 ┆ 1.431394 ┆ 1.430975 ┆ … ┆ 2          ┆ 4         ┆ heise     ┆ SHFE      │
│ 10:47:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

HC has 0/562918 rows containing None.
HC has data out of the trading hours:

shape: (2_904, 9)
┌────────────────┬──────────┬──────────┬──────────┬───┬────────┬───────────┬──────────┬────────────┐
│ Time           ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount    ┆ Open     ┆ TradingDay │
│ ---            ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---       ┆ Interest ┆ ---        │
│ datetime[μs]   ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64       ┆ ---      ┆ date       │
│                ┆          ┆          ┆          ┆   ┆        ┆           ┆ f64      ┆            │
╞════════════════╪══════════╪══════════╪══════════╪═══╪════════╪═══════════╪══════════╪════════════╡
│ 2014-03-24     ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 60.0   ┆ 1.9884e6  ┆ 52044.0  ┆ 2014-03-24 │
│ 08:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2014-03-24     ┆ 1.004828 ┆ 1.004828 ┆ 1.004828 ┆ … ┆ 110.0  ┆ 3.66296e6 ┆ 47616.0  ┆ 2014-03-24 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2014-03-25     ┆ 1.003621 ┆ 1.003621 ┆ 1.003621 ┆ … ┆ 36.0   ┆ 1.19736e6 ┆ 47652.0  ┆ 2014-03-25 │
│ 08:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2014-03-25     ┆ 1.019312 ┆ 1.019312 ┆ 1.019312 ┆ … ┆ 0.0    ┆ 0.0       ┆ 61256.0  ┆ 2014-03-25 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2014-03-26     ┆ 1.016898 ┆ 1.016898 ┆ 1.016898 ┆ … ┆ 24.0   ┆ 808800.0  ┆ 61254.0  ┆ 2014-03-26 │
│ 08:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ …              ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …         ┆ …        ┆ …          │
│ 2020-04-29     ┆ 1.828451 ┆ 1.828451 ┆ 1.828451 ┆ … ┆ 1.0    ┆ 31630.0   ┆ 437940.0 ┆ 2020-04-29 │
│ 10:15:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-04-29     ┆ 1.826139 ┆ 1.826139 ┆ 1.826139 ┆ … ┆ 0.0    ┆ 0.0       ┆ 432938.0 ┆ 2020-04-29 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-04-30     ┆ 1.849262 ┆ 1.849262 ┆ 1.849262 ┆ … ┆ 10.0   ┆ 319900.0  ┆ 437352.0 ┆ 2020-04-30 │
│ 10:15:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-04-30     ┆ 1.856199 ┆ 1.856199 ┆ 1.856199 ┆ … ┆ 9.0    ┆ 288990.0  ┆ 424718.0 ┆ 2020-04-30 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-05-06     ┆ 1.877587 ┆ 1.877587 ┆ 1.877587 ┆ … ┆ 14.0   ┆ 454710.0  ┆ 429865.0 ┆ 2020-05-06 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
└────────────────┴──────────┴──────────┴──────────┴───┴────────┴───────────┴──────────┴────────────┘

shape: (5_104, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2014-04-11 ┆ 1.038624 ┆ 1.038624 ┆ 1.038624 ┆ … ┆ 4          ┆ 7         ┆ heise     ┆ SHFE      │
│ 14:36:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2014-04-14 ┆ 1.043452 ┆ 1.043452 ┆ 1.043452 ┆ … ┆ 4          ┆ 1         ┆ heise     ┆ SHFE      │
│ 10:03:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2014-04-14 ┆ 1.036814 ┆ 1.036814 ┆ 1.03621  ┆ … ┆ 4          ┆ 1         ┆ heise     ┆ SHFE      │
│ 13:59:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2014-04-16 ┆ 1.031986 ┆ 1.031986 ┆ 1.031986 ┆ … ┆ 4          ┆ 3         ┆ heise     ┆ SHFE      │
│ 11:18:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2014-04-17 ┆ 1.031382 ┆ 1.031382 ┆ 1.031382 ┆ … ┆ 4          ┆ 4         ┆ heise     ┆ SHFE      │
│ 14:40:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2019-10-10 ┆ 1.75753  ┆ 1.758568 ┆ 1.755972 ┆ … ┆ 10         ┆ 7         ┆ heise     ┆ SHFE      │
│ 21:04:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-01-06 ┆ 1.948158 ┆ 1.94925  ┆ 1.948158 ┆ … ┆ 1          ┆ 1         ┆ heise     ┆ SHFE      │
│ 09:16:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-01-08 ┆ 1.991863 ┆ 1.992409 ┆ 1.991317 ┆ … ┆ 1          ┆ 3         ┆ heise     ┆ SHFE      │
│ 09:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-01-21 ┆ 1.956899 ┆ 1.956899 ┆ 1.956352 ┆ … ┆ 1          ┆ 2         ┆ heise     ┆ SHFE      │
│ 10:43:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-02-20 ┆ 1.87222  ┆ 1.87222  ┆ 1.87222  ┆ … ┆ 2          ┆ 4         ┆ heise     ┆ SHFE      │
│ 10:47:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

RU has 0/567749 rows containing None.
RU has data out of the trading hours:

shape: (3_132, 9)
┌─────────────┬──────────┬──────────┬──────────┬───┬────────┬────────────┬────────────┬────────────┐
│ Time        ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μs ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64        ┆ ---        ┆ date       │
│ ]           ┆          ┆          ┆          ┆   ┆        ┆            ┆ f64        ┆            │
╞═════════════╪══════════╪══════════╪══════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 2013-09-17  ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 658.0  ┆ 1.320935e8 ┆ 172010.0   ┆ 2013-09-17 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-17  ┆ 1.015691 ┆ 1.015691 ┆ 1.015691 ┆ … ┆ 98.0   ┆ 1.99836e7  ┆ 171190.0   ┆ 2013-09-17 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-18  ┆ 1.011955 ┆ 1.011955 ┆ 1.011955 ┆ … ┆ 570.0  ┆ 1.157955e8 ┆ 171224.0   ┆ 2013-09-18 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-18  ┆ 1.035866 ┆ 1.035866 ┆ 1.035866 ┆ … ┆ 22.0   ┆ 4.575e6    ┆ 165346.0   ┆ 2013-09-18 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-23  ┆ 1.025654 ┆ 1.025654 ┆ 1.025654 ┆ … ┆ 1644.0 ┆ 3.384996e8 ┆ 164950.0   ┆ 2013-09-23 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ …           ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 2020-03-27  ┆ 0.184885 ┆ 0.184885 ┆ 0.184885 ┆ … ┆ 5.0    ┆ 484950.0   ┆ 149492.0   ┆ 2020-03-27 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-03-30  ┆ 0.180597 ┆ 0.180597 ┆ 0.180597 ┆ … ┆ 1.0    ┆ 94750.0    ┆ 153535.0   ┆ 2020-03-30 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-03-31  ┆ 0.184504 ┆ 0.184504 ┆ 0.184504 ┆ … ┆ 2.0    ┆ 193600.0   ┆ 153710.0   ┆ 2020-03-31 │
│ 10:15:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-03-31  ┆ 0.184981 ┆ 0.184981 ┆ 0.184981 ┆ … ┆ 4.0    ┆ 388250.0   ┆ 152396.0   ┆ 2020-03-31 │
│ 11:30:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-03-31  ┆ 0.184504 ┆ 0.184504 ┆ 0.184504 ┆ … ┆ 1.0    ┆ 96800.0    ┆ 150213.0   ┆ 2020-03-31 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
└─────────────┴──────────┴──────────┴──────────┴───┴────────┴────────────┴────────────┴────────────┘

shape: (39, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2013-11-04 ┆ 0.96265  ┆ 0.962894 ┆ 0.962162 ┆ … ┆ 11         ┆ 1         ┆ nengyuanh ┆ SHFE      │
│ 14:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2014-09-23 ┆ 0.533289 ┆ 0.533289 ┆ 0.532854 ┆ … ┆ 9          ┆ 2         ┆ nengyuanh ┆ SHFE      │
│ 09:43:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2014-12-04 ┆ 0.557001 ┆ 0.557661 ┆ 0.557001 ┆ … ┆ 12         ┆ 4         ┆ nengyuanh ┆ SHFE      │
│ 13:30:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2015-05-18 ┆ 0.660433 ┆ 0.660661 ┆ 0.660433 ┆ … ┆ 5          ┆ 2         ┆ nengyuanh ┆ SHFE      │
│ 21:25:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2015-06-19 ┆ 0.625793 ┆ 0.625793 ┆ 0.624882 ┆ … ┆ 6          ┆ 7         ┆ nengyuanh ┆ SHFE      │
│ 09:01:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-02-03 ┆ 0.218702 ┆ 0.218702 ┆ 0.218702 ┆ … ┆ 2          ┆ 1         ┆ nengyuanh ┆ SHFE      │
│ 14:41:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-02-03 ┆ 0.218702 ┆ 0.218702 ┆ 0.218702 ┆ … ┆ 2          ┆ 1         ┆ nengyuanh ┆ SHFE      │
│ 14:43:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-02-03 ┆ 0.218702 ┆ 0.218702 ┆ 0.218702 ┆ … ┆ 2          ┆ 1         ┆ nengyuanh ┆ SHFE      │
│ 14:49:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-02-03 ┆ 0.218702 ┆ 0.218702 ┆ 0.218702 ┆ … ┆ 2          ┆ 1         ┆ nengyuanh ┆ SHFE      │
│ 14:53:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-02-20 ┆ 0.227925 ┆ 0.227925 ┆ 0.227827 ┆ … ┆ 2          ┆ 4         ┆ nengyuanh ┆ SHFE      │
│ 10:47:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

CU has 0/788946 rows containing None.
CU has data out of the trading hours:

shape: (3_036, 9)
┌─────────────┬──────────┬──────────┬──────────┬───┬────────┬────────────┬────────────┬────────────┐
│ Time        ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μs ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64        ┆ ---        ┆ date       │
│ ]           ┆          ┆          ┆          ┆   ┆        ┆            ┆ f64        ┆            │
╞═════════════╪══════════╪══════════╪══════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 2013-09-17  ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 538.0  ┆ 1.376204e8 ┆ 247028.0   ┆ 2013-09-17 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-17  ┆ 1.005864 ┆ 1.005864 ┆ 1.005864 ┆ … ┆ 14.0   ┆ 3.6028e6   ┆ 249736.0   ┆ 2013-09-17 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-18  ┆ 1.004691 ┆ 1.004691 ┆ 1.004691 ┆ … ┆ 630.0  ┆ 1.6191e8   ┆ 249710.0   ┆ 2013-09-18 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-18  ┆ 1.010164 ┆ 1.010164 ┆ 1.010164 ┆ … ┆ 0.0    ┆ 0.0        ┆ 233710.0   ┆ 2013-09-18 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-23  ┆ 1.016419 ┆ 1.016419 ┆ 1.016419 ┆ … ┆ 4184.0 ┆ 1.0878e9   ┆ 232122.0   ┆ 2013-09-23 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ …           ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 2020-03-30  ┆ 0.795782 ┆ 0.795782 ┆ 0.795782 ┆ … ┆ 3.0    ┆ 580800.0   ┆ 112746.0   ┆ 2020-03-30 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-03-31  ┆ 0.804619 ┆ 0.804619 ┆ 0.804619 ┆ … ┆ 0.0    ┆ 0.0        ┆ 110825.0   ┆ 2020-03-31 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-04-01  ┆ 0.801537 ┆ 0.801537 ┆ 0.801537 ┆ … ┆ 0.0    ┆ 0.0        ┆ 110620.0   ┆ 2020-04-01 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-04-02  ┆ 0.803592 ┆ 0.803592 ┆ 0.803592 ┆ … ┆ 4.0    ┆ 782000.0   ┆ 109505.0   ┆ 2020-04-02 │
│ 10:15:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-04-02  ┆ 0.814895 ┆ 0.814895 ┆ 0.814895 ┆ … ┆ 2.0    ┆ 396650.0   ┆ 108853.0   ┆ 2020-04-02 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
└─────────────┴──────────┴──────────┴──────────┴───┴────────┴────────────┴────────────┴────────────┘

shape: (312, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2013-11-04 ┆ 1.013096 ┆ 1.013096 ┆ 1.012703 ┆ … ┆ 11         ┆ 1         ┆ yousejins ┆ SHFE      │
│ 14:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2014-03-10 ┆ 0.920105 ┆ 0.920105 ┆ 0.920105 ┆ … ┆ 3          ┆ 1         ┆ yousejins ┆ SHFE      │
│ 11:06:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2014-03-10 ┆ 0.920105 ┆ 0.920105 ┆ 0.920105 ┆ … ┆ 3          ┆ 1         ┆ yousejins ┆ SHFE      │
│ 11:18:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2014-05-07 ┆ 0.94341  ┆ 0.943608 ┆ 0.94341  ┆ … ┆ 5          ┆ 3         ┆ yousejins ┆ SHFE      │
│ 00:31:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2014-09-23 ┆ 0.97281  ┆ 0.97281  ┆ 0.972404 ┆ … ┆ 9          ┆ 2         ┆ yousejins ┆ SHFE      │
│ 09:43:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-03-19 ┆ 0.772147 ┆ 0.772147 ┆ 0.772147 ┆ … ┆ 3          ┆ 4         ┆ yousejins ┆ SHFE      │
│ 13:31:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2020-03-19 ┆ 0.772147 ┆ 0.772147 ┆ 0.772147 ┆ … ┆ 3          ┆ 4         ┆ yousejins ┆ SHFE      │
│ 13:59:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2020-03-19 ┆ 0.772147 ┆ 0.772147 ┆ 0.772147 ┆ … ┆ 3          ┆ 4         ┆ yousejins ┆ SHFE      │
│ 14:09:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2020-03-19 ┆ 0.772147 ┆ 0.772147 ┆ 0.772147 ┆ … ┆ 3          ┆ 4         ┆ yousejins ┆ SHFE      │
│ 14:11:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2020-03-19 ┆ 0.772147 ┆ 0.772147 ┆ 0.772147 ┆ … ┆ 3          ┆ 4         ┆ yousejins ┆ SHFE      │
│ 14:27:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

V has 0/442708 rows containing None.
V has bad data:

shape: (1, 9)
┌────────────┬──────────┬──────────┬──────────┬───┬───────────┬───────────┬────────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume    ┆ Amount    ┆ Open       ┆ TradingDa │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---       ┆ Interest   ┆ y         │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64       ┆ f64       ┆ ---        ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆           ┆           ┆ f64        ┆ date      │
╞════════════╪══════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪════════════╪═══════════╡
│ 2017-03-23 ┆ 1.114814 ┆ 1.114814 ┆ 1.114814 ┆ … ┆ -129880.0 ┆ -4.1299e9 ┆ 91670.0    ┆ 2017-03-2 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆           ┆            ┆ 3         │
└────────────┴──────────┴──────────┴──────────┴───┴───────────┴───────────┴────────────┴───────────┘

V has data out of the trading hours:

shape: (2_936, 9)
┌───────────────┬──────────┬──────────┬──────────┬───┬────────┬─────────┬──────────┬────────────┐
│ Time          ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount  ┆ Open     ┆ TradingDay │
│ ---           ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---     ┆ Interest ┆ ---        │
│ datetime[μs]  ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64     ┆ ---      ┆ date       │
│               ┆          ┆          ┆          ┆   ┆        ┆         ┆ f64      ┆            │
╞═══════════════╪══════════╪══════════╪══════════╪═══╪════════╪═════════╪══════════╪════════════╡
│ 2013-09-17    ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 2.0    ┆ 66100.0 ┆ 26554.0  ┆ 2013-09-17 │
│ 08:59:00      ┆          ┆          ┆          ┆   ┆        ┆         ┆          ┆            │
│ 2013-09-17    ┆ 1.000756 ┆ 1.000756 ┆ 1.000756 ┆ … ┆ 0.0    ┆ 0.0     ┆ 24910.0  ┆ 2013-09-17 │
│ 15:00:00      ┆          ┆          ┆          ┆   ┆        ┆         ┆          ┆            │
│ 2013-09-18    ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 2.0    ┆ 66100.0 ┆ 24910.0  ┆ 2013-09-18 │
│ 08:59:00      ┆          ┆          ┆          ┆   ┆        ┆         ┆          ┆            │
│ 2013-09-18    ┆ 0.995461 ┆ 0.995461 ┆ 0.995461 ┆ … ┆ 0.0    ┆ 0.0     ┆ 24320.0  ┆ 2013-09-18 │
│ 15:00:00      ┆          ┆          ┆          ┆   ┆        ┆         ┆          ┆            │
│ 2013-09-23    ┆ 0.996218 ┆ 0.996218 ┆ 0.996218 ┆ … ┆ 0.0    ┆ 0.0     ┆ 24872.0  ┆ 2013-09-23 │
│ 15:00:00      ┆          ┆          ┆          ┆   ┆        ┆         ┆          ┆            │
│ …             ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …       ┆ …        ┆ …          │
│ 2020-03-26    ┆ 1.043262 ┆ 1.043262 ┆ 1.043262 ┆ … ┆ 0.0    ┆ 0.0     ┆ 108417.0 ┆ 2020-03-26 │
│ 15:00:00      ┆          ┆          ┆          ┆   ┆        ┆         ┆          ┆            │
│ 2020-03-27    ┆ 1.037524 ┆ 1.037524 ┆ 1.037524 ┆ … ┆ 1.0    ┆ 27125.0 ┆ 97576.0  ┆ 2020-03-27 │
│ 11:30:00      ┆          ┆          ┆          ┆   ┆        ┆         ┆          ┆            │
│ 2020-03-27    ┆ 1.03083  ┆ 1.03083  ┆ 1.03083  ┆ … ┆ 0.0    ┆ 0.0     ┆ 90481.0  ┆ 2020-03-27 │
│ 15:00:00      ┆          ┆          ┆          ┆   ┆        ┆         ┆          ┆            │
│ 2020-03-30    ┆ 0.978237 ┆ 0.978237 ┆ 0.978237 ┆ … ┆ 0.0    ┆ 0.0     ┆ 77101.0  ┆ 2020-03-30 │
│ 15:00:00      ┆          ┆          ┆          ┆   ┆        ┆         ┆          ┆            │
│ 2020-03-31    ┆ 0.997362 ┆ 0.997362 ┆ 0.997362 ┆ … ┆ 2.0    ┆ 52150.0 ┆ 73288.0  ┆ 2020-03-31 │
│ 10:15:00      ┆          ┆          ┆          ┆   ┆        ┆         ┆          ┆            │
└───────────────┴──────────┴──────────┴──────────┴───┴────────┴─────────┴──────────┴────────────┘

shape: (4_588, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2013-09-17 ┆ 1.000756 ┆ 1.000756 ┆ 1.000756 ┆ … ┆ 9          ┆ 2         ┆ nengyuanh ┆ DCE       │
│ 09:51:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2013-09-17 ┆ 1.000756 ┆ 1.000756 ┆ 1.000756 ┆ … ┆ 9          ┆ 2         ┆ nengyuanh ┆ DCE       │
│ 10:03:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2013-09-17 ┆ 0.999244 ┆ 0.999244 ┆ 0.999244 ┆ … ┆ 9          ┆ 2         ┆ nengyuanh ┆ DCE       │
│ 10:38:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2013-09-17 ┆ 1.000756 ┆ 1.000756 ┆ 1.000756 ┆ … ┆ 9          ┆ 2         ┆ nengyuanh ┆ DCE       │
│ 10:52:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2013-09-17 ┆ 1.000756 ┆ 1.000756 ┆ 1.000756 ┆ … ┆ 9          ┆ 2         ┆ nengyuanh ┆ DCE       │
│ 10:57:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-02-10 ┆ 1.193392 ┆ 1.193392 ┆ 1.193392 ┆ … ┆ 2          ┆ 1         ┆ nengyuanh ┆ DCE       │
│ 14:05:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-02-10 ┆ 1.191479 ┆ 1.191479 ┆ 1.191479 ┆ … ┆ 2          ┆ 1         ┆ nengyuanh ┆ DCE       │
│ 14:23:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-02-14 ┆ 1.202954 ┆ 1.202954 ┆ 1.201998 ┆ … ┆ 2          ┆ 7         ┆ nengyuanh ┆ DCE       │
│ 11:09:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-02-18 ┆ 1.205823 ┆ 1.205823 ┆ 1.205823 ┆ … ┆ 2          ┆ 2         ┆ nengyuanh ┆ DCE       │
│ 14:04:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-11 ┆ 1.189567 ┆ 1.190523 ┆ 1.189567 ┆ … ┆ 3          ┆ 3         ┆ nengyuanh ┆ DCE       │
│ 11:22:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

PB has 0/719739 rows containing None.
PB has bad data:

shape: (6, 9)
┌────────────┬──────────┬──────────┬──────────┬───┬──────────┬───────────┬────────────┬────────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume   ┆ Amount    ┆ Open       ┆ TradingDay │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---       ┆ Interest   ┆ ---        │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64       ┆ ---        ┆ date       │
│ s]         ┆          ┆          ┆          ┆   ┆          ┆           ┆ f64        ┆            │
╞════════════╪══════════╪══════════╪══════════╪═══╪══════════╪═══════════╪════════════╪════════════╡
│ 2017-07-25 ┆ 1.276855 ┆ 1.276855 ┆ 1.276855 ┆ … ┆ -52368.0 ┆ -4.5882e9 ┆ 37200.0    ┆ 2017-07-26 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆          ┆           ┆            ┆            │
│ 2017-07-27 ┆ 1.314813 ┆ 1.314813 ┆ 1.314813 ┆ … ┆ -90060.0 ┆ -8.1354e9 ┆ 46794.0    ┆ 2017-07-28 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆          ┆           ┆            ┆            │
│ 2017-08-08 ┆ 1.374463 ┆ 1.374463 ┆ 1.374463 ┆ … ┆ -49722.0 ┆ -4.7419e9 ┆ 41162.0    ┆ 2017-08-09 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆          ┆           ┆            ┆            │
│ 2017-08-11 ┆ 1.380247 ┆ 1.380247 ┆ 1.380247 ┆ … ┆ -56912.0 ┆ -5.4446e9 ┆ 31656.0    ┆ 2017-08-12 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆          ┆           ┆            ┆            │
│ 2017-09-04 ┆ 1.412779 ┆ 1.412779 ┆ 1.412779 ┆ … ┆ -83500.0 ┆ -8.1935e9 ┆ 47018.0    ┆ 2017-09-05 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆          ┆           ┆            ┆            │
│ 2017-09-07 ┆ 1.371226 ┆ 1.371226 ┆ 1.371226 ┆ … ┆ -59676.0 ┆ -5.6939e9 ┆ 43008.0    ┆ 2017-09-08 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆          ┆           ┆            ┆            │
└────────────┴──────────┴──────────┴──────────┴───┴──────────┴───────────┴────────────┴────────────┘

PB has data out of the trading hours:

shape: (3_052, 9)
┌─────────────────┬──────────┬──────────┬──────────┬───┬────────┬──────────┬──────────┬────────────┐
│ Time            ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount   ┆ Open     ┆ TradingDay │
│ ---             ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---      ┆ Interest ┆ ---        │
│ datetime[μs]    ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64      ┆ ---      ┆ date       │
│                 ┆          ┆          ┆          ┆   ┆        ┆          ┆ f64      ┆            │
╞═════════════════╪══════════╪══════════╪══════════╪═══╪════════╪══════════╪══════════╪════════════╡
│ 2013-09-17      ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 0.0    ┆ 0.0      ┆ 6722.0   ┆ 2013-09-17 │
│ 08:59:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2013-09-17      ┆ 0.992543 ┆ 0.992543 ┆ 0.992543 ┆ … ┆ 0.0    ┆ 0.0      ┆ 7684.0   ┆ 2013-09-17 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2013-09-18      ┆ 0.990767 ┆ 0.990767 ┆ 0.990767 ┆ … ┆ 6.0    ┆ 418500.0 ┆ 7684.0   ┆ 2013-09-18 │
│ 08:59:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2013-09-18      ┆ 0.997159 ┆ 0.997159 ┆ 0.997159 ┆ … ┆ 0.0    ┆ 0.0      ┆ 7852.0   ┆ 2013-09-18 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2013-09-23      ┆ 0.997869 ┆ 0.997869 ┆ 0.997869 ┆ … ┆ 2.0    ┆ 140500.0 ┆ 7852.0   ┆ 2013-09-23 │
│ 08:59:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ …               ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …        ┆ …        ┆ …          │
│ 2020-05-07      ┆ 1.287716 ┆ 1.287716 ┆ 1.287716 ┆ … ┆ 0.0    ┆ 0.0      ┆ 24414.0  ┆ 2020-05-07 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-05-08      ┆ 1.285861 ┆ 1.285861 ┆ 1.285861 ┆ … ┆ 1.0    ┆ 69325.0  ┆ 25274.0  ┆ 2020-05-08 │
│ 11:30:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-05-08      ┆ 1.288643 ┆ 1.288643 ┆ 1.288643 ┆ … ┆ 1.0    ┆ 69475.0  ┆ 25391.0  ┆ 2020-05-08 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-05-11      ┆ 1.287252 ┆ 1.287252 ┆ 1.287252 ┆ … ┆ 1.0    ┆ 69400.0  ┆ 24875.0  ┆ 2020-05-11 │
│ 10:15:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-05-11      ┆ 1.288643 ┆ 1.288643 ┆ 1.288643 ┆ … ┆ 0.0    ┆ 0.0      ┆ 24460.0  ┆ 2020-05-11 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
└─────────────────┴──────────┴──────────┴──────────┴───┴────────┴──────────┴──────────┴────────────┘

shape: (18_230, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2013-09-17 ┆ 0.99858  ┆ 0.99858  ┆ 0.99858  ┆ … ┆ 9          ┆ 2         ┆ yousejins ┆ SHFE      │
│ 09:13:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2013-09-17 ┆ 0.995028 ┆ 0.995028 ┆ 0.995028 ┆ … ┆ 9          ┆ 2         ┆ yousejins ┆ SHFE      │
│ 09:27:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2013-09-17 ┆ 0.994673 ┆ 0.995028 ┆ 0.994673 ┆ … ┆ 9          ┆ 2         ┆ yousejins ┆ SHFE      │
│ 09:33:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2013-09-17 ┆ 0.996094 ┆ 0.996449 ┆ 0.996094 ┆ … ┆ 9          ┆ 2         ┆ yousejins ┆ SHFE      │
│ 09:57:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2013-09-17 ┆ 0.995384 ┆ 0.995384 ┆ 0.995384 ┆ … ┆ 9          ┆ 2         ┆ yousejins ┆ SHFE      │
│ 10:11:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-05-11 ┆ 1.284006 ┆ 1.284006 ┆ 1.284006 ┆ … ┆ 5          ┆ 1         ┆ yousejins ┆ SHFE      │
│ 09:54:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2020-05-11 ┆ 1.28447  ┆ 1.284933 ┆ 1.284006 ┆ … ┆ 5          ┆ 1         ┆ yousejins ┆ SHFE      │
│ 11:08:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2020-05-11 ┆ 1.285397 ┆ 1.285397 ┆ 1.285397 ┆ … ┆ 5          ┆ 1         ┆ yousejins ┆ SHFE      │
│ 11:23:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2020-05-11 ┆ 1.287252 ┆ 1.287252 ┆ 1.287252 ┆ … ┆ 5          ┆ 1         ┆ yousejins ┆ SHFE      │
│ 13:39:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2020-05-12 ┆ 1.323421 ┆ 1.323885 ┆ 1.323421 ┆ … ┆ 5          ┆ 2         ┆ yousejins ┆ SHFE      │
│ 00:38:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

SP has 0/173765 rows containing None.
SP has data out of the trading hours:

shape: (630, 9)
┌─────────────┬──────────┬──────────┬──────────┬───┬────────┬────────────┬────────────┬────────────┐
│ Time        ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μs ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64        ┆ ---        ┆ date       │
│ ]           ┆          ┆          ┆          ┆   ┆        ┆            ┆ f64        ┆            │
╞═════════════╪══════════╪══════════╪══════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 2018-11-27  ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 2076.0 ┆ 1.10028e8  ┆ 78156.0    ┆ 2018-11-28 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2018-11-28  ┆ 0.978113 ┆ 0.978113 ┆ 0.978113 ┆ … ┆ 44.0   ┆ 2.28168e6  ┆ 101512.0   ┆ 2018-11-28 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2018-11-28  ┆ 0.973585 ┆ 0.973585 ┆ 0.973585 ┆ … ┆ 1444.0 ┆ 7.45104e7  ┆ 101664.0   ┆ 2018-11-29 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2018-11-29  ┆ 0.978868 ┆ 0.978868 ┆ 0.978868 ┆ … ┆ 18.0   ┆ 933600.0   ┆ 110832.0   ┆ 2018-11-29 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2018-11-29  ┆ 0.982642 ┆ 0.982642 ┆ 0.982642 ┆ … ┆ 352.0  ┆ 1.833216e7 ┆ 110770.0   ┆ 2018-11-30 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ …           ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 2020-05-11  ┆ 0.783209 ┆ 0.783209 ┆ 0.783209 ┆ … ┆ 1.0    ┆ 44620.0    ┆ 93003.0    ┆ 2020-05-11 │
│ 10:15:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-05-11  ┆ 0.786017 ┆ 0.786017 ┆ 0.786017 ┆ … ┆ 1.0    ┆ 44780.0    ┆ 92259.0    ┆ 2020-05-11 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-05-12  ┆ 0.784964 ┆ 0.784964 ┆ 0.784964 ┆ … ┆ 1.0    ┆ 44720.0    ┆ 92796.0    ┆ 2020-05-12 │
│ 10:15:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-05-12  ┆ 0.78356  ┆ 0.78356  ┆ 0.78356  ┆ … ┆ 4.0    ┆ 178560.0   ┆ 90771.0    ┆ 2020-05-12 │
│ 11:30:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-05-12  ┆ 0.784262 ┆ 0.784262 ┆ 0.784262 ┆ … ┆ 1.0    ┆ 44680.0    ┆ 90009.0    ┆ 2020-05-12 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
└─────────────┴──────────┴──────────┴──────────┴───┴────────┴────────────┴────────────┴────────────┘

shape: (66, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2018-12-28 ┆ 0.941509 ┆ 0.941509 ┆ 0.941132 ┆ … ┆ 12         ┆ 7         ┆ nengyuanh ┆ SHFE      │
│ 14:21:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-01-24 ┆ 1.016226 ┆ 1.016226 ┆ 1.016226 ┆ … ┆ 1          ┆ 4         ┆ nengyuanh ┆ SHFE      │
│ 13:47:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-02-01 ┆ 1.032453 ┆ 1.032453 ┆ 1.032453 ┆ … ┆ 2          ┆ 7         ┆ nengyuanh ┆ SHFE      │
│ 09:07:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-02-28 ┆ 1.049057 ┆ 1.049057 ┆ 1.048679 ┆ … ┆ 2          ┆ 4         ┆ nengyuanh ┆ SHFE      │
│ 09:29:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-03-06 ┆ 1.053208 ┆ 1.053962 ┆ 1.053208 ┆ … ┆ 3          ┆ 3         ┆ nengyuanh ┆ SHFE      │
│ 09:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-02-20 ┆ 0.816532 ┆ 0.816532 ┆ 0.816532 ┆ … ┆ 2          ┆ 4         ┆ nengyuanh ┆ SHFE      │
│ 10:47:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-04-07 ┆ 0.811126 ┆ 0.811126 ┆ 0.810766 ┆ … ┆ 4          ┆ 2         ┆ nengyuanh ┆ SHFE      │
│ 09:42:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-04-07 ┆ 0.814009 ┆ 0.814009 ┆ 0.814009 ┆ … ┆ 4          ┆ 2         ┆ nengyuanh ┆ SHFE      │
│ 14:09:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-04-07 ┆ 0.813649 ┆ 0.814369 ┆ 0.813649 ┆ … ┆ 4          ┆ 2         ┆ nengyuanh ┆ SHFE      │
│ 14:21:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-05-08 ┆ 0.786368 ┆ 0.786719 ┆ 0.786368 ┆ … ┆ 5          ┆ 1         ┆ nengyuanh ┆ SHFE      │
│ 21:42:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

ZN has 0/790108 rows containing None.
ZN has bad data:

shape: (6, 9)
┌────────────┬──────────┬──────────┬──────────┬───┬───────────┬────────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume    ┆ Amount     ┆ Open      ┆ TradingDa │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---        ┆ Interest  ┆ y         │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64       ┆ f64        ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆           ┆            ┆ f64       ┆ date      │
╞════════════╪══════════╪══════════╪══════════╪═══╪═══════════╪════════════╪═══════════╪═══════════╡
│ 2017-07-03 ┆ 1.6082   ┆ 1.6082   ┆ 1.6082   ┆ … ┆ -455984.0 ┆ -5.1989e10 ┆ 243412.0  ┆ 2017-07-0 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 4         │
│ 2017-07-12 ┆ 1.641512 ┆ 1.641512 ┆ 1.641512 ┆ … ┆ -551362.0 ┆ -6.4072e10 ┆ 304068.0  ┆ 2017-07-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 3         │
│ 2017-07-21 ┆ 1.60958  ┆ 1.60958  ┆ 1.60958  ┆ … ┆ -504940.0 ┆ -5.7539e10 ┆ 266408.0  ┆ 2017-07-2 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 2         │
│ 2017-07-25 ┆ 1.635196 ┆ 1.635196 ┆ 1.635196 ┆ … ┆ -529890.0 ┆ -6.1206e10 ┆ 262316.0  ┆ 2017-07-2 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 6         │
│ 2017-07-27 ┆ 1.634143 ┆ 1.634143 ┆ 1.634143 ┆ … ┆ -406886.0 ┆ -4.7402e10 ┆ 244618.0  ┆ 2017-07-2 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 8         │
│ 2017-08-08 ┆ 1.670637 ┆ 1.670637 ┆ 1.670637 ┆ … ┆ -332394.0 ┆ -3.9713e10 ┆ 156594.0  ┆ 2017-08-0 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 9         │
└────────────┴──────────┴──────────┴──────────┴───┴───────────┴────────────┴───────────┴───────────┘

ZN has data out of the trading hours:

shape: (3_175, 9)
┌─────────────┬──────────┬──────────┬──────────┬───┬────────┬────────────┬────────────┬────────────┐
│ Time        ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μs ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64        ┆ ---        ┆ date       │
│ ]           ┆          ┆          ┆          ┆   ┆        ┆            ┆ f64        ┆            │
╞═════════════╪══════════╪══════════╪══════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 2013-09-17  ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 62.0   ┆ 4.53995e6  ┆ 136922.0   ┆ 2013-09-17 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-17  ┆ 1.001024 ┆ 1.001024 ┆ 1.001024 ┆ … ┆ 0.0    ┆ 0.0        ┆ 136766.0   ┆ 2013-09-17 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-18  ┆ 0.998976 ┆ 0.998976 ┆ 0.998976 ┆ … ┆ 38.0   ┆ 2.7797e6   ┆ 136770.0   ┆ 2013-09-18 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-18  ┆ 1.001707 ┆ 1.001707 ┆ 1.001707 ┆ … ┆ 2.0    ┆ 146700.0   ┆ 140350.0   ┆ 2013-09-18 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-23  ┆ 1.000341 ┆ 1.000341 ┆ 1.000341 ┆ … ┆ 118.0  ┆ 8.6435e6   ┆ 140416.0   ┆ 2013-09-23 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ …           ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 2020-05-22  ┆ 1.449519 ┆ 1.449519 ┆ 1.449519 ┆ … ┆ 1.0    ┆ 81975.0    ┆ 97446.0    ┆ 2020-05-22 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-05-25  ┆ 1.444657 ┆ 1.444657 ┆ 1.444657 ┆ … ┆ 8.0    ┆ 653600.0   ┆ 96439.0    ┆ 2020-05-25 │
│ 10:15:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-05-25  ┆ 1.444657 ┆ 1.444657 ┆ 1.444657 ┆ … ┆ 4.0    ┆ 326800.0   ┆ 93999.0    ┆ 2020-05-25 │
│ 11:30:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-05-25  ┆ 1.443773 ┆ 1.443773 ┆ 1.443773 ┆ … ┆ 0.0    ┆ 0.0        ┆ 93825.0    ┆ 2020-05-25 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-05-26  ┆ 1.437142 ┆ 1.437142 ┆ 1.437142 ┆ … ┆ 23.0   ┆ 1.869325e6 ┆ 93686.0    ┆ 2020-05-26 │
│ 10:15:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
└─────────────┴──────────┴──────────┴──────────┴───┴────────┴────────────┴────────────┴────────────┘

shape: (743, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2013-09-23 ┆ 0.999317 ┆ 0.999317 ┆ 0.999317 ┆ … ┆ 9          ┆ 1         ┆ yousejins ┆ SHFE      │
│ 11:05:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2013-09-26 ┆ 1.00478  ┆ 1.00478  ┆ 1.004438 ┆ … ┆ 9          ┆ 4         ┆ yousejins ┆ SHFE      │
│ 11:28:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2013-10-08 ┆ 1.005121 ┆ 1.005121 ┆ 1.005121 ┆ … ┆ 10         ┆ 2         ┆ yousejins ┆ SHFE      │
│ 11:19:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2013-10-08 ┆ 1.005463 ┆ 1.005463 ┆ 1.005463 ┆ … ┆ 10         ┆ 2         ┆ yousejins ┆ SHFE      │
│ 13:53:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2013-10-08 ┆ 1.005463 ┆ 1.005463 ┆ 1.005121 ┆ … ┆ 10         ┆ 2         ┆ yousejins ┆ SHFE      │
│ 14:07:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-05-09 ┆ 1.489741 ┆ 1.490181 ┆ 1.489741 ┆ … ┆ 5          ┆ 1         ┆ yousejins ┆ SHFE      │
│ 00:28:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2020-05-09 ┆ 1.489741 ┆ 1.489741 ┆ 1.489741 ┆ … ┆ 5          ┆ 1         ┆ yousejins ┆ SHFE      │
│ 00:37:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2020-05-09 ┆ 1.4893   ┆ 1.4893   ┆ 1.4893   ┆ … ┆ 5          ┆ 1         ┆ yousejins ┆ SHFE      │
│ 00:40:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2020-05-09 ┆ 1.489741 ┆ 1.490181 ┆ 1.489741 ┆ … ┆ 5          ┆ 1         ┆ yousejins ┆ SHFE      │
│ 00:45:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
│ 2020-05-13 ┆ 1.472507 ┆ 1.472507 ┆ 1.472065 ┆ … ┆ 5          ┆ 3         ┆ yousejins ┆ SHFE      │
│ 00:28:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ hu        ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

FG has 0/583914 rows containing None.
FG has bad data:

shape: (12, 9)
┌────────────┬──────────┬──────────┬──────────┬───┬───────────┬───────────┬────────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume    ┆ Amount    ┆ Open       ┆ TradingDa │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---       ┆ Interest   ┆ y         │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64       ┆ f64       ┆ ---        ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆           ┆           ┆ f64        ┆ date      │
╞════════════╪══════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪════════════╪═══════════╡
│ 2018-01-11 ┆ 1.163708 ┆ 1.163708 ┆ 1.163708 ┆ … ┆ -278680.0 ┆ -8.3214e9 ┆ 449200.0   ┆ 2018-01-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆           ┆            ┆ 2         │
│ 2018-08-13 ┆ 1.203239 ┆ 1.203239 ┆ 1.203239 ┆ … ┆ -159850.0 ┆ -4.6133e9 ┆ 190414.0   ┆ 2018-08-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆           ┆            ┆ 4         │
│ 2018-09-25 ┆ 1.140701 ┆ 1.140701 ┆ 1.140701 ┆ … ┆ -138518.0 ┆ -3.7899e9 ┆ 198304.0   ┆ 2018-09-2 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆           ┆            ┆ 5         │
│ 2018-10-16 ┆ 1.099009 ┆ 1.099009 ┆ 1.099009 ┆ … ┆ -134072.0 ┆ -3.5341e9 ┆ 225858.0   ┆ 2018-10-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆           ┆            ┆ 7         │
│ 2019-01-02 ┆ 1.084816 ┆ 1.084816 ┆ 1.084816 ┆ … ┆ -108978.0 ┆ -2.8291e9 ┆ 147590.0   ┆ 2019-01-0 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆           ┆            ┆ 2         │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …         ┆ …         ┆ …          ┆ …         │
│ 2020-07-29 ┆ 1.470668 ┆ 1.473318 ┆ 1.470668 ┆ … ┆ 440.0     ┆ -19985.0  ┆ 217272.0   ┆ 2020-07-2 │
│ 13:54:00   ┆          ┆          ┆          ┆   ┆           ┆           ┆            ┆ 9         │
│ 2020-08-18 ┆ 1.697864 ┆ 1.69878  ┆ 1.697864 ┆ … ┆ 705.0     ┆ -87412.0  ┆ 656164.0   ┆ 2020-08-1 │
│ 14:42:00   ┆          ┆          ┆          ┆   ┆           ┆           ┆            ┆ 8         │
│ 2020-08-28 ┆ 1.599928 ┆ 1.600844 ┆ 1.599928 ┆ … ┆ 356.0     ┆ -30782.0  ┆ 745789.0   ┆ 2020-08-2 │
│ 09:41:00   ┆          ┆          ┆          ┆   ┆           ┆           ┆            ┆ 8         │
│ 2020-09-04 ┆ 1.608166 ┆ 1.609081 ┆ 1.607251 ┆ … ┆ 918.0     ┆ -200210.0 ┆ 688448.0   ┆ 2020-09-0 │
│ 10:58:00   ┆          ┆          ┆          ┆   ┆           ┆           ┆            ┆ 4         │
│ 2020-12-28 ┆ 1.775846 ┆ 1.776803 ┆ 1.775846 ┆ … ┆ 463.0     ┆ -23914.0  ┆ 436433.0   ┆ 2020-12-2 │
│ 11:05:00   ┆          ┆          ┆          ┆   ┆           ┆           ┆            ┆ 8         │
└────────────┴──────────┴──────────┴──────────┴───┴───────────┴───────────┴────────────┴───────────┘

FG has data out of the trading hours:

shape: (1_609, 9)
┌─────────────┬──────────┬──────────┬──────────┬───┬────────┬────────────┬────────────┬────────────┐
│ Time        ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μs ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64        ┆ ---        ┆ date       │
│ ]           ┆          ┆          ┆          ┆   ┆        ┆            ┆ f64        ┆            │
╞═════════════╪══════════╪══════════╪══════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 2013-09-30  ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 746.0  ┆ 1.950044e7 ┆ 730560.0   ┆ 2013-09-30 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-30  ┆ 0.996174 ┆ 0.996174 ┆ 0.996174 ┆ … ┆ 0.0    ┆ 0.0        ┆ 680604.0   ┆ 2013-09-30 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-10-09  ┆ 1.002295 ┆ 1.002295 ┆ 1.002295 ┆ … ┆ 1092.0 ┆ 2.86104e7  ┆ 692734.0   ┆ 2013-10-09 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-10-09  ┆ 1.009946 ┆ 1.009946 ┆ 1.009946 ┆ … ┆ 44.0   ┆ 1.1616e6   ┆ 727906.0   ┆ 2013-10-09 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-10-10  ┆ 1.009181 ┆ 1.009181 ┆ 1.009181 ┆ … ┆ 1358.0 ┆ 3.582404e7 ┆ 728552.0   ┆ 2013-10-10 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ …           ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 2021-01-26  ┆ 1.683942 ┆ 1.683942 ┆ 1.683942 ┆ … ┆ 1474.0 ┆ 2.592766e6 ┆ 478476.0   ┆ 2021-01-27 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-27  ┆ 1.699259 ┆ 1.699259 ┆ 1.699259 ┆ … ┆ 997.0  ┆ 1.769675e6 ┆ 466503.0   ┆ 2021-01-28 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-28  ┆ 1.713619 ┆ 1.713619 ┆ 1.713619 ┆ … ┆ 2554.0 ┆ 4.57166e6  ┆ 488734.0   ┆ 2021-01-29 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-29  ┆ 1.705961 ┆ 1.705961 ┆ 1.705961 ┆ … ┆ 1905.0 ┆ 3.39471e6  ┆ 473243.0   ┆ 2021-01-30 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-02-01  ┆ 1.727022 ┆ 1.727022 ┆ 1.727022 ┆ … ┆ 1063.0 ┆ 1.917652e6 ┆ 470751.0   ┆ 2021-02-02 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
└─────────────┴──────────┴──────────┴──────────┴───┴────────┴────────────┴────────────┴────────────┘

shape: (48, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2014-10-16 ┆ 0.782386 ┆ 0.782386 ┆ 0.781621 ┆ … ┆ 10         ┆ 4         ┆ qinggongj ┆ CZCE      │
│ 10:04:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ iancai    ┆           │
│ 2015-07-15 ┆ 0.669275 ┆ 0.670047 ┆ 0.668503 ┆ … ┆ 7          ┆ 4         ┆ qinggongj ┆ CZCE      │
│ 21:35:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ iancai    ┆           │
│ 2016-01-12 ┆ 0.644543 ┆ 0.644543 ┆ 0.643768 ┆ … ┆ 1          ┆ 3         ┆ qinggongj ┆ CZCE      │
│ 22:59:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ iancai    ┆           │
│ 2018-07-19 ┆ 1.197286 ┆ 1.198101 ┆ 1.196472 ┆ … ┆ 7          ┆ 7         ┆ qinggongj ┆ CZCE      │
│ 21:03:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ iancai    ┆           │
│ 2018-08-02 ┆ 1.205431 ┆ 1.205431 ┆ 1.204617 ┆ … ┆ 8          ┆ 7         ┆ qinggongj ┆ CZCE      │
│ 23:15:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ iancai    ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2019-12-11 ┆ 1.285134 ┆ 1.285134 ┆ 1.28426  ┆ … ┆ 12         ┆ 3         ┆ qinggongj ┆ CZCE      │
│ 11:08:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ iancai    ┆           │
│ 2019-12-11 ┆ 1.285134 ┆ 1.285134 ┆ 1.285134 ┆ … ┆ 12         ┆ 3         ┆ qinggongj ┆ CZCE      │
│ 11:21:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ iancai    ┆           │
│ 2019-12-11 ┆ 1.285134 ┆ 1.285134 ┆ 1.285134 ┆ … ┆ 12         ┆ 3         ┆ qinggongj ┆ CZCE      │
│ 14:09:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ iancai    ┆           │
│ 2019-12-11 ┆ 1.285134 ┆ 1.285134 ┆ 1.285134 ┆ … ┆ 12         ┆ 3         ┆ qinggongj ┆ CZCE      │
│ 14:24:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ iancai    ┆           │
│ 2019-12-20 ┆ 1.290409 ┆ 1.291288 ┆ 1.290409 ┆ … ┆ 12         ┆ 1         ┆ qinggongj ┆ CZCE      │
│ 22:46:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ iancai    ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

JM has 0/605064 rows containing None.
JM has data out of the trading hours:

shape: (3_006, 9)
┌─────────────┬──────────┬──────────┬──────────┬───┬────────┬────────────┬────────────┬────────────┐
│ Time        ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μs ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64        ┆ ---        ┆ date       │
│ ]           ┆          ┆          ┆          ┆   ┆        ┆            ┆ f64        ┆            │
╞═════════════╪══════════╪══════════╪══════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 2013-09-17  ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 236.0  ┆ 1.60008e7  ┆ 259494.0   ┆ 2013-09-17 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-17  ┆ 1.010619 ┆ 1.010619 ┆ 1.010619 ┆ … ┆ 2.0    ┆ 137040.0   ┆ 254566.0   ┆ 2013-09-17 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-18  ┆ 1.00708  ┆ 1.00708  ┆ 1.00708  ┆ … ┆ 378.0  ┆ 2.580984e7 ┆ 254442.0   ┆ 2013-09-18 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-18  ┆ 1.026549 ┆ 1.026549 ┆ 1.026549 ┆ … ┆ 2.0    ┆ 139200.0   ┆ 266166.0   ┆ 2013-09-18 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-23  ┆ 1.021239 ┆ 1.021239 ┆ 1.021239 ┆ … ┆ 730.0  ┆ 5.05452e7  ┆ 266550.0   ┆ 2013-09-23 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ …           ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 2020-03-25  ┆ 1.497572 ┆ 1.497572 ┆ 1.497572 ┆ … ┆ 0.0    ┆ 0.0        ┆ 80265.0    ┆ 2020-03-25 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-03-26  ┆ 1.485691 ┆ 1.485691 ┆ 1.485691 ┆ … ┆ 0.0    ┆ 0.0        ┆ 75765.0    ┆ 2020-03-26 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-03-27  ┆ 1.489849 ┆ 1.489849 ┆ 1.489849 ┆ … ┆ 0.0    ┆ 0.0        ┆ 74177.0    ┆ 2020-03-27 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-03-30  ┆ 1.475592 ┆ 1.475592 ┆ 1.475592 ┆ … ┆ 0.0    ┆ 0.0        ┆ 69169.0    ┆ 2020-03-30 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-03-31  ┆ 1.497572 ┆ 1.497572 ┆ 1.497572 ┆ … ┆ 0.0    ┆ 0.0        ┆ 67685.0    ┆ 2020-03-31 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
└─────────────┴──────────┴──────────┴──────────┴───┴────────┴────────────┴────────────┴────────────┘

shape: (1_221, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2014-12-27 ┆ 0.558618 ┆ 0.558618 ┆ 0.558618 ┆ … ┆ 12         ┆ 1         ┆ heise     ┆ DCE       │
│ 00:18:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2014-12-27 ┆ 0.558618 ┆ 0.558618 ┆ 0.558618 ┆ … ┆ 12         ┆ 1         ┆ heise     ┆ DCE       │
│ 00:31:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2014-12-27 ┆ 0.558618 ┆ 0.558618 ┆ 0.558618 ┆ … ┆ 12         ┆ 1         ┆ heise     ┆ DCE       │
│ 00:39:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2014-12-27 ┆ 0.558618 ┆ 0.558618 ┆ 0.558618 ┆ … ┆ 12         ┆ 1         ┆ heise     ┆ DCE       │
│ 00:41:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2014-12-27 ┆ 0.558618 ┆ 0.558618 ┆ 0.558618 ┆ … ┆ 12         ┆ 1         ┆ heise     ┆ DCE       │
│ 01:07:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-01-09 ┆ 1.431633 ┆ 1.431633 ┆ 1.431039 ┆ … ┆ 1          ┆ 7         ┆ heise     ┆ DCE       │
│ 22:06:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-01-10 ┆ 1.440544 ┆ 1.440544 ┆ 1.43995  ┆ … ┆ 1          ┆ 1         ┆ heise     ┆ DCE       │
│ 22:24:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-01-13 ┆ 1.435198 ┆ 1.435792 ┆ 1.435198 ┆ … ┆ 1          ┆ 2         ┆ heise     ┆ DCE       │
│ 22:25:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-01-17 ┆ 1.454207 ┆ 1.454207 ┆ 1.453613 ┆ … ┆ 1          ┆ 1         ┆ heise     ┆ DCE       │
│ 22:05:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-01-17 ┆ 1.453613 ┆ 1.453613 ┆ 1.453613 ┆ … ┆ 1          ┆ 1         ┆ heise     ┆ DCE       │
│ 22:15:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

CY has 0/223237 rows containing None.
CY has bad data:

shape: (10, 9)
┌────────────┬──────────┬──────────┬──────────┬───┬──────────┬───────────┬────────────┬────────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume   ┆ Amount    ┆ Open       ┆ TradingDay │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---       ┆ Interest   ┆ ---        │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64       ┆ ---        ┆ date       │
│ s]         ┆          ┆          ┆          ┆   ┆          ┆           ┆ f64        ┆            │
╞════════════╪══════════╪══════════╪══════════╪═══╪══════════╪═══════════╪════════════╪════════════╡
│ 2018-06-19 ┆ 1.135308 ┆ 1.135308 ┆ 1.135308 ┆ … ┆ -54064.0 ┆ -6.9959e9 ┆ 7922.0     ┆ 2018-06-19 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆          ┆           ┆            ┆            │
│ 2018-08-13 ┆ 1.119954 ┆ 1.119954 ┆ 1.119954 ┆ … ┆ -4662.0  ┆ -5.9510e8 ┆ 2156.0     ┆ 2018-08-14 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆          ┆           ┆            ┆            │
│ 2018-09-25 ┆ 1.141668 ┆ 1.141668 ┆ 1.14101  ┆ … ┆ -3200.0  ┆ -4.1616e8 ┆ 1864.0     ┆ 2018-09-25 │
│ 09:00:00   ┆          ┆          ┆          ┆   ┆          ┆           ┆            ┆            │
│ 2018-11-05 ┆ 1.040152 ┆ 1.040152 ┆ 1.040152 ┆ … ┆ -1076.0  ┆ -1.2691e8 ┆ 1248.0     ┆ 2018-11-06 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆          ┆           ┆            ┆            │
│ 2019-01-02 ┆ 1.040593 ┆ 1.040593 ┆ 1.040593 ┆ … ┆ -270.0   ┆ -3.186e7  ┆ 24.0       ┆ 2019-01-02 │
│ 09:44:00   ┆          ┆          ┆          ┆   ┆          ┆           ┆            ┆            │
│ 2020-06-15 ┆ 0.773855 ┆ 0.774259 ┆ 0.773855 ┆ … ┆ 1.0      ┆ -19135.0  ┆ 8519.0     ┆ 2020-06-15 │
│ 14:11:00   ┆          ┆          ┆          ┆   ┆          ┆           ┆            ┆            │
│ 2020-06-22 ┆ 0.773855 ┆ 0.773855 ┆ 0.773855 ┆ … ┆ 1.0      ┆ -1755.0   ┆ 8173.0     ┆ 2020-06-22 │
│ 11:21:00   ┆          ┆          ┆          ┆   ┆          ┆           ┆            ┆            │
│ 2020-06-30 ┆ 0.767796 ┆ 0.767998 ┆ 0.767796 ┆ … ┆ 1.0      ┆ -9450.0   ┆ 8461.0     ┆ 2020-06-30 │
│ 14:39:00   ┆          ┆          ┆          ┆   ┆          ┆           ┆            ┆            │
│ 2020-07-23 ┆ 0.770018 ┆ 0.770018 ┆ 0.770018 ┆ … ┆ 1.0      ┆ -16035.0  ┆ 8034.0     ┆ 2020-07-23 │
│ 14:06:00   ┆          ┆          ┆          ┆   ┆          ┆           ┆            ┆            │
│ 2021-01-08 ┆ 0.784487 ┆ 0.784838 ┆ 0.784487 ┆ … ┆ 3.0      ┆ -300.0    ┆ 8812.0     ┆ 2021-01-08 │
│ 14:44:00   ┆          ┆          ┆          ┆   ┆          ┆           ┆            ┆            │
└────────────┴──────────┴──────────┴──────────┴───┴──────────┴───────────┴────────────┴────────────┘

CY has data out of the trading hours:

shape: (272, 9)
┌────────────────┬──────────┬──────────┬──────────┬───┬────────┬───────────┬──────────┬────────────┐
│ Time           ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount    ┆ Open     ┆ TradingDay │
│ ---            ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---       ┆ Interest ┆ ---        │
│ datetime[μs]   ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64       ┆ ---      ┆ date       │
│                ┆          ┆          ┆          ┆   ┆        ┆           ┆ f64      ┆            │
╞════════════════╪══════════╪══════════╪══════════╪═══╪════════╪═══════════╪══════════╪════════════╡
│ 2017-08-18     ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 72.0   ┆ 8.2818e6  ┆ 7626.0   ┆ 2017-08-19 │
│ 20:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2017-08-21     ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 10.0   ┆ 1.15025e6 ┆ 8478.0   ┆ 2017-08-22 │
│ 20:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2017-08-22     ┆ 1.00326  ┆ 1.00326  ┆ 1.00326  ┆ … ┆ 4.0    ┆ 461600.0  ┆ 7512.0   ┆ 2017-08-23 │
│ 20:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2017-08-23     ┆ 1.002825 ┆ 1.002825 ┆ 1.002825 ┆ … ┆ 40.0   ┆ 4.614e6   ┆ 6994.0   ┆ 2017-08-24 │
│ 20:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2017-08-24     ┆ 1.001521 ┆ 1.001521 ┆ 1.001521 ┆ … ┆ 4.0    ┆ 460800.0  ┆ 6416.0   ┆ 2017-08-25 │
│ 20:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ …              ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …         ┆ …        ┆ …          │
│ 2021-01-26     ┆ 0.756231 ┆ 0.756231 ┆ 0.756231 ┆ … ┆ 13.0   ┆ 280085.0  ┆ 8961.0   ┆ 2021-01-27 │
│ 20:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2021-01-27     ┆ 0.764304 ┆ 0.764304 ┆ 0.764304 ┆ … ┆ 3.0    ┆ 65325.0   ┆ 8580.0   ┆ 2021-01-28 │
│ 20:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2021-01-28     ┆ 0.755354 ┆ 0.755354 ┆ 0.755354 ┆ … ┆ 12.0   ┆ 258240.0  ┆ 8637.0   ┆ 2021-01-29 │
│ 20:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2021-01-29     ┆ 0.757284 ┆ 0.757284 ┆ 0.757284 ┆ … ┆ 9.0    ┆ 194175.0  ┆ 8325.0   ┆ 2021-01-30 │
│ 20:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2021-02-01     ┆ 0.764655 ┆ 0.764655 ┆ 0.764655 ┆ … ┆ 5.0    ┆ 108925.0  ┆ 8217.0   ┆ 2021-02-02 │
│ 20:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
└────────────────┴──────────┴──────────┴──────────┴───┴────────┴───────────┴──────────┴────────────┘

shape: (11_991, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2017-08-22 ┆ 1.001304 ┆ 1.001304 ┆ 1.001304 ┆ … ┆ 8          ┆ 2         ┆ nongfucha ┆ CZCE      │
│ 11:11:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2017-08-22 ┆ 1.002391 ┆ 1.002391 ┆ 1.002391 ┆ … ┆ 8          ┆ 2         ┆ nongfucha ┆ CZCE      │
│ 14:14:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2017-08-23 ┆ 1.002825 ┆ 1.003043 ┆ 1.002825 ┆ … ┆ 8          ┆ 3         ┆ nongfucha ┆ CZCE      │
│ 14:48:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2017-08-23 ┆ 1.003695 ┆ 1.003695 ┆ 1.003695 ┆ … ┆ 8          ┆ 4         ┆ nongfucha ┆ CZCE      │
│ 22:14:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2017-08-23 ┆ 1.002825 ┆ 1.002825 ┆ 1.002825 ┆ … ┆ 8          ┆ 4         ┆ nongfucha ┆ CZCE      │
│ 23:16:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2021-02-01 ┆ 0.763076 ┆ 0.763251 ┆ 0.7629   ┆ … ┆ 2          ┆ 1         ┆ nongfucha ┆ CZCE      │
│ 09:39:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2021-02-01 ┆ 0.762549 ┆ 0.762549 ┆ 0.762549 ┆ … ┆ 2          ┆ 1         ┆ nongfucha ┆ CZCE      │
│ 10:13:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2021-02-01 ┆ 0.76641  ┆ 0.76641  ┆ 0.76641  ┆ … ┆ 2          ┆ 1         ┆ nongfucha ┆ CZCE      │
│ 11:11:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2021-02-01 ┆ 0.76641  ┆ 0.76641  ┆ 0.76641  ┆ … ┆ 2          ┆ 1         ┆ nongfucha ┆ CZCE      │
│ 14:22:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2021-02-01 ┆ 0.76448  ┆ 0.76448  ┆ 0.76448  ┆ … ┆ 2          ┆ 2         ┆ nongfucha ┆ CZCE      │
│ 21:38:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

BU has 0/575702 rows containing None.
BU has bad data:

shape: (2, 9)
┌────────────┬──────────┬──────────┬──────────┬───┬───────────┬────────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume    ┆ Amount     ┆ Open      ┆ TradingDa │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---        ┆ Interest  ┆ y         │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64       ┆ f64        ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆           ┆            ┆ f64       ┆ date      │
╞════════════╪══════════╪══════════╪══════════╪═══╪═══════════╪════════════╪═══════════╪═══════════╡
│ 2017-03-20 ┆ 0.412412 ┆ 0.412412 ┆ 0.412412 ┆ … ┆ -873132.0 ┆ -2.3586e10 ┆ 515568.0  ┆ 2017-03-2 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 1         │
│ 2017-03-21 ┆ 0.41826  ┆ 0.41826  ┆ 0.41826  ┆ … ┆ -863500.0 ┆ -2.3286e10 ┆ 521782.0  ┆ 2017-03-2 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 2         │
└────────────┴──────────┴──────────┴──────────┴───┴───────────┴────────────┴───────────┴───────────┘

BU has data out of the trading hours:

shape: (3_145, 9)
┌─────────────┬──────────┬──────────┬──────────┬───┬────────┬────────────┬────────────┬────────────┐
│ Time        ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μs ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64        ┆ ---        ┆ date       │
│ ]           ┆          ┆          ┆          ┆   ┆        ┆            ┆ f64        ┆            │
╞═════════════╪══════════╪══════════╪══════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 2013-10-10  ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 438.0  ┆ 1.95348e7  ┆ 65346.0    ┆ 2013-10-10 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-10-10  ┆ 1.009417 ┆ 1.009417 ┆ 1.009417 ┆ … ┆ 0.0    ┆ 0.0        ┆ 54008.0    ┆ 2013-10-10 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-10-11  ┆ 1.011211 ┆ 1.011211 ┆ 1.011211 ┆ … ┆ 970.0  ┆ 4.3747e7   ┆ 54212.0    ┆ 2013-10-11 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-10-11  ┆ 1.001345 ┆ 1.001345 ┆ 1.001345 ┆ … ┆ 38.0   ┆ 1.697e6    ┆ 60936.0    ┆ 2013-10-11 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-10-14  ┆ 1.003587 ┆ 1.003587 ┆ 1.003587 ┆ … ┆ 722.0  ┆ 3.231672e7 ┆ 60770.0    ┆ 2013-10-14 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ …           ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 2020-04-29  ┆ 0.294437 ┆ 0.294437 ┆ 0.294437 ┆ … ┆ 1.0    ┆ 20660.0    ┆ 339007.0   ┆ 2020-04-29 │
│ 10:15:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-04-29  ┆ 0.292156 ┆ 0.292156 ┆ 0.292156 ┆ … ┆ 3.0    ┆ 61460.0    ┆ 329553.0   ┆ 2020-04-29 │
│ 11:30:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-04-29  ┆ 0.291586 ┆ 0.291586 ┆ 0.291586 ┆ … ┆ 105.0  ┆ 2.14826e6  ┆ 299335.0   ┆ 2020-04-29 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-04-30  ┆ 0.297572 ┆ 0.297572 ┆ 0.297572 ┆ … ┆ 3.0    ┆ 62660.0    ┆ 289155.0   ┆ 2020-04-30 │
│ 10:15:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-04-30  ┆ 0.297857 ┆ 0.297857 ┆ 0.297857 ┆ … ┆ 1.0    ┆ 20900.0    ┆ 284229.0   ┆ 2020-04-30 │
│ 11:30:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
└─────────────┴──────────┴──────────┴──────────┴───┴────────┴────────────┴────────────┴────────────┘

shape: (3_402, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2013-11-04 ┆ 0.967713 ┆ 0.967713 ┆ 0.967265 ┆ … ┆ 11         ┆ 1         ┆ nengyuanh ┆ SHFE      │
│ 14:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2013-12-19 ┆ 0.971749 ┆ 0.971749 ┆ 0.971749 ┆ … ┆ 12         ┆ 4         ┆ nengyuanh ┆ SHFE      │
│ 10:51:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2013-12-30 ┆ 0.969058 ┆ 0.969058 ┆ 0.969058 ┆ … ┆ 12         ┆ 1         ┆ nengyuanh ┆ SHFE      │
│ 10:58:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2013-12-31 ┆ 0.969058 ┆ 0.969058 ┆ 0.969058 ┆ … ┆ 12         ┆ 2         ┆ nengyuanh ┆ SHFE      │
│ 09:50:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2014-01-06 ┆ 0.962332 ┆ 0.962332 ┆ 0.961883 ┆ … ┆ 1          ┆ 1         ┆ nengyuanh ┆ SHFE      │
│ 09:48:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-01-21 ┆ 0.447498 ┆ 0.447783 ┆ 0.447498 ┆ … ┆ 1          ┆ 2         ┆ nengyuanh ┆ SHFE      │
│ 10:43:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-02-20 ┆ 0.438092 ┆ 0.438377 ┆ 0.438092 ┆ … ┆ 2          ┆ 4         ┆ nengyuanh ┆ SHFE      │
│ 10:47:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-09 ┆ 0.37453  ┆ 0.37453  ┆ 0.37453  ┆ … ┆ 3          ┆ 1         ┆ nengyuanh ┆ SHFE      │
│ 11:08:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-09 ┆ 0.37453  ┆ 0.37453  ┆ 0.37453  ┆ … ┆ 3          ┆ 1         ┆ nengyuanh ┆ SHFE      │
│ 11:10:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-09 ┆ 0.37453  ┆ 0.37453  ┆ 0.37453  ┆ … ┆ 3          ┆ 1         ┆ nengyuanh ┆ SHFE      │
│ 11:26:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

SF has 0/299878 rows containing None.
SF has bad data:

shape: (7, 9)
┌────────────┬──────────┬──────────┬──────────┬───┬───────────┬───────────┬────────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume    ┆ Amount    ┆ Open       ┆ TradingDa │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---       ┆ Interest   ┆ y         │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64       ┆ f64       ┆ ---        ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆           ┆           ┆ f64        ┆ date      │
╞════════════╪══════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪════════════╪═══════════╡
│ 2018-01-12 ┆ 1.202052 ┆ 1.202052 ┆ 1.202052 ┆ … ┆ -205660.0 ┆ -6.5708e9 ┆ 231882.0   ┆ 2018-01-1 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆           ┆            ┆ 2         │
│ 2018-08-14 ┆ 1.264386 ┆ 1.264386 ┆ 1.264386 ┆ … ┆ -175160.0 ┆ -6.0605e9 ┆ 135274.0   ┆ 2018-08-1 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆           ┆            ┆ 4         │
│ 2018-09-25 ┆ 1.195217 ┆ 1.195217 ┆ 1.195217 ┆ … ┆ -99342.0  ┆ -3.3359e9 ┆ 131926.0   ┆ 2018-09-2 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆           ┆            ┆ 5         │
│ 2018-10-17 ┆ 1.213369 ┆ 1.213369 ┆ 1.213369 ┆ … ┆ -101444.0 ┆ -3.4582e9 ┆ 143198.0   ┆ 2018-10-1 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆           ┆            ┆ 7         │
│ 2018-11-06 ┆ 1.192369 ┆ 1.192369 ┆ 1.192369 ┆ … ┆ -60216.0  ┆ -2.0172e9 ┆ 106674.0   ┆ 2018-11-0 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆           ┆            ┆ 6         │
│ 2019-01-02 ┆ 1.064124 ┆ 1.064124 ┆ 1.064124 ┆ … ┆ -53420.0  ┆ -1.5305e9 ┆ 90772.0    ┆ 2019-01-0 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆           ┆            ┆ 2         │
│ 2019-05-15 ┆ 1.083428 ┆ 1.083428 ┆ 1.083428 ┆ … ┆ -73426.0  ┆ -2.1719e9 ┆ 99690.0    ┆ 2019-05-1 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆           ┆            ┆ 5         │
└────────────┴──────────┴──────────┴──────────┴───┴───────────┴───────────┴────────────┴───────────┘

SF has data out of the trading hours:

shape: (785, 9)
┌─────────────┬──────────┬──────────┬──────────┬───┬────────┬────────────┬────────────┬────────────┐
│ Time        ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μs ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64        ┆ ---        ┆ date       │
│ ]           ┆          ┆          ┆          ┆   ┆        ┆            ┆ f64        ┆            │
╞═════════════╪══════════╪══════════╪══════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 2014-08-11  ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 440.0  ┆ 1.26896e7  ┆ 31126.0    ┆ 2014-08-11 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2014-08-12  ┆ 1.007282 ┆ 1.007282 ┆ 1.007282 ┆ … ┆ 122.0  ┆ 3.5441e6   ┆ 33754.0    ┆ 2014-08-12 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2014-08-13  ┆ 1.026352 ┆ 1.026352 ┆ 1.026352 ┆ … ┆ 54.0   ┆ 1.5984e6   ┆ 46600.0    ┆ 2014-08-13 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2014-08-14  ┆ 1.026006 ┆ 1.026006 ┆ 1.026006 ┆ … ┆ 62.0   ┆ 1.83458e6  ┆ 46650.0    ┆ 2014-08-14 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2014-08-15  ┆ 0.995146 ┆ 0.995146 ┆ 0.995146 ┆ … ┆ 164.0  ┆ 4.7068e6   ┆ 35412.0    ┆ 2014-08-15 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ …           ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 2021-01-26  ┆ 1.328387 ┆ 1.328387 ┆ 1.328387 ┆ … ┆ 551.0  ┆ 3.938548e6 ┆ 140920.0   ┆ 2021-01-26 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-27  ┆ 1.303113 ┆ 1.303113 ┆ 1.303113 ┆ … ┆ 561.0  ┆ 3.933732e6 ┆ 133416.0   ┆ 2021-01-27 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-28  ┆ 1.300883 ┆ 1.300883 ┆ 1.300883 ┆ … ┆ 552.0  ┆ 3.864e6    ┆ 136140.0   ┆ 2021-01-28 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-29  ┆ 1.30906  ┆ 1.30906  ┆ 1.30906  ┆ … ┆ 531.0  ┆ 3.740364e6 ┆ 149427.0   ┆ 2021-01-29 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-02-01  ┆ 1.254051 ┆ 1.254051 ┆ 1.254051 ┆ … ┆ 761.0  ┆ 5.135228e6 ┆ 135072.0   ┆ 2021-02-01 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
└─────────────┴──────────┴──────────┴──────────┴───┴────────┴────────────┴────────────┴────────────┘

shape: (6_481, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2014-08-26 ┆ 0.996879 ┆ 0.996879 ┆ 0.996879 ┆ … ┆ 8          ┆ 2         ┆ heise     ┆ CZCE      │
│ 10:56:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2014-08-26 ┆ 0.996879 ┆ 0.996879 ┆ 0.996879 ┆ … ┆ 8          ┆ 2         ┆ heise     ┆ CZCE      │
│ 11:21:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2014-08-27 ┆ 0.999307 ┆ 0.999653 ┆ 0.999307 ┆ … ┆ 8          ┆ 3         ┆ heise     ┆ CZCE      │
│ 11:24:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2014-08-27 ┆ 0.99896  ┆ 0.999653 ┆ 0.99896  ┆ … ┆ 8          ┆ 3         ┆ heise     ┆ CZCE      │
│ 14:05:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2014-08-29 ┆ 1.000693 ┆ 1.000693 ┆ 1.000693 ┆ … ┆ 8          ┆ 7         ┆ heise     ┆ CZCE      │
│ 11:21:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-04-09 ┆ 1.058333 ┆ 1.059094 ┆ 1.058333 ┆ … ┆ 4          ┆ 4         ┆ heise     ┆ CZCE      │
│ 14:03:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-04-09 ┆ 1.055667 ┆ 1.056048 ┆ 1.055667 ┆ … ┆ 4          ┆ 4         ┆ heise     ┆ CZCE      │
│ 14:32:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-09-29 ┆ 1.085657 ┆ 1.08604  ┆ 1.085657 ┆ … ┆ 9          ┆ 2         ┆ heise     ┆ CZCE      │
│ 14:21:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-09-30 ┆ 1.079915 ┆ 1.079915 ┆ 1.079915 ┆ … ┆ 9          ┆ 3         ┆ heise     ┆ CZCE      │
│ 13:42:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-09-30 ┆ 1.078766 ┆ 1.078766 ┆ 1.078766 ┆ … ┆ 9          ┆ 3         ┆ heise     ┆ CZCE      │
│ 14:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

AU has 0/957488 rows containing None.
AU has bad data:

shape: (16, 9)
┌────────────┬──────────┬──────────┬──────────┬───┬───────────┬────────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume    ┆ Amount     ┆ Open      ┆ TradingDa │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---        ┆ Interest  ┆ y         │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64       ┆ f64        ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆           ┆            ┆ f64       ┆ date      │
╞════════════╪══════════╪══════════╪══════════╪═══╪═══════════╪════════════╪═══════════╪═══════════╡
│ 2017-07-03 ┆ 0.979875 ┆ 0.979875 ┆ 0.979875 ┆ … ┆ -141836.0 ┆ -3.9026e10 ┆ 343268.0  ┆ 2017-07-0 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 4         │
│ 2017-07-12 ┆ 0.976648 ┆ 0.976648 ┆ 0.976648 ┆ … ┆ -155942.0 ┆ -4.2221e10 ┆ 348734.0  ┆ 2017-07-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 3         │
│ 2017-07-21 ┆ 0.992247 ┆ 0.992247 ┆ 0.992247 ┆ … ┆ -173414.0 ┆ -4.7683e10 ┆ 349822.0  ┆ 2017-07-2 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 2         │
│ 2017-07-25 ┆ 0.990095 ┆ 0.990095 ┆ 0.990095 ┆ … ┆ -98674.0  ┆ -2.7299e10 ┆ 346382.0  ┆ 2017-07-2 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 6         │
│ 2017-07-27 ┆ 0.99655  ┆ 0.99655  ┆ 0.99655  ┆ … ┆ -164010.0 ┆ -4.5390e10 ┆ 342964.0  ┆ 2017-07-2 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 8         │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …         ┆ …          ┆ …         ┆ …         │
│ 2017-09-26 ┆ 1.004619 ┆ 1.004619 ┆ 1.004619 ┆ … ┆ -208700.0 ┆ -5.8568e10 ┆ 298414.0  ┆ 2017-09-2 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 7         │
│ 2017-10-09 ┆ 0.991171 ┆ 0.991171 ┆ 0.991171 ┆ … ┆ -98690.0  ┆ -2.7476e10 ┆ 286906.0  ┆ 2017-10-0 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 9         │
│ 2017-10-10 ┆ 0.992068 ┆ 0.992068 ┆ 0.992068 ┆ … ┆ -89302.0  ┆ -2.4717e10 ┆ 298072.0  ┆ 2017-10-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 1         │
│ 2017-10-12 ┆ 0.992426 ┆ 0.992426 ┆ 0.992426 ┆ … ┆ -106506.0 ┆ -2.9464e10 ┆ 301240.0  ┆ 2017-10-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 3         │
│ 2017-10-18 ┆ 0.989558 ┆ 0.989558 ┆ 0.989558 ┆ … ┆ -109216.0 ┆ -3.0207e10 ┆ 278218.0  ┆ 2017-10-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 9         │
└────────────┴──────────┴──────────┴──────────┴───┴───────────┴────────────┴───────────┴───────────┘

AU has data out of the trading hours:

shape: (3_207, 9)
┌─────────────┬──────────┬──────────┬──────────┬───┬────────┬────────────┬────────────┬────────────┐
│ Time        ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μs ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64        ┆ ---        ┆ date       │
│ ]           ┆          ┆          ┆          ┆   ┆        ┆            ┆ f64        ┆            │
╞═════════════╪══════════╪══════════╪══════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 2013-09-16  ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 170.0  ┆ 4.454e7    ┆ 126110.0   ┆ 2013-09-17 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-17  ┆ 1.001336 ┆ 1.001336 ┆ 1.001336 ┆ … ┆ 8.0    ┆ 2.0988e6   ┆ 127714.0   ┆ 2013-09-17 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-17  ┆ 1.000763 ┆ 1.000763 ┆ 1.000763 ┆ … ┆ 100.0  ┆ 2.622e7    ┆ 127784.0   ┆ 2013-09-18 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-18  ┆ 0.993893 ┆ 0.993893 ┆ 0.993893 ┆ … ┆ 2.0    ┆ 520800.0   ┆ 116440.0   ┆ 2013-09-18 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-23  ┆ 1.007824 ┆ 1.007824 ┆ 1.007824 ┆ … ┆ 898.0  ┆ 2.371169e8 ┆ 116778.0   ┆ 2013-09-23 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ …           ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 2020-05-19  ┆ 1.319846 ┆ 1.319846 ┆ 1.319846 ┆ … ┆ 1.0    ┆ 395400.0   ┆ 174923.0   ┆ 2020-05-19 │
│ 11:30:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-05-19  ┆ 1.316841 ┆ 1.316841 ┆ 1.316841 ┆ … ┆ 0.0    ┆ 0.0        ┆ 176053.0   ┆ 2020-05-19 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-05-20  ┆ 1.327723 ┆ 1.327723 ┆ 1.327723 ┆ … ┆ 2.0    ┆ 795520.0   ┆ 179760.0   ┆ 2020-05-20 │
│ 02:30:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-05-20  ┆ 1.331862 ┆ 1.331862 ┆ 1.331862 ┆ … ┆ 1.0    ┆ 399000.0   ┆ 183126.0   ┆ 2020-05-20 │
│ 10:15:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-05-20  ┆ 1.330928 ┆ 1.330928 ┆ 1.330928 ┆ … ┆ 5.0    ┆ 1.9936e6   ┆ 184790.0   ┆ 2020-05-20 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
└─────────────┴──────────┴──────────┴──────────┴───┴────────┴────────────┴────────────┴────────────┘

shape: (355, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2013-11-04 ┆ 0.992748 ┆ 0.992748 ┆ 0.992748 ┆ … ┆ 11         ┆ 1         ┆ guijinshu ┆ SHFE      │
│ 14:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2013-11-07 ┆ 0.99313  ┆ 0.993321 ┆ 0.99313  ┆ … ┆ 11         ┆ 4         ┆ guijinshu ┆ SHFE      │
│ 09:57:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2013-12-26 ┆ 0.918708 ┆ 0.918708 ┆ 0.918708 ┆ … ┆ 12         ┆ 4         ┆ guijinshu ┆ SHFE      │
│ 01:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2013-12-26 ┆ 0.918899 ┆ 0.918899 ┆ 0.918708 ┆ … ┆ 12         ┆ 4         ┆ guijinshu ┆ SHFE      │
│ 01:37:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2013-12-26 ┆ 0.918518 ┆ 0.918518 ┆ 0.918518 ┆ … ┆ 12         ┆ 4         ┆ guijinshu ┆ SHFE      │
│ 01:49:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-01-21 ┆ 1.169073 ┆ 1.169073 ┆ 1.169073 ┆ … ┆ 1          ┆ 2         ┆ guijinshu ┆ SHFE      │
│ 02:08:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-01-21 ┆ 1.169073 ┆ 1.16914  ┆ 1.169073 ┆ … ┆ 1          ┆ 2         ┆ guijinshu ┆ SHFE      │
│ 02:11:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-01-21 ┆ 1.178998 ┆ 1.179065 ┆ 1.178663 ┆ … ┆ 1          ┆ 2         ┆ guijinshu ┆ SHFE      │
│ 10:43:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-01-22 ┆ 1.171554 ┆ 1.171554 ┆ 1.171353 ┆ … ┆ 1          ┆ 3         ┆ guijinshu ┆ SHFE      │
│ 01:28:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-02-20 ┆ 1.228556 ┆ 1.228623 ┆ 1.228556 ┆ … ┆ 2          ┆ 4         ┆ guijinshu ┆ SHFE      │
│ 10:47:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

RR has 0/94882 rows containing None.
RR has data out of the trading hours:

shape: (195, 9)
┌─────────────────┬──────────┬──────────┬──────────┬───┬────────┬──────────┬──────────┬────────────┐
│ Time            ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount   ┆ Open     ┆ TradingDay │
│ ---             ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---      ┆ Interest ┆ ---        │
│ datetime[μs]    ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64      ┆ ---      ┆ date       │
│                 ┆          ┆          ┆          ┆   ┆        ┆          ┆ f64      ┆            │
╞═════════════════╪══════════╪══════════╪══════════╪═══╪════════╪══════════╪══════════╪════════════╡
│ 2019-08-16      ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 24.0   ┆ 885600.0 ┆ 28674.0  ┆ 2019-08-17 │
│ 20:59:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2019-08-19      ┆ 0.995393 ┆ 0.995393 ┆ 0.995393 ┆ … ┆ 4.0    ┆ 146920.0 ┆ 25730.0  ┆ 2019-08-19 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2019-08-19      ┆ 0.997019 ┆ 0.997019 ┆ 0.997019 ┆ … ┆ 20.0   ┆ 735800.0 ┆ 25738.0  ┆ 2019-08-20 │
│ 20:59:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2019-08-20      ┆ 0.992412 ┆ 0.992412 ┆ 0.992412 ┆ … ┆ 0.0    ┆ 0.0      ┆ 24242.0  ┆ 2019-08-20 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2019-08-20      ┆ 0.992954 ┆ 0.992954 ┆ 0.992954 ┆ … ┆ 4.0    ┆ 146560.0 ┆ 24244.0  ┆ 2019-08-21 │
│ 20:59:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ …               ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …        ┆ …        ┆ …          │
│ 2020-05-19      ┆ 0.872865 ┆ 0.872865 ┆ 0.872865 ┆ … ┆ 0.0    ┆ 0.0      ┆ 24134.0  ┆ 2020-05-19 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-05-20      ┆ 0.876172 ┆ 0.876172 ┆ 0.876172 ┆ … ┆ 0.0    ┆ 0.0      ┆ 25034.0  ┆ 2020-05-20 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-05-21      ┆ 0.873374 ┆ 0.873374 ┆ 0.873374 ┆ … ┆ 0.0    ┆ 0.0      ┆ 24644.0  ┆ 2020-05-21 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-05-22      ┆ 0.865487 ┆ 0.865487 ┆ 0.865487 ┆ … ┆ 0.0    ┆ 0.0      ┆ 24147.0  ┆ 2020-05-22 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
│ 2020-05-25      ┆ 0.867523 ┆ 0.867523 ┆ 0.867523 ┆ … ┆ 0.0    ┆ 0.0      ┆ 23774.0  ┆ 2020-05-25 │
│ 15:00:00        ┆          ┆          ┆          ┆   ┆        ┆          ┆          ┆            │
└─────────────────┴──────────┴──────────┴──────────┴───┴────────┴──────────┴──────────┴────────────┘

shape: (3_455, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2019-08-20 ┆ 0.99458  ┆ 0.99458  ┆ 0.994309 ┆ … ┆ 8          ┆ 3         ┆ nongfucha ┆ DCE       │
│ 22:35:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-08-21 ┆ 0.99458  ┆ 0.99458  ┆ 0.99458  ┆ … ┆ 8          ┆ 3         ┆ nongfucha ┆ DCE       │
│ 14:12:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-08-21 ┆ 0.99458  ┆ 0.99458  ┆ 0.994309 ┆ … ┆ 8          ┆ 3         ┆ nongfucha ┆ DCE       │
│ 14:14:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-08-21 ┆ 0.99458  ┆ 0.99458  ┆ 0.99458  ┆ … ┆ 8          ┆ 3         ┆ nongfucha ┆ DCE       │
│ 14:18:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-08-23 ┆ 0.984824 ┆ 0.984824 ┆ 0.984824 ┆ … ┆ 8          ┆ 7         ┆ nongfucha ┆ DCE       │
│ 09:31:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-05-25 ┆ 0.867268 ┆ 0.867268 ┆ 0.867268 ┆ … ┆ 5          ┆ 1         ┆ nongfucha ┆ DCE       │
│ 14:37:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-05-25 ┆ 0.867268 ┆ 0.867268 ┆ 0.867268 ┆ … ┆ 5          ┆ 1         ┆ nongfucha ┆ DCE       │
│ 14:40:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-05-25 ┆ 0.867014 ┆ 0.867014 ┆ 0.867014 ┆ … ┆ 5          ┆ 1         ┆ nongfucha ┆ DCE       │
│ 14:44:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-05-25 ┆ 0.867268 ┆ 0.867268 ┆ 0.867014 ┆ … ┆ 5          ┆ 1         ┆ nongfucha ┆ DCE       │
│ 14:46:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-05-25 ┆ 0.867268 ┆ 0.867268 ┆ 0.867268 ┆ … ┆ 5          ┆ 1         ┆ nongfucha ┆ DCE       │
│ 14:49:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

C has 0/450961 rows containing None.
C has data out of the trading hours:

shape: (3_084, 9)
┌────────────────┬──────────┬──────────┬──────────┬───┬────────┬───────────┬──────────┬────────────┐
│ Time           ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount    ┆ Open     ┆ TradingDay │
│ ---            ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---       ┆ Interest ┆ ---        │
│ datetime[μs]   ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64       ┆ ---      ┆ date       │
│                ┆          ┆          ┆          ┆   ┆        ┆           ┆ f64      ┆            │
╞════════════════╪══════════╪══════════╪══════════╪═══╪════════╪═══════════╪══════════╪════════════╡
│ 2013-09-17     ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 70.0   ┆ 1.6268e6  ┆ 334962.0 ┆ 2013-09-17 │
│ 08:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2013-09-17     ┆ 1.003873 ┆ 1.003873 ┆ 1.003873 ┆ … ┆ 0.0    ┆ 0.0       ┆ 331266.0 ┆ 2013-09-17 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2013-09-18     ┆ 1.003442 ┆ 1.003442 ┆ 1.003442 ┆ … ┆ 24.0   ┆ 559680.0  ┆ 331284.0 ┆ 2013-09-18 │
│ 08:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2013-09-18     ┆ 1.004733 ┆ 1.004733 ┆ 1.004733 ┆ … ┆ 2.0    ┆ 46700.0   ┆ 333928.0 ┆ 2013-09-18 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2013-09-23     ┆ 1.003442 ┆ 1.003442 ┆ 1.003442 ┆ … ┆ 106.0  ┆ 2.47192e6 ┆ 333886.0 ┆ 2013-09-23 │
│ 08:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ …              ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …         ┆ …        ┆ …          │
│ 2020-04-23     ┆ 1.041209 ┆ 1.041209 ┆ 1.041209 ┆ … ┆ 6.0    ┆ 124730.0  ┆ 863729.0 ┆ 2020-04-23 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-04-24     ┆ 1.04171  ┆ 1.04171  ┆ 1.04171  ┆ … ┆ 5.0    ┆ 104050.0  ┆ 872136.0 ┆ 2020-04-24 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-04-27     ┆ 1.051732 ┆ 1.051732 ┆ 1.051732 ┆ … ┆ 1.0    ┆ 20990.0   ┆ 908822.0 ┆ 2020-04-27 │
│ 10:15:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-04-27     ┆ 1.051231 ┆ 1.051231 ┆ 1.051231 ┆ … ┆ 0.0    ┆ 0.0       ┆ 908904.0 ┆ 2020-04-27 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-04-28     ┆ 1.050228 ┆ 1.050228 ┆ 1.050228 ┆ … ┆ 0.0    ┆ 0.0       ┆ 901454.0 ┆ 2020-04-28 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
└────────────────┴──────────┴──────────┴──────────┴───┴────────┴───────────┴──────────┴────────────┘

shape: (178, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2013-09-26 ┆ 1.002582 ┆ 1.002582 ┆ 1.002582 ┆ … ┆ 9          ┆ 4         ┆ nongfucha ┆ DCE       │
│ 10:58:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2013-10-09 ┆ 1.0      ┆ 1.0      ┆ 0.99957  ┆ … ┆ 10         ┆ 3         ┆ nongfucha ┆ DCE       │
│ 11:17:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2013-10-09 ┆ 0.99957  ┆ 0.99957  ┆ 0.99957  ┆ … ┆ 10         ┆ 3         ┆ nongfucha ┆ DCE       │
│ 11:23:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2013-10-16 ┆ 1.009024 ┆ 1.009024 ┆ 1.009024 ┆ … ┆ 10         ┆ 3         ┆ nongfucha ┆ DCE       │
│ 11:07:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2013-10-16 ┆ 1.008165 ┆ 1.008595 ┆ 1.008165 ┆ … ┆ 10         ┆ 3         ┆ nongfucha ┆ DCE       │
│ 14:11:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2018-04-18 ┆ 1.050176 ┆ 1.050176 ┆ 1.050176 ┆ … ┆ 4          ┆ 3         ┆ nongfucha ┆ DCE       │
│ 10:43:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2018-04-18 ┆ 1.049571 ┆ 1.050176 ┆ 1.049571 ┆ … ┆ 4          ┆ 3         ┆ nongfucha ┆ DCE       │
│ 14:41:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2018-04-18 ┆ 1.049571 ┆ 1.050176 ┆ 1.049571 ┆ … ┆ 4          ┆ 3         ┆ nongfucha ┆ DCE       │
│ 14:46:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-10-10 ┆ 0.981042 ┆ 0.981042 ┆ 0.979974 ┆ … ┆ 10         ┆ 7         ┆ nongfucha ┆ DCE       │
│ 21:04:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-12-03 ┆ 0.977304 ┆ 0.977304 ┆ 0.97677  ┆ … ┆ 12         ┆ 3         ┆ nongfucha ┆ DCE       │
│ 22:33:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

FB has 20272/188819 rows containing None.
FB has data out of the trading hours:

shape: (1_396, 9)
┌────────────────┬──────────┬──────────┬──────────┬───┬────────┬───────────┬──────────┬────────────┐
│ Time           ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount    ┆ Open     ┆ TradingDay │
│ ---            ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---       ┆ Interest ┆ ---        │
│ datetime[μs]   ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64       ┆ ---      ┆ date       │
│                ┆          ┆          ┆          ┆   ┆        ┆           ┆ f64      ┆            │
╞════════════════╪══════════╪══════════╪══════════╪═══╪════════╪═══════════╪══════════╪════════════╡
│ 2013-12-09     ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 160.0  ┆ 5.72e6    ┆ 10600.0  ┆ 2013-12-09 │
│ 08:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2013-12-09     ┆ 1.037063 ┆ 1.037063 ┆ 1.037063 ┆ … ┆ 142.0  ┆ 5.26475e6 ┆ 27074.0  ┆ 2013-12-09 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2013-12-10     ┆ 1.034266 ┆ 1.034266 ┆ 1.034266 ┆ … ┆ 232.0  ┆ 8.5782e6  ┆ 27084.0  ┆ 2013-12-10 │
│ 08:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2013-12-10     ┆ 1.015385 ┆ 1.015385 ┆ 1.015385 ┆ … ┆ 2.0    ┆ 72600.0   ┆ 37456.0  ┆ 2013-12-10 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2013-12-11     ┆ 1.015385 ┆ 1.015385 ┆ 1.015385 ┆ … ┆ 274.0  ┆ 9.9462e6  ┆ 37494.0  ┆ 2013-12-11 │
│ 08:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ …              ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …         ┆ …        ┆ …          │
│ 2020-03-16     ┆ 2.231944 ┆ 2.231944 ┆ 2.231944 ┆ … ┆ 0.0    ┆ 0.0       ┆ 4462.0   ┆ 2020-03-16 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-03-17     ┆ 2.257839 ┆ 2.257839 ┆ 2.257839 ┆ … ┆ 2.0    ┆ 27030.0   ┆ 4062.0   ┆ 2020-03-17 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-03-18     ┆ 2.237791 ┆ 2.237791 ┆ 2.237791 ┆ … ┆ 0.0    ┆ 0.0       ┆ 4544.0   ┆ 2020-03-18 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-03-19     ┆ 2.236956 ┆ 2.236956 ┆ 2.236956 ┆ … ┆ 0.0    ┆ 0.0       ┆ 4628.0   ┆ 2020-03-19 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-03-20     ┆ 2.233615 ┆ 2.233615 ┆ 2.233615 ┆ … ┆ 0.0    ┆ 0.0       ┆ 3725.0   ┆ 2020-03-20 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
└────────────────┴──────────┴──────────┴──────────┴───┴────────┴───────────┴──────────┴────────────┘

shape: (7_145, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2014-07-30 ┆ 0.847926 ┆ 0.847926 ┆ 0.847926 ┆ … ┆ 7          ┆ 3         ┆ qinggongj ┆ DCE       │
│ 13:47:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ iancai    ┆           │
│ 2014-08-25 ┆ 0.878722 ┆ 0.878722 ┆ 0.878722 ┆ … ┆ 8          ┆ 1         ┆ qinggongj ┆ DCE       │
│ 13:56:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ iancai    ┆           │
│ 2014-08-25 ┆ 0.878722 ┆ 0.878722 ┆ 0.878722 ┆ … ┆ 8          ┆ 1         ┆ qinggongj ┆ DCE       │
│ 13:59:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ iancai    ┆           │
│ 2014-08-25 ┆ 0.879407 ┆ 0.879407 ┆ 0.879407 ┆ … ┆ 8          ┆ 1         ┆ qinggongj ┆ DCE       │
│ 14:20:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ iancai    ┆           │
│ 2014-08-26 ┆ 0.883513 ┆ 0.884197 ┆ 0.883513 ┆ … ┆ 8          ┆ 2         ┆ qinggongj ┆ DCE       │
│ 10:38:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ iancai    ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-03-23 ┆ 2.201873 ┆ 2.201873 ┆ 2.199367 ┆ … ┆ 3          ┆ 1         ┆ qinggongj ┆ DCE       │
│ 10:59:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ iancai    ┆           │
│ 2020-03-23 ┆ 2.199367 ┆ 2.199367 ┆ 2.199367 ┆ … ┆ 3          ┆ 1         ┆ qinggongj ┆ DCE       │
│ 11:01:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ iancai    ┆           │
│ 2020-03-23 ┆ 2.205214 ┆ 2.205214 ┆ 2.204379 ┆ … ┆ 3          ┆ 1         ┆ qinggongj ┆ DCE       │
│ 11:15:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ iancai    ┆           │
│ 2020-03-23 ┆ 2.203544 ┆ 2.203544 ┆ 2.203544 ┆ … ┆ 3          ┆ 1         ┆ qinggongj ┆ DCE       │
│ 11:17:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ iancai    ┆           │
│ 2020-03-23 ┆ 2.203544 ┆ 2.203544 ┆ 2.203544 ┆ … ┆ 3          ┆ 1         ┆ qinggongj ┆ DCE       │
│ 11:19:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ iancai    ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

EG has 0/162254 rows containing None.
EG has data out of the trading hours:

shape: (606, 9)
┌─────────────┬──────────┬──────────┬──────────┬───┬────────┬────────────┬────────────┬────────────┐
│ Time        ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μs ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64        ┆ ---        ┆ date       │
│ ]           ┆          ┆          ┆          ┆   ┆        ┆            ┆ f64        ┆            │
╞═════════════╪══════════╪══════════╪══════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 2018-12-11  ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 316.0  ┆ 1.775288e7 ┆ 69702.0    ┆ 2018-12-11 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2018-12-11  ┆ 0.986294 ┆ 0.986294 ┆ 0.986294 ┆ … ┆ 22.0   ┆ 1.2186e6   ┆ 83122.0    ┆ 2018-12-11 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2018-12-12  ┆ 0.993236 ┆ 0.993236 ┆ 0.993236 ┆ … ┆ 694.0  ┆ 3.87252e7  ┆ 83708.0    ┆ 2018-12-12 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2018-12-12  ┆ 0.986828 ┆ 0.986828 ┆ 0.986828 ┆ … ┆ 2.0    ┆ 110880.0   ┆ 88512.0    ┆ 2018-12-12 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2018-12-13  ┆ 0.982378 ┆ 0.982378 ┆ 0.982378 ┆ … ┆ 252.0  ┆ 1.390788e7 ┆ 88734.0    ┆ 2018-12-13 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ …           ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 2020-05-06  ┆ 0.63793  ┆ 0.63793  ┆ 0.637757 ┆ … ┆ 7.0    ┆ 258810.0   ┆ 190306.0   ┆ 2020-05-06 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-05-07  ┆ 0.638102 ┆ 0.638102 ┆ 0.638102 ┆ … ┆ 1.0    ┆ 36990.0    ┆ 200149.0   ┆ 2020-05-07 │
│ 10:15:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-05-07  ┆ 0.639137 ┆ 0.639137 ┆ 0.639137 ┆ … ┆ 12.0   ┆ 444600.0   ┆ 197548.0   ┆ 2020-05-07 │
│ 11:30:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-05-07  ┆ 0.63655  ┆ 0.63655  ┆ 0.63655  ┆ … ┆ 0.0    ┆ 0.0        ┆ 193785.0   ┆ 2020-05-07 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-05-08  ┆ 0.629994 ┆ 0.629994 ┆ 0.629994 ┆ … ┆ 96.0   ┆ 3.50696e6  ┆ 192919.0   ┆ 2020-05-08 │
│ 11:30:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
└─────────────┴──────────┴──────────┴──────────┴───┴────────┴────────────┴────────────┴────────────┘

shape: (41, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2019-04-23 ┆ 0.840513 ┆ 0.840691 ┆ 0.839267 ┆ … ┆ 4          ┆ 2         ┆ nengyuanh ┆ DCE       │
│ 10:11:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-06-28 ┆ 0.765491 ┆ 0.765491 ┆ 0.764452 ┆ … ┆ 6          ┆ 7         ┆ nengyuanh ┆ DCE       │
│ 11:02:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-09-16 ┆ 0.866285 ┆ 0.866285 ┆ 0.866285 ┆ … ┆ 9          ┆ 1         ┆ nengyuanh ┆ DCE       │
│ 14:04:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-09-16 ┆ 0.866285 ┆ 0.866285 ┆ 0.866285 ┆ … ┆ 9          ┆ 1         ┆ nengyuanh ┆ DCE       │
│ 14:22:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-09-16 ┆ 0.866285 ┆ 0.866285 ┆ 0.866285 ┆ … ┆ 9          ┆ 1         ┆ nengyuanh ┆ DCE       │
│ 14:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-03-19 ┆ 0.651529 ┆ 0.651529 ┆ 0.651529 ┆ … ┆ 3          ┆ 4         ┆ nengyuanh ┆ DCE       │
│ 11:12:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-19 ┆ 0.651529 ┆ 0.651529 ┆ 0.651529 ┆ … ┆ 3          ┆ 4         ┆ nengyuanh ┆ DCE       │
│ 11:15:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-19 ┆ 0.651529 ┆ 0.651529 ┆ 0.651529 ┆ … ┆ 3          ┆ 4         ┆ nengyuanh ┆ DCE       │
│ 11:28:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-19 ┆ 0.651529 ┆ 0.651529 ┆ 0.651529 ┆ … ┆ 3          ┆ 4         ┆ nengyuanh ┆ DCE       │
│ 13:38:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-19 ┆ 0.651529 ┆ 0.651529 ┆ 0.651529 ┆ … ┆ 3          ┆ 4         ┆ nengyuanh ┆ DCE       │
│ 13:47:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

L has 0/451005 rows containing None.
L has data out of the trading hours:

shape: (3_087, 9)
┌─────────────┬──────────┬──────────┬──────────┬───┬────────┬────────────┬────────────┬────────────┐
│ Time        ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μs ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64        ┆ ---        ┆ date       │
│ ]           ┆          ┆          ┆          ┆   ┆        ┆            ┆ f64        ┆            │
╞═════════════╪══════════╪══════════╪══════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 2013-09-17  ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 416.0  ┆ 2.23392e7  ┆ 387360.0   ┆ 2013-09-17 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-17  ┆ 0.999069 ┆ 0.999069 ┆ 0.999069 ┆ … ┆ 14.0   ┆ 751100.0   ┆ 389600.0   ┆ 2013-09-17 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-18  ┆ 0.99581  ┆ 0.99581  ┆ 0.99581  ┆ … ┆ 454.0  ┆ 2.427765e7 ┆ 389564.0   ┆ 2013-09-18 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-18  ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 0.0    ┆ 0.0        ┆ 369436.0   ┆ 2013-09-18 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-23  ┆ 0.996276 ┆ 0.996276 ┆ 0.996276 ┆ … ┆ 1568.0 ┆ 8.3888e7   ┆ 369876.0   ┆ 2013-09-23 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ …           ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 2020-04-23  ┆ 1.045427 ┆ 1.045427 ┆ 1.045427 ┆ … ┆ 0.0    ┆ 0.0        ┆ 351940.0   ┆ 2020-04-23 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-04-24  ┆ 1.047141 ┆ 1.047141 ┆ 1.047141 ┆ … ┆ 1.0    ┆ 30550.0    ┆ 353346.0   ┆ 2020-04-24 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-04-27  ┆ 1.076276 ┆ 1.076276 ┆ 1.076276 ┆ … ┆ 14.0   ┆ 439350.0   ┆ 369539.0   ┆ 2020-04-27 │
│ 10:15:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-04-27  ┆ 1.070277 ┆ 1.070277 ┆ 1.070277 ┆ … ┆ 2.0    ┆ 62425.0    ┆ 366460.0   ┆ 2020-04-27 │
│ 11:30:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-04-27  ┆ 1.06685  ┆ 1.06685  ┆ 1.06685  ┆ … ┆ 5.0    ┆ 155725.0   ┆ 366881.0   ┆ 2020-04-27 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
└─────────────┴──────────┴──────────┴──────────┴───┴────────┴────────────┴────────────┴────────────┘

shape: (25, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2019-10-10 ┆ 1.259527 ┆ 1.261229 ┆ 1.258676 ┆ … ┆ 10         ┆ 7         ┆ nengyuanh ┆ DCE       │
│ 21:04:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-11-26 ┆ 1.230592 ┆ 1.230592 ┆ 1.229741 ┆ … ┆ 11         ┆ 3         ┆ nengyuanh ┆ DCE       │
│ 22:30:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-12-05 ┆ 1.233145 ┆ 1.233145 ┆ 1.232294 ┆ … ┆ 12         ┆ 7         ┆ nengyuanh ┆ DCE       │
│ 22:33:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-12-06 ┆ 1.234847 ┆ 1.235698 ┆ 1.233996 ┆ … ┆ 12         ┆ 7         ┆ nengyuanh ┆ DCE       │
│ 11:02:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-02-03 ┆ 1.144825 ┆ 1.144825 ┆ 1.144825 ┆ … ┆ 2          ┆ 1         ┆ nengyuanh ┆ DCE       │
│ 14:04:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-03-09 ┆ 1.123593 ┆ 1.123593 ┆ 1.123593 ┆ … ┆ 3          ┆ 1         ┆ nengyuanh ┆ DCE       │
│ 14:42:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-09 ┆ 1.123593 ┆ 1.123593 ┆ 1.123593 ┆ … ┆ 3          ┆ 1         ┆ nengyuanh ┆ DCE       │
│ 14:45:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-09 ┆ 1.123593 ┆ 1.123593 ┆ 1.123593 ┆ … ┆ 3          ┆ 1         ┆ nengyuanh ┆ DCE       │
│ 14:49:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-19 ┆ 1.054802 ┆ 1.054802 ┆ 1.054802 ┆ … ┆ 3          ┆ 4         ┆ nengyuanh ┆ DCE       │
│ 11:07:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-03-19 ┆ 1.054802 ┆ 1.054802 ┆ 1.054802 ┆ … ┆ 3          ┆ 4         ┆ nengyuanh ┆ DCE       │
│ 13:40:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

B has 0/278003 rows containing None.
B has data out of the trading hours:

shape: (1_386, 9)
┌───────────────┬──────────┬──────────┬──────────┬───┬────────┬────────┬──────────┬────────────┐
│ Time          ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount ┆ Open     ┆ TradingDay │
│ ---           ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---    ┆ Interest ┆ ---        │
│ datetime[μs]  ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64    ┆ ---      ┆ date       │
│               ┆          ┆          ┆          ┆   ┆        ┆        ┆ f64      ┆            │
╞═══════════════╪══════════╪══════════╪══════════╪═══╪════════╪════════╪══════════╪════════════╡
│ 2013-09-17    ┆ 1.001729 ┆ 1.001729 ┆ 1.001729 ┆ … ┆ 0.0    ┆ 0.0    ┆ 118.0    ┆ 2013-09-17 │
│ 15:00:00      ┆          ┆          ┆          ┆   ┆        ┆        ┆          ┆            │
│ 2013-09-18    ┆ 1.005435 ┆ 1.005435 ┆ 1.005435 ┆ … ┆ 0.0    ┆ 0.0    ┆ 118.0    ┆ 2013-09-18 │
│ 15:00:00      ┆          ┆          ┆          ┆   ┆        ┆        ┆          ┆            │
│ 2013-09-23    ┆ 1.007658 ┆ 1.007658 ┆ 1.007658 ┆ … ┆ 0.0    ┆ 0.0    ┆ 118.0    ┆ 2013-09-23 │
│ 15:00:00      ┆          ┆          ┆          ┆   ┆        ┆        ┆          ┆            │
│ 2013-09-24    ┆ 1.008893 ┆ 1.008893 ┆ 1.008893 ┆ … ┆ 0.0    ┆ 0.0    ┆ 120.0    ┆ 2013-09-24 │
│ 15:00:00      ┆          ┆          ┆          ┆   ┆        ┆        ┆          ┆            │
│ 2013-09-25    ┆ 1.009634 ┆ 1.009634 ┆ 1.009634 ┆ … ┆ 0.0    ┆ 0.0    ┆ 118.0    ┆ 2013-09-25 │
│ 15:00:00      ┆          ┆          ┆          ┆   ┆        ┆        ┆          ┆            │
│ …             ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …      ┆ …        ┆ …          │
│ 2020-04-09    ┆ 0.86245  ┆ 0.86245  ┆ 0.86245  ┆ … ┆ 0.0    ┆ 0.0    ┆ 12264.0  ┆ 2020-04-09 │
│ 15:00:00      ┆          ┆          ┆          ┆   ┆        ┆        ┆          ┆            │
│ 2020-04-10    ┆ 0.866301 ┆ 0.866301 ┆ 0.866301 ┆ … ┆ 0.0    ┆ 0.0    ┆ 10540.0  ┆ 2020-04-10 │
│ 15:00:00      ┆          ┆          ┆          ┆   ┆        ┆        ┆          ┆            │
│ 2020-04-13    ┆ 0.861624 ┆ 0.861624 ┆ 0.861624 ┆ … ┆ 0.0    ┆ 0.0    ┆ 9839.0   ┆ 2020-04-13 │
│ 15:00:00      ┆          ┆          ┆          ┆   ┆        ┆        ┆          ┆            │
│ 2020-04-14    ┆ 0.842092 ┆ 0.842092 ┆ 0.842092 ┆ … ┆ 0.0    ┆ 0.0    ┆ 7212.0   ┆ 2020-04-14 │
│ 15:00:00      ┆          ┆          ┆          ┆   ┆        ┆        ┆          ┆            │
│ 2020-04-15    ┆ 0.847594 ┆ 0.847594 ┆ 0.847594 ┆ … ┆ 0.0    ┆ 0.0    ┆ 7294.0   ┆ 2020-04-15 │
│ 15:00:00      ┆          ┆          ┆          ┆   ┆        ┆        ┆          ┆            │
└───────────────┴──────────┴──────────┴──────────┴───┴────────┴────────┴──────────┴────────────┘

shape: (5_643, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2013-09-17 ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 9          ┆ 2         ┆ nongfucha ┆ DCE       │
│ 09:05:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2013-09-17 ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 9          ┆ 2         ┆ nongfucha ┆ DCE       │
│ 09:09:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2013-09-17 ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 9          ┆ 2         ┆ nongfucha ┆ DCE       │
│ 09:21:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2013-09-17 ┆ 1.000494 ┆ 1.000494 ┆ 1.000494 ┆ … ┆ 9          ┆ 2         ┆ nongfucha ┆ DCE       │
│ 09:25:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2013-09-17 ┆ 1.000988 ┆ 1.000988 ┆ 1.000988 ┆ … ┆ 9          ┆ 2         ┆ nongfucha ┆ DCE       │
│ 10:01:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-03-09 ┆ 0.808529 ┆ 0.808529 ┆ 0.808529 ┆ … ┆ 3          ┆ 1         ┆ nongfucha ┆ DCE       │
│ 14:35:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-03-09 ┆ 0.808529 ┆ 0.808529 ┆ 0.808529 ┆ … ┆ 3          ┆ 1         ┆ nongfucha ┆ DCE       │
│ 14:42:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-03-11 ┆ 0.823935 ┆ 0.823935 ┆ 0.823935 ┆ … ┆ 3          ┆ 3         ┆ nongfucha ┆ DCE       │
│ 09:54:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-03-11 ┆ 0.82311  ┆ 0.82366  ┆ 0.82311  ┆ … ┆ 3          ┆ 3         ┆ nongfucha ┆ DCE       │
│ 11:08:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-03-23 ┆ 0.886934 ┆ 0.886934 ┆ 0.886934 ┆ … ┆ 3          ┆ 1         ┆ nongfucha ┆ DCE       │
│ 14:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

AG has 0/953079 rows containing None.
AG has bad data:

shape: (5, 9)
┌────────────┬──────────┬──────────┬──────────┬───┬───────────┬────────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume    ┆ Amount     ┆ Open      ┆ TradingDa │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---        ┆ Interest  ┆ y         │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64       ┆ f64        ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆           ┆            ┆ f64       ┆ date      │
╞════════════╪══════════╪══════════╪══════════╪═══╪═══════════╪════════════╪═══════════╪═══════════╡
│ 2017-07-03 ┆ 0.802818 ┆ 0.802818 ┆ 0.802818 ┆ … ┆ -328368.0 ┆ -1.9748e10 ┆ 656210.0  ┆ 2017-07-0 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 4         │
│ 2017-07-12 ┆ 0.775491 ┆ 0.775491 ┆ 0.775491 ┆ … ┆ -830196.0 ┆ -4.7122e10 ┆ 712582.0  ┆ 2017-07-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 3         │
│ 2017-07-21 ┆ 0.789458 ┆ 0.789458 ┆ 0.789458 ┆ … ┆ -523370.0 ┆ -3.0432e10 ┆ 649980.0  ┆ 2017-07-2 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 2         │
│ 2017-07-25 ┆ 0.785612 ┆ 0.785612 ┆ 0.785612 ┆ … ┆ -287166.0 ┆ -1.6737e10 ┆ 632786.0  ┆ 2017-07-2 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 6         │
│ 2017-07-27 ┆ 0.794317 ┆ 0.794317 ┆ 0.794317 ┆ … ┆ -498620.0 ┆ -2.9143e10 ┆ 626146.0  ┆ 2017-07-2 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 8         │
└────────────┴──────────┴──────────┴──────────┴───┴───────────┴────────────┴───────────┴───────────┘

AG has data out of the trading hours:

shape: (3_237, 9)
┌─────────────┬──────────┬──────────┬──────────┬───┬────────┬────────────┬────────────┬────────────┐
│ Time        ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μs ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64        ┆ ---        ┆ date       │
│ ]           ┆          ┆          ┆          ┆   ┆        ┆            ┆ f64        ┆            │
╞═════════════╪══════════╪══════════╪══════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 2013-09-16  ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 4068.0 ┆ 2.687931e8 ┆ 535368.0   ┆ 2013-09-17 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-17  ┆ 1.011351 ┆ 1.011351 ┆ 1.011351 ┆ … ┆ 218.0  ┆ 1.457103e7 ┆ 535920.0   ┆ 2013-09-17 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-17  ┆ 1.003859 ┆ 1.003859 ┆ 1.003859 ┆ … ┆ 4170.0 ┆ 2.765961e8 ┆ 537972.0   ┆ 2013-09-18 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-18  ┆ 1.003178 ┆ 1.003178 ┆ 1.003178 ┆ … ┆ 46.0   ┆ 3.04875e6  ┆ 472906.0   ┆ 2013-09-18 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-09-23  ┆ 0.998865 ┆ 0.998865 ┆ 0.998865 ┆ … ┆ 8290.0 ┆ 5.4714e8   ┆ 472760.0   ┆ 2013-09-23 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ …           ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 2020-04-15  ┆ 0.679224 ┆ 0.679224 ┆ 0.679224 ┆ … ┆ 20.0   ┆ 1.1124e6   ┆ 349754.0   ┆ 2020-04-15 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-04-16  ┆ 0.678858 ┆ 0.678858 ┆ 0.678858 ┆ … ┆ 40.0   ┆ 2.2236e6   ┆ 354548.0   ┆ 2020-04-16 │
│ 11:30:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-04-16  ┆ 0.692046 ┆ 0.692046 ┆ 0.692046 ┆ … ┆ 10.0   ┆ 566745.0   ┆ 352060.0   ┆ 2020-04-16 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-04-17  ┆ 0.679957 ┆ 0.679957 ┆ 0.679957 ┆ … ┆ 3.0    ┆ 167040.0   ┆ 354533.0   ┆ 2020-04-17 │
│ 10:15:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-04-17  ┆ 0.679041 ┆ 0.679041 ┆ 0.679041 ┆ … ┆ 2.0    ┆ 111210.0   ┆ 353668.0   ┆ 2020-04-17 │
│ 11:30:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
└─────────────┴──────────┴──────────┴──────────┴───┴────────┴────────────┴────────────┴────────────┘

shape: (59, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2013-11-04 ┆ 0.993417 ┆ 0.993644 ┆ 0.99319  ┆ … ┆ 11         ┆ 1         ┆ guijinshu ┆ SHFE      │
│ 14:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2013-11-29 ┆ 0.93916  ┆ 0.93916  ┆ 0.93916  ┆ … ┆ 12         ┆ 7         ┆ guijinshu ┆ SHFE      │
│ 01:49:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2014-09-23 ┆ 0.854713 ┆ 0.854713 ┆ 0.854713 ┆ … ┆ 9          ┆ 2         ┆ guijinshu ┆ SHFE      │
│ 09:43:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2014-12-26 ┆ 0.78047  ┆ 0.780698 ┆ 0.78047  ┆ … ┆ 12         ┆ 7         ┆ guijinshu ┆ SHFE      │
│ 01:36:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2015-05-18 ┆ 0.858861 ┆ 0.859084 ┆ 0.858861 ┆ … ┆ 5          ┆ 2         ┆ guijinshu ┆ SHFE      │
│ 21:25:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-03-17 ┆ 0.588184 ┆ 0.588184 ┆ 0.588184 ┆ … ┆ 3          ┆ 2         ┆ guijinshu ┆ SHFE      │
│ 11:26:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-03-17 ┆ 0.588184 ┆ 0.588184 ┆ 0.588184 ┆ … ┆ 3          ┆ 2         ┆ guijinshu ┆ SHFE      │
│ 13:42:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-03-17 ┆ 0.588184 ┆ 0.588184 ┆ 0.588184 ┆ … ┆ 3          ┆ 2         ┆ guijinshu ┆ SHFE      │
│ 14:22:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-03-24 ┆ 0.610899 ┆ 0.610899 ┆ 0.610899 ┆ … ┆ 3          ┆ 2         ┆ guijinshu ┆ SHFE      │
│ 10:11:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-03-24 ┆ 0.610899 ┆ 0.610899 ┆ 0.610899 ┆ … ┆ 3          ┆ 2         ┆ guijinshu ┆ SHFE      │
│ 10:38:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

A has 0/608553 rows containing None.
A has data out of the trading hours:

shape: (3_082, 9)
┌────────────────┬──────────┬──────────┬──────────┬───┬────────┬───────────┬──────────┬────────────┐
│ Time           ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount    ┆ Open     ┆ TradingDay │
│ ---            ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---       ┆ Interest ┆ ---        │
│ datetime[μs]   ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64       ┆ ---      ┆ date       │
│                ┆          ┆          ┆          ┆   ┆        ┆           ┆ f64      ┆            │
╞════════════════╪══════════╪══════════╪══════════╪═══╪════════╪═══════════╪══════════╪════════════╡
│ 2013-09-17     ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 52.0   ┆ 2.3556e6  ┆ 107122.0 ┆ 2013-09-17 │
│ 08:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2013-09-17     ┆ 1.006623 ┆ 1.006623 ┆ 1.006623 ┆ … ┆ 0.0    ┆ 0.0       ┆ 103444.0 ┆ 2013-09-17 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2013-09-18     ┆ 1.004415 ┆ 1.004415 ┆ 1.004415 ┆ … ┆ 30.0   ┆ 1.365e6   ┆ 103424.0 ┆ 2013-09-18 │
│ 08:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2013-09-18     ┆ 1.013024 ┆ 1.013024 ┆ 1.013024 ┆ … ┆ 0.0    ┆ 0.0       ┆ 100720.0 ┆ 2013-09-18 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2013-09-23     ┆ 1.008389 ┆ 1.008389 ┆ 1.008389 ┆ … ┆ 480.0  ┆ 2.19264e7 ┆ 100910.0 ┆ 2013-09-23 │
│ 08:59:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ …              ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …         ┆ …        ┆ …          │
│ 2020-05-21     ┆ 0.783311 ┆ 0.783491 ┆ 0.783311 ┆ … ┆ 6.0    ┆ 259870.0  ┆ 137646.0 ┆ 2020-05-21 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-05-22     ┆ 0.801758 ┆ 0.801758 ┆ 0.801758 ┆ … ┆ 8.0    ┆ 354640.0  ┆ 140658.0 ┆ 2020-05-22 │
│ 10:15:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-05-22     ┆ 0.798684 ┆ 0.798684 ┆ 0.798684 ┆ … ┆ 15.0   ┆ 662170.0  ┆ 134777.0 ┆ 2020-05-22 │
│ 11:30:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-05-22     ┆ 0.799407 ┆ 0.799407 ┆ 0.799407 ┆ … ┆ 3.0    ┆ 132600.0  ┆ 128856.0 ┆ 2020-05-22 │
│ 15:00:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-05-25     ┆ 0.801397 ┆ 0.801397 ┆ 0.801397 ┆ … ┆ 2.0    ┆ 88620.0   ┆ 123101.0 ┆ 2020-05-25 │
│ 10:15:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
└────────────────┴──────────┴──────────┴──────────┴───┴────────┴───────────┴──────────┴────────────┘

shape: (506, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2013-10-09 ┆ 1.025386 ┆ 1.025386 ┆ 1.025386 ┆ … ┆ 10         ┆ 3         ┆ nongfucha ┆ DCE       │
│ 11:27:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2013-10-14 ┆ 1.026711 ┆ 1.026711 ┆ 1.026711 ┆ … ┆ 10         ┆ 1         ┆ nongfucha ┆ DCE       │
│ 10:50:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2013-10-18 ┆ 1.025166 ┆ 1.025166 ┆ 1.025166 ┆ … ┆ 10         ┆ 7         ┆ nongfucha ┆ DCE       │
│ 13:45:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2013-12-11 ┆ 1.000718 ┆ 1.000718 ┆ 1.000718 ┆ … ┆ 12         ┆ 3         ┆ nongfucha ┆ DCE       │
│ 14:27:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2013-12-26 ┆ 1.004978 ┆ 1.004978 ┆ 1.004978 ┆ … ┆ 12         ┆ 4         ┆ nongfucha ┆ DCE       │
│ 11:12:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2019-12-02 ┆ 0.646987 ┆ 0.646987 ┆ 0.646987 ┆ … ┆ 12         ┆ 2         ┆ nongfucha ┆ DCE       │
│ 22:28:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-12-02 ┆ 0.646987 ┆ 0.646987 ┆ 0.646987 ┆ … ┆ 12         ┆ 2         ┆ nongfucha ┆ DCE       │
│ 22:53:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-12-05 ┆ 0.658083 ┆ 0.658083 ┆ 0.657892 ┆ … ┆ 12         ┆ 7         ┆ nongfucha ┆ DCE       │
│ 22:21:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-12-05 ┆ 0.657892 ┆ 0.658083 ┆ 0.657892 ┆ … ┆ 12         ┆ 7         ┆ nongfucha ┆ DCE       │
│ 22:33:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-12-06 ┆ 0.658657 ┆ 0.658657 ┆ 0.658466 ┆ … ┆ 12         ┆ 7         ┆ nongfucha ┆ DCE       │
│ 10:51:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

SM has 0/283578 rows containing None.
SM has bad data:

shape: (8, 9)
┌────────────┬──────────┬──────────┬──────────┬───┬───────────┬────────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume    ┆ Amount     ┆ Open      ┆ TradingDa │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---        ┆ Interest  ┆ y         │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64       ┆ f64        ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆           ┆            ┆ f64       ┆ date      │
╞════════════╪══════════╪══════════╪══════════╪═══╪═══════════╪════════════╪═══════════╪═══════════╡
│ 2018-01-12 ┆ 2.143446 ┆ 2.143446 ┆ 2.143446 ┆ … ┆ -127970.0 ┆ -4.5647e9  ┆ 77698.0   ┆ 2018-01-1 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 2         │
│ 2018-08-14 ┆ 2.7094   ┆ 2.7094   ┆ 2.7094   ┆ … ┆ -118192.0 ┆ -5.1804e9  ┆ 85186.0   ┆ 2018-08-1 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 4         │
│ 2018-09-25 ┆ 2.622147 ┆ 2.622147 ┆ 2.622147 ┆ … ┆ -190378.0 ┆ -8.1748e9  ┆ 160696.0  ┆ 2018-09-2 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 5         │
│ 2018-10-17 ┆ 2.654511 ┆ 2.654511 ┆ 2.654511 ┆ … ┆ -233946.0 ┆ -1.0170e10 ┆ 166564.0  ┆ 2018-10-1 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 7         │
│ 2018-11-06 ┆ 2.636192 ┆ 2.636192 ┆ 2.636192 ┆ … ┆ -108316.0 ┆ -4.6760e9  ┆ 167768.0  ┆ 2018-11-0 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 6         │
│ 2019-01-02 ┆ 2.5066   ┆ 2.5066   ┆ 2.5066   ┆ … ┆ -61702.0  ┆ -2.2484e9  ┆ 76952.0   ┆ 2019-01-0 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 2         │
│ 2019-01-08 ┆ 2.541681 ┆ 2.541681 ┆ 2.541681 ┆ … ┆ -59196.0  ┆ -2.1873e9  ┆ 82654.0   ┆ 2019-01-0 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 8         │
│ 2019-05-15 ┆ 2.543935 ┆ 2.543935 ┆ 2.543935 ┆ … ┆ -64906.0  ┆ -2.3399e9  ┆ 97986.0   ┆ 2019-05-1 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 5         │
└────────────┴──────────┴──────────┴──────────┴───┴───────────┴────────────┴───────────┴───────────┘

SM has data out of the trading hours:

shape: (916, 9)
┌─────────────┬──────────┬──────────┬──────────┬───┬────────┬────────────┬────────────┬────────────┐
│ Time        ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μs ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64        ┆ ---        ┆ date       │
│ ]           ┆          ┆          ┆          ┆   ┆        ┆            ┆ f64        ┆            │
╞═════════════╪══════════╪══════════╪══════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 2014-08-11  ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 292.0  ┆ 9.40824e6  ┆ 24756.0    ┆ 2014-08-11 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2014-08-12  ┆ 0.996586 ┆ 0.996586 ┆ 0.996586 ┆ … ┆ 140.0  ┆ 4.4954e6   ┆ 25716.0    ┆ 2014-08-12 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2014-08-13  ┆ 0.994724 ┆ 0.994724 ┆ 0.994724 ┆ … ┆ 70.0   ┆ 2.2435e6   ┆ 31912.0    ┆ 2014-08-13 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2014-08-14  ┆ 0.995655 ┆ 0.995655 ┆ 0.995655 ┆ … ┆ 74.0   ┆ 2.37392e6  ┆ 28340.0    ┆ 2014-08-14 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2014-08-15  ┆ 0.993172 ┆ 0.993172 ┆ 0.993172 ┆ … ┆ 44.0   ┆ 1.408e6    ┆ 28070.0    ┆ 2014-08-15 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ …           ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 2021-01-26  ┆ 2.641389 ┆ 2.641389 ┆ 2.641389 ┆ … ┆ 243.0  ┆ 1.7496e6   ┆ 119741.0   ┆ 2021-01-26 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-27  ┆ 2.593697 ┆ 2.593697 ┆ 2.593697 ┆ … ┆ 567.0  ┆ 4.00869e6  ┆ 125151.0   ┆ 2021-01-27 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-28  ┆ 2.563615 ┆ 2.563615 ┆ 2.563615 ┆ … ┆ 717.0  ┆ 5.010396e6 ┆ 124250.0   ┆ 2021-01-28 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-29  ┆ 2.552609 ┆ 2.552609 ┆ 2.552609 ┆ … ┆ 648.0  ┆ 4.508784e6 ┆ 120927.0   ┆ 2021-01-29 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-02-01  ┆ 2.505651 ┆ 2.505651 ┆ 2.505651 ┆ … ┆ 311.0  ┆ 2.12413e6  ┆ 120590.0   ┆ 2021-02-01 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
└─────────────┴──────────┴──────────┴──────────┴───┴────────┴────────────┴────────────┴────────────┘

shape: (3_341, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2014-08-20 ┆ 0.990689 ┆ 0.990689 ┆ 0.990689 ┆ … ┆ 8          ┆ 3         ┆ heise     ┆ CZCE      │
│ 10:48:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2014-08-20 ┆ 0.990689 ┆ 0.990689 ┆ 0.990689 ┆ … ┆ 8          ┆ 3         ┆ heise     ┆ CZCE      │
│ 11:02:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2014-08-21 ┆ 0.988827 ┆ 0.988827 ┆ 0.988516 ┆ … ┆ 8          ┆ 4         ┆ heise     ┆ CZCE      │
│ 13:41:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2014-08-21 ┆ 0.988206 ┆ 0.988206 ┆ 0.988206 ┆ … ┆ 8          ┆ 4         ┆ heise     ┆ CZCE      │
│ 13:45:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2014-08-21 ┆ 0.988827 ┆ 0.988827 ┆ 0.988827 ┆ … ┆ 8          ┆ 4         ┆ heise     ┆ CZCE      │
│ 13:53:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-04-10 ┆ 2.631997 ┆ 2.631997 ┆ 2.631997 ┆ … ┆ 4          ┆ 7         ┆ heise     ┆ CZCE      │
│ 11:19:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-04-10 ┆ 2.631997 ┆ 2.631997 ┆ 2.631997 ┆ … ┆ 4          ┆ 7         ┆ heise     ┆ CZCE      │
│ 14:20:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-04-10 ┆ 2.631997 ┆ 2.631997 ┆ 2.631997 ┆ … ┆ 4          ┆ 7         ┆ heise     ┆ CZCE      │
│ 14:32:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-04-10 ┆ 2.631997 ┆ 2.631997 ┆ 2.631997 ┆ … ┆ 4          ┆ 7         ┆ heise     ┆ CZCE      │
│ 14:35:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2020-08-26 ┆ 2.314321 ┆ 2.314321 ┆ 2.312832 ┆ … ┆ 8          ┆ 3         ┆ heise     ┆ CZCE      │
│ 14:17:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

SA has 0/88086 rows containing None.
SA has bad data:

shape: (6, 9)
┌────────────────┬──────────┬──────────┬──────────┬───┬────────┬───────────┬──────────┬────────────┐
│ Time           ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount    ┆ Open     ┆ TradingDay │
│ ---            ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---       ┆ Interest ┆ ---        │
│ datetime[μs]   ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64       ┆ ---      ┆ date       │
│                ┆          ┆          ┆          ┆   ┆        ┆           ┆ f64      ┆            │
╞════════════════╪══════════╪══════════╪══════════╪═══╪════════╪═══════════╪══════════╪════════════╡
│ 2020-06-17     ┆ 0.826509 ┆ 0.827084 ┆ 0.826509 ┆ … ┆ 14.0   ┆ -9333.0   ┆ 71470.0  ┆ 2020-06-17 │
│ 10:01:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-07-14     ┆ 0.795472 ┆ 0.795472 ┆ 0.794897 ┆ … ┆ 26.0   ┆ -23210.0  ┆ 128105.0 ┆ 2020-07-14 │
│ 10:46:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-08-12     ┆ 0.806967 ┆ 0.806967 ┆ 0.806967 ┆ … ┆ 152.0  ┆ -103858.0 ┆ 100762.0 ┆ 2020-08-12 │
│ 11:09:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-09-23     ┆ 0.877659 ┆ 0.877659 ┆ 0.877148 ┆ … ┆ 241.0  ┆ -125443.0 ┆ 176247.0 ┆ 2020-09-23 │
│ 10:11:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2020-12-02     ┆ 0.740748 ┆ 0.740748 ┆ 0.740237 ┆ … ┆ 184.0  ┆ -20723.0  ┆ 313856.0 ┆ 2020-12-02 │
│ 10:08:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
│ 2021-01-26     ┆ 0.706365 ┆ 0.706365 ┆ 0.705916 ┆ … ┆ 58.0   ┆ -160055.0 ┆ 179777.0 ┆ 2021-01-26 │
│ 14:36:00       ┆          ┆          ┆          ┆   ┆        ┆           ┆          ┆            │
└────────────────┴──────────┴──────────┴──────────┴───┴────────┴───────────┴──────────┴────────────┘

SA has data out of the trading hours:

shape: (115, 9)
┌─────────────┬──────────┬──────────┬──────────┬───┬────────┬────────────┬────────────┬────────────┐
│ Time        ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μs ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64        ┆ ---        ┆ date       │
│ ]           ┆          ┆          ┆          ┆   ┆        ┆            ┆ f64        ┆            │
╞═════════════╪══════════╪══════════╪══════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 2020-08-11  ┆ 0.829383 ┆ 0.829383 ┆ 0.829383 ┆ … ┆ 277.0  ┆ 399711.0   ┆ 100585.0   ┆ 2020-08-12 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-08-12  ┆ 0.813864 ┆ 0.813864 ┆ 0.813864 ┆ … ┆ 272.0  ┆ 385152.0   ┆ 97166.0    ┆ 2020-08-13 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-08-13  ┆ 0.808691 ┆ 0.808691 ┆ 0.808691 ┆ … ┆ 278.0  ┆ 391146.0   ┆ 93249.0    ┆ 2020-08-14 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-08-14  ┆ 0.795472 ┆ 0.795472 ┆ 0.795472 ┆ … ┆ 1149.0 ┆ 1.590216e6 ┆ 87742.0    ┆ 2020-08-15 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2020-08-17  ┆ 0.794897 ┆ 0.794897 ┆ 0.794897 ┆ … ┆ 108.0  ┆ 149364.0   ┆ 71727.0    ┆ 2020-08-18 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ …           ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 2021-01-26  ┆ 0.707262 ┆ 0.707262 ┆ 0.707262 ┆ … ┆ 451.0  ┆ 710776.0   ┆ 177867.0   ┆ 2021-01-27 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-27  ┆ 0.698287 ┆ 0.698287 ┆ 0.698287 ┆ … ┆ 435.0  ┆ 676860.0   ┆ 175991.0   ┆ 2021-01-28 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-28  ┆ 0.719379 ┆ 0.719379 ┆ 0.719379 ┆ … ┆ 453.0  ┆ 726159.0   ┆ 195106.0   ┆ 2021-01-29 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-29  ┆ 0.726111 ┆ 0.726111 ┆ 0.726111 ┆ … ┆ 698.0  ┆ 1.129364e6 ┆ 192933.0   ┆ 2021-01-30 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-02-01  ┆ 0.716238 ┆ 0.716238 ┆ 0.716238 ┆ … ┆ 292.0  ┆ 466032.0   ┆ 181053.0   ┆ 2021-02-02 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
└─────────────┴──────────┴──────────┴──────────┴───┴────────┴────────────┴────────────┴────────────┘

shape: (237, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2019-12-09 ┆ 1.007673 ┆ 1.007673 ┆ 1.007673 ┆ … ┆ 12         ┆ 2         ┆ nengyuanh ┆ CZCE      │
│ 23:02:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-12-09 ┆ 1.007673 ┆ 1.007673 ┆ 1.007033 ┆ … ┆ 12         ┆ 2         ┆ nengyuanh ┆ CZCE      │
│ 23:21:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-12-09 ┆ 1.007673 ┆ 1.008312 ┆ 1.007673 ┆ … ┆ 12         ┆ 2         ┆ nengyuanh ┆ CZCE      │
│ 23:27:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-12-10 ┆ 1.044757 ┆ 1.044757 ┆ 1.044757 ┆ … ┆ 12         ┆ 2         ┆ nengyuanh ┆ CZCE      │
│ 13:41:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2019-12-10 ┆ 1.044757 ┆ 1.044757 ┆ 1.044757 ┆ … ┆ 12         ┆ 2         ┆ nengyuanh ┆ CZCE      │
│ 14:07:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2020-04-28 ┆ 0.841453 ┆ 0.841453 ┆ 0.840878 ┆ … ┆ 4          ┆ 2         ┆ nengyuanh ┆ CZCE      │
│ 13:44:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-04-30 ┆ 0.828808 ┆ 0.828808 ┆ 0.828233 ┆ … ┆ 4          ┆ 4         ┆ nengyuanh ┆ CZCE      │
│ 14:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-05-06 ┆ 0.83513  ┆ 0.83513  ┆ 0.83513  ┆ … ┆ 5          ┆ 3         ┆ nengyuanh ┆ CZCE      │
│ 14:05:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-05-06 ┆ 0.83628  ┆ 0.83628  ┆ 0.835705 ┆ … ┆ 5          ┆ 4         ┆ nengyuanh ┆ CZCE      │
│ 22:48:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
│ 2020-05-07 ┆ 0.835705 ┆ 0.836855 ┆ 0.835705 ┆ … ┆ 5          ┆ 7         ┆ nengyuanh ┆ CZCE      │
│ 22:19:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ uagong    ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

SR has 0/592227 rows containing None.
SR has bad data:

shape: (7, 9)
┌────────────┬──────────┬──────────┬──────────┬───┬───────────┬────────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume    ┆ Amount     ┆ Open      ┆ TradingDa │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---        ┆ Interest  ┆ y         │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64       ┆ f64        ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆           ┆            ┆ f64       ┆ date      │
╞════════════╪══════════╪══════════╪══════════╪═══╪═══════════╪════════════╪═══════════╪═══════════╡
│ 2017-03-20 ┆ 1.126547 ┆ 1.126547 ┆ 1.126547 ┆ … ┆ -657160.0 ┆ -4.4161e10 ┆ 449652.0  ┆ 2017-03-2 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 1         │
│ 2017-03-21 ┆ 1.113471 ┆ 1.113471 ┆ 1.113471 ┆ … ┆ -355322.0 ┆ -2.3600e10 ┆ 456088.0  ┆ 2017-03-2 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 2         │
│ 2018-01-11 ┆ 1.021835 ┆ 1.021835 ┆ 1.021835 ┆ … ┆ -222412.0 ┆ -1.3013e10 ┆ 496300.0  ┆ 2018-01-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 2         │
│ 2018-08-13 ┆ 0.884995 ┆ 0.884995 ┆ 0.884995 ┆ … ┆ -556432.0 ┆ -2.8628e10 ┆ 375088.0  ┆ 2018-08-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 4         │
│ 2018-09-25 ┆ 0.843197 ┆ 0.843197 ┆ 0.843197 ┆ … ┆ -410402.0 ┆ -2.0118e10 ┆ 424688.0  ┆ 2018-09-2 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 5         │
│ 2018-10-16 ┆ 0.883275 ┆ 0.883275 ┆ 0.883275 ┆ … ┆ -728400.0 ┆ -3.7403e10 ┆ 416318.0  ┆ 2018-10-1 │
│ 20:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 7         │
│ 2019-01-02 ┆ 0.806967 ┆ 0.806967 ┆ 0.806967 ┆ … ┆ -724350.0 ┆ -3.3900e10 ┆ 482362.0  ┆ 2019-01-0 │
│ 08:59:00   ┆          ┆          ┆          ┆   ┆           ┆            ┆           ┆ 2         │
└────────────┴──────────┴──────────┴──────────┴───┴───────────┴────────────┴───────────┴───────────┘

SR has data out of the trading hours:

shape: (1_574, 9)
┌─────────────┬──────────┬──────────┬──────────┬───┬────────┬────────────┬────────────┬────────────┐
│ Time        ┆ Open     ┆ High     ┆ Low      ┆ … ┆ Volume ┆ Amount     ┆ Open       ┆ TradingDay │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---    ┆ ---        ┆ Interest   ┆ ---        │
│ datetime[μs ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64    ┆ f64        ┆ ---        ┆ date       │
│ ]           ┆          ┆          ┆          ┆   ┆        ┆            ┆ f64        ┆            │
╞═════════════╪══════════╪══════════╪══════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 2013-09-30  ┆ 1.0      ┆ 1.0      ┆ 0.999803 ┆ … ┆ 1782.0 ┆ 9.024048e7 ┆ 559534.0   ┆ 2013-09-30 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-10-09  ┆ 1.018164 ┆ 1.018164 ┆ 1.018164 ┆ … ┆ 770.0  ┆ 3.97089e7  ┆ 511060.0   ┆ 2013-10-09 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-10-10  ┆ 1.014215 ┆ 1.014215 ┆ 1.014215 ┆ … ┆ 260.0  ┆ 1.33562e7  ┆ 522186.0   ┆ 2013-10-10 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-10-10  ┆ 1.032577 ┆ 1.032774 ┆ 1.032577 ┆ … ┆ 120.0  ┆ 6.2772e6   ┆ 597680.0   ┆ 2013-10-10 │
│ 15:00:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2013-10-11  ┆ 1.034353 ┆ 1.034353 ┆ 1.034353 ┆ … ┆ 2412.0 ┆ 1.2636468e ┆ 596520.0   ┆ 2013-10-11 │
│ 08:59:00    ┆          ┆          ┆          ┆   ┆        ┆ 8          ┆            ┆            │
│ …           ┆ …        ┆ …        ┆ …        ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 2021-01-26  ┆ 0.942481 ┆ 0.942481 ┆ 0.942481 ┆ … ┆ 559.0  ┆ 2.944812e6 ┆ 457092.0   ┆ 2021-01-27 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-27  ┆ 0.948206 ┆ 0.948206 ┆ 0.948206 ┆ … ┆ 841.0  ┆ 4.4573e6   ┆ 463783.0   ┆ 2021-01-28 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-28  ┆ 0.935682 ┆ 0.935682 ┆ 0.935682 ┆ … ┆ 1360.0 ┆ 7.1128e6   ┆ 462076.0   ┆ 2021-01-29 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-01-29  ┆ 0.935146 ┆ 0.935146 ┆ 0.935146 ┆ … ┆ 567.0  ┆ 2.963709e6 ┆ 462430.0   ┆ 2021-01-30 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
│ 2021-02-01  ┆ 0.942839 ┆ 0.942839 ┆ 0.942839 ┆ … ┆ 584.0  ┆ 3.07768e6  ┆ 451849.0   ┆ 2021-02-02 │
│ 20:59:00    ┆          ┆          ┆          ┆   ┆        ┆            ┆            ┆            │
└─────────────┴──────────┴──────────┴──────────┴───┴────────┴────────────┴────────────┴────────────┘

shape: (7, 22)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Time       ┆ Open     ┆ High     ┆ Low      ┆ … ┆ DATA_month ┆ DATA_week ┆ DATA_sect ┆ DATA_exch │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ day       ┆ or        ┆ ange      │
│ datetime[μ ┆ f64      ┆ f64      ┆ f64      ┆   ┆ i8         ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆          ┆          ┆          ┆   ┆            ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2014-10-16 ┆ 0.933046 ┆ 0.933248 ┆ 0.93244  ┆ … ┆ 10         ┆ 4         ┆ nongfucha ┆ CZCE      │
│ 10:04:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2015-07-15 ┆ 1.015578 ┆ 1.015578 ┆ 1.01501  ┆ … ┆ 7          ┆ 4         ┆ nongfucha ┆ CZCE      │
│ 21:35:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2016-01-12 ┆ 1.007785 ┆ 1.008153 ┆ 1.007785 ┆ … ┆ 1          ┆ 3         ┆ nongfucha ┆ CZCE      │
│ 22:59:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2018-07-19 ┆ 0.869374 ┆ 0.870082 ┆ 0.869198 ┆ … ┆ 7          ┆ 7         ┆ nongfucha ┆ CZCE      │
│ 21:03:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-05-23 ┆ 0.852369 ┆ 0.853235 ┆ 0.852369 ┆ … ┆ 5          ┆ 4         ┆ nongfucha ┆ CZCE      │
│ 10:34:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2019-06-28 ┆ 0.869704 ┆ 0.869704 ┆ 0.869184 ┆ … ┆ 6          ┆ 7         ┆ nongfucha ┆ CZCE      │
│ 11:02:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
│ 2020-02-04 ┆ 0.993841 ┆ 0.993841 ┆ 0.993841 ┆ … ┆ 2          ┆ 2         ┆ nongfucha ┆ CZCE      │
│ 13:46:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆ npin      ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [13]:
s = "I"
d = pl.datetime(2014,12,27)
with pl.Config(tbl_rows=1000):
    display(
        get_raw_data(s).with_columns([
            pl.col("Time").str.strptime(
                pl.Datetime("us"),
                "%Y-%m-%d %H:%M:%S%.6f",
                strict=False
            ).dt.truncate("1m"),
        ]).filter(pl.col("Time").dt.date() == d)
    )

shape: (137, 8)
┌─────────────────┬──────────┬──────────┬──────────┬──────────┬────────┬───────────┬───────────────┐
│ Time            ┆ Open     ┆ High     ┆ Low      ┆ Close    ┆ Volume ┆ Amount    ┆ Open Interest │
│ ---             ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---    ┆ ---       ┆ ---           │
│ datetime[μs]    ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64    ┆ f64       ┆ f64           │
╞═════════════════╪══════════╪══════════╪══════════╪══════════╪════════╪═══════════╪═══════════════╡
│ 2014-12-27      ┆ 0.546384 ┆ 0.547531 ┆ 0.546384 ┆ 0.546384 ┆ 60.0   ┆ 2.8564e6  ┆ 697312.0      │
│ 00:00:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.547531 ┆ 0.546384 ┆ 0.546384 ┆ 10.0   ┆ 476200.0  ┆ 697316.0      │
│ 00:01:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 18.0   ┆ 856800.0  ┆ 697330.0      │
│ 00:02:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 10.0   ┆ 476000.0  ┆ 697340.0      │
│ 00:03:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 4.0    ┆ 190400.0  ┆ 697344.0      │
│ 00:04:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 270.0  ┆ 1.2852e7  ┆ 697370.0      │
│ 00:05:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 16.0   ┆ 761600.0  ┆ 697376.0      │
│ 00:06:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 70.0   ┆ 3.332e6   ┆ 697382.0      │
│ 00:07:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 24.0   ┆ 1.1424e6  ┆ 697360.0      │
│ 00:08:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 132.0  ┆ 6.2832e6  ┆ 697268.0      │
│ 00:09:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 8.0    ┆ 380800.0  ┆ 697272.0      │
│ 00:10:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 24.0   ┆ 1.1424e6  ┆ 697292.0      │
│ 00:11:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 12.0   ┆ 571200.0  ┆ 697292.0      │
│ 00:12:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 4.0    ┆ 190400.0  ┆ 697292.0      │
│ 00:13:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.0    ┆ 0.0       ┆ 697292.0      │
│ 00:14:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.547531 ┆ 0.546384 ┆ 0.546384 ┆ 52.0   ┆ 2.4794e6  ┆ 697260.0      │
│ 00:16:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 10.0   ┆ 476000.0  ┆ 697268.0      │
│ 00:17:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.547531 ┆ 0.546384 ┆ 0.547531 ┆ 4.0    ┆ 190600.0  ┆ 697270.0      │
│ 00:18:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.547531 ┆ 0.547531 ┆ 0.546384 ┆ 0.546384 ┆ 4.0    ┆ 190400.0  ┆ 697272.0      │
│ 00:19:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 10.0   ┆ 476000.0  ┆ 697272.0      │
│ 00:20:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.0    ┆ 0.0       ┆ 697272.0      │
│ 00:21:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.0    ┆ 0.0       ┆ 697272.0      │
│ 00:22:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.0    ┆ 0.0       ┆ 697272.0      │
│ 00:23:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 6.0    ┆ 285600.0  ┆ 697272.0      │
│ 00:24:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 10.0   ┆ 476000.0  ┆ 697282.0      │
│ 00:25:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 4.0    ┆ 190400.0  ┆ 697286.0      │
│ 00:26:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.0    ┆ 0.0       ┆ 697286.0      │
│ 00:27:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 2.0    ┆ 95200.0   ┆ 697288.0      │
│ 00:28:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 2.0    ┆ 95200.0   ┆ 697290.0      │
│ 00:29:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 44.0   ┆ 2.0944e6  ┆ 697294.0      │
│ 00:30:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.547531 ┆ 0.546384 ┆ 0.546384 ┆ 36.0   ┆ 1.7156e6  ┆ 697298.0      │
│ 00:31:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 104.0  ┆ 4.9504e6  ┆ 697246.0      │
│ 00:32:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 48.0   ┆ 2.2848e6  ┆ 697204.0      │
│ 00:33:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.0    ┆ 0.0       ┆ 697204.0      │
│ 00:34:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 116.0  ┆ 5.5216e6  ┆ 697098.0      │
│ 00:35:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 4.0    ┆ 190400.0  ┆ 697098.0      │
│ 00:36:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 16.0   ┆ 761600.0  ┆ 697082.0      │
│ 00:37:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.0    ┆ 0.0       ┆ 697082.0      │
│ 00:38:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.545236 ┆ 0.546384 ┆ 58.0   ┆ 2.7596e6  ┆ 697086.0      │
│ 00:39:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 6.0    ┆ 285600.0  ┆ 697086.0      │
│ 00:40:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 426.0  ┆ 2.02776e7 ┆ 696664.0      │
│ 00:41:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 38.0   ┆ 1.8088e6  ┆ 696696.0      │
│ 00:42:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.0    ┆ 0.0       ┆ 696696.0      │
│ 00:43:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.0    ┆ 0.0       ┆ 696696.0      │
│ 00:44:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 16.0   ┆ 761600.0  ┆ 696710.0      │
│ 00:45:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.0    ┆ 0.0       ┆ 696710.0      │
│ 00:46:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.547531 ┆ 0.546384 ┆ 0.546384 ┆ 6.0    ┆ 286000.0  ┆ 696708.0      │
│ 00:47:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.547531 ┆ 0.546384 ┆ 0.547531 ┆ 14.0   ┆ 667800.0  ┆ 696694.0      │
│ 00:48:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.547531 ┆ 0.547531 ┆ 0.546384 ┆ 0.546384 ┆ 8.0    ┆ 381400.0  ┆ 696688.0      │
│ 00:49:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.0    ┆ 0.0       ┆ 696688.0      │
│ 00:50:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 42.0   ┆ 1.9992e6  ┆ 696730.0      │
│ 00:51:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.547531 ┆ 0.547531 ┆ 0.546384 ┆ 0.546384 ┆ 18.0   ┆ 857000.0  ┆ 696740.0      │
│ 00:52:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 6.0    ┆ 285600.0  ┆ 696740.0      │
│ 00:54:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 6.0    ┆ 285600.0  ┆ 696740.0      │
│ 00:55:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 2.0    ┆ 95200.0   ┆ 696740.0      │
│ 00:56:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.547531 ┆ 0.546384 ┆ 0.547531 ┆ 150.0  ┆ 7.155e6   ┆ 696740.0      │
│ 00:57:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 6.0    ┆ 285600.0  ┆ 696746.0      │
│ 00:58:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 22.0   ┆ 1.0472e6  ┆ 696766.0      │
│ 00:59:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.547531 ┆ 0.546384 ┆ 0.547531 ┆ 64.0   ┆ 3.0476e6  ┆ 696760.0      │
│ 01:00:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.547531 ┆ 0.547531 ┆ 0.546384 ┆ 0.546384 ┆ 22.0   ┆ 1.0474e6  ┆ 696738.0      │
│ 01:01:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 20.0   ┆ 952000.0  ┆ 696718.0      │
│ 01:02:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 274.0  ┆ 1.30424e7 ┆ 696490.0      │
│ 01:03:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.0    ┆ 0.0       ┆ 696490.0      │
│ 01:04:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 2.0    ┆ 95200.0   ┆ 696490.0      │
│ 01:05:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.0    ┆ 0.0       ┆ 696490.0      │
│ 01:06:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.545236 ┆ 0.545236 ┆ 58.0   ┆ 2.7606e6  ┆ 696434.0      │
│ 01:07:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 126.0  ┆ 5.985e6   ┆ 696346.0      │
│ 01:08:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 126.0  ┆ 5.985e6   ┆ 696386.0      │
│ 01:09:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.0    ┆ 0.0       ┆ 696386.0      │
│ 01:10:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.545236 ┆ 0.546384 ┆ 0.545236 ┆ 0.545236 ┆ 44.0   ┆ 2.0902e6  ┆ 696372.0      │
│ 01:11:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.0    ┆ 0.0       ┆ 696372.0      │
│ 01:12:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.545236 ┆ 0.546384 ┆ 0.545236 ┆ 0.545236 ┆ 20.0   ┆ 951000.0  ┆ 696362.0      │
│ 01:13:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.0    ┆ 0.0       ┆ 696362.0      │
│ 01:14:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.545236 ┆ 0.546384 ┆ 0.545236 ┆ 0.545236 ┆ 20.0   ┆ 951600.0  ┆ 696344.0      │
│ 01:15:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.0    ┆ 0.0       ┆ 696344.0      │
│ 01:16:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.0    ┆ 0.0       ┆ 696344.0      │
│ 01:17:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.0    ┆ 0.0       ┆ 696344.0      │
│ 01:18:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.0    ┆ 0.0       ┆ 696344.0      │
│ 01:19:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 20.0   ┆ 950000.0  ┆ 696324.0      │
│ 01:21:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.0    ┆ 0.0       ┆ 696324.0      │
│ 01:22:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 4.0    ┆ 190400.0  ┆ 696320.0      │
│ 01:23:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.0    ┆ 0.0       ┆ 696320.0      │
│ 01:24:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.0    ┆ 0.0       ┆ 696320.0      │
│ 01:25:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 24.0   ┆ 1.1424e6  ┆ 696320.0      │
│ 01:26:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.545236 ┆ 0.545236 ┆ 2.0    ┆ 95000.0   ┆ 696320.0      │
│ 01:27:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.0    ┆ 0.0       ┆ 696320.0      │
│ 01:28:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.545236 ┆ 0.546384 ┆ 0.545236 ┆ 0.546384 ┆ 8.0    ┆ 380800.0  ┆ 696312.0      │
│ 01:29:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 18.0   ┆ 855000.0  ┆ 696314.0      │
│ 01:30:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.0    ┆ 0.0       ┆ 696314.0      │
│ 01:31:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 14.0   ┆ 665000.0  ┆ 696316.0      │
│ 01:32:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.0    ┆ 0.0       ┆ 696316.0      │
│ 01:33:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.0    ┆ 0.0       ┆ 696316.0      │
│ 01:34:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 6.0    ┆ 285000.0  ┆ 696314.0      │
│ 01:35:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.0    ┆ 0.0       ┆ 696314.0      │
│ 01:36:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 0.545236 ┆ 150.0  ┆ 7.125e6   ┆ 696320.0      │
│ 01:37:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │
│ 2014-12-27      ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 0.546384 ┆ 126.0  ┆ 5.9976e6  ┆ 696194.0      │
│ 01:38:00        ┆          ┆          ┆          ┆          ┆        ┆           ┆               │

In [14]:
symbol_with_null

['FB']

In [16]:
def add_return(s: str, w: int, y_old=None):
    df = pl.read_parquet(
        f"{PROJ_ROOT}/data/cleaned_data/{s}.parquet"
    ).select([
        "Time", "Symbol", "Close", "DATA_is_trading_hour", 
        "DATA_is_day_session", "DATA_is_bad_data", "DATA_is_last_30min"
    ])
    df_w = df.select(["Time", "Close"]).with_columns([
        (pl.col("Time") - pl.duration(minutes=w)).alias("Time")
    ]).rename({"Close": f"Close_t+{w}"})
    df_w15 = df.select(["Time", "Close"]).with_columns([
        (pl.col("Time") - pl.duration(minutes=15+w)).alias("Time")
    ]).rename({"Close": f"Close_t+{15+w}"})
    df_w120 = df.select(["Time", "Close"]).with_columns([
        (pl.col("Time") - pl.duration(minutes=120+w)).alias("Time")
    ]).rename({"Close": f"Close_t+{120+w}"})
    df = df.join(df_w, on="Time", how="left").join(df_w15, on="Time", how="left").join(df_w120, on="Time", how="left")
    y = df.with_columns([
        pl.when(
            pl.col("DATA_is_last_30min")
        ).then(None).when(
            get_session_expr(minus_time(time(10,14),w-1), time(10,14))
        ).then(
            (pl.col(f"Close_t+{15+w}") / pl.col("Close") - 1)
        ).when(
            get_session_expr(minus_time(time(11,29),w-1), time(11,29))
        ).then(
            (pl.col(f"Close_t+{120+w}") / pl.col("Close") - 1)
        ).otherwise(
            (pl.col(f"Close_t+{w}") / pl.col("Close") - 1)
        ).alias(f"ret_{w}min")
    ]).select(["Time", "Symbol", f"ret_{w}min"])
    if y_old is None:
        return y
    else:
        return y_old.join(y, on=["Time", "Symbol"], how="left")

In [18]:
from tqdm.auto import tqdm
for s in tqdm(SYMBOLS):
    for w in range(1,31):
        if w == 1:
            y_old = add_return(s,w)
        else:
            y_old = add_return(s,w,y_old)
    y_old.write_parquet(f"{PROJ_ROOT}/data/labels/{s}.parquet", compression="zstd")

  0%|          | 0/51 [00:00<?, ?it/s]